### ISSUE TITLE
Gallery view of Guest listing and state as paused, both Running and disconnected are shown

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#1013]
Gallery view of Guest listing and state as paused both Running and disconnected are shown. 
I will suggest to show state as Paused instead.
![db67ee92ef29403](https://cloud.githubusercontent.com/assets/12509490/18509027/49b4e8b8-7a94-11e6-9d5b-2078b8affeec.jpg)

**Comment by alinefm** [comment]
Duplicated of #1005
