### ISSUE TITLE
List view of Guest listing and non of icon shown for a guest have tool-tip. 

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#1014]
List view of Guest listing and non of icon shown for a guest have tool-tip. 
![174538a4c9c97d67](https://cloud.githubusercontent.com/assets/12509490/18509172/e04a7fcc-7a94-11e6-95dd-6d2b8848f799.jpg)

**Comment by alinefm** [comment]
Duplicated of #1005
