### ISSUE TITLE
Ubuntu-16.04: Unable to search peers when using Federation.

### ISSUE THREAD

**Issue by pvital** [kimchi-project/kimchi#1032]
After set up to use federation on both Kimchi hosts, it was not able to find peers:

![screenshot from 2016-09-14 15-53-31](https://cloud.githubusercontent.com/assets/699330/18525616/a1370afe-7a93-11e6-8567-0cf2f956bb9d.png)

No error messages printed in wok-error.log neither slpd.log (from both sides).

**Comment by alinefm** [comment]
@pvital are you running on top of master branch for all the projects?
The peers federation is now loaded on Dashboard tab, extending Ginger Base plugin.
That way, you should not see the Peers drop down menu and instead of that, have a new section of Peers in Dashboard tab.

**Comment by pvital** [comment]
I ran with the following commits (all HEAD of the branches when announced the code freeze for 2.3 release):

- wok: https://github.com/kimchi-project/wok/commit/8e5a84d592ab9efad6dd85da867af7356ae62999
- gingerbase: https://github.com/lcorreia/gingerbase/commit/b51c6ae7a0ff08b4eca2c1382e8a72ba34fb91ec
- kimchi: https://github.com/kimchi-project/kimchi/commit/2be8daa352715fc51e16a37aac04ce956f397486
- ginger: https://github.com/lcorreia/ginger/commit/b06e89a8cb4d33843b083c02d97b83a889cd2a0e

**Comment by alinefm** [comment]
Fixed by https://github.com/kimchi-project/wok/commit/4bbfcd1b252d2f5cfc1d7e2a7485ae5fd76a0503
