### ISSUE TITLE
Error shown on clicking "Edit" button for NAT/isolated virtual networks

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#1033]
The following message is showed on error log when clicking on Edit button for a NAT/isolated network:
KCHIFACE0001E: Interface virbr1 does not exist

**Comment by lcorreia** [comment]
Reproducible on Ubuntu 16.10

**Comment by alinefm** [comment]
I am unable to reproduce that in my Ubuntu 16.10 system.
I could create/edit/stop/delete a NAT/isolated network without problems.

I am closing this bug by now. Please, feel free to reopen if the problem persists to you.
