### ISSUE TITLE
Fedora 24: Unable to Add a Storage Device to a running VM

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/kimchi#1039]
![screen shot 2016-09-15 at 5 03 53 pm](https://cloud.githubusercontent.com/assets/6681745/18565546/84271afc-7b66-11e6-9885-1b30cae2d930.png)

**Comment by pvital** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Kc7DVyeT&#x2F;50-kimchi-issue-fedora-24-unable-to-add-a-storage-device-to-a-running-vm"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [kimchi] issue - Fedora 24: Unable to Add a Storage Device to a running VM</a>

**Comment by pvital** [comment]
I could not reproduce this issue, using Fedora 24 as host and commit f0016f4 as HEAD.

I could {cold, hot}-plug and {cold, hot}-unplug  an existent disk image in two different VM's (Fedora 23 and Ubuntu 16.04) using Google Chrome (Version 53.0.2785.92) and Firefox (Version 48.0.1) browsers.

@biancafc can you re-test it again?

**Comment by biancafc** [comment]
I've tried to reproduce this issue again but it didn't happen, not sure why.
