### ISSUE TITLE
Problem on renaming local-img based template on RHEL 7.2

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#1040]
Got the following error message in access log. No error message in error log.

INFO:wok_request_logger:{"info": {"status": 500, "zone": "BRT", "ip": "192.168.122.1", "app": "/plugins/kimchi", "req": "PUT", "user": "dev", "time": "18:13:22", "date": "2016-09-15"}, "message": {"code": "KCHTMPL0003L", "params": {"ident": "1852ebf5-323b-48b0-a450-2c9f0d06b374"}}, "id": "e85dd7ea-2db5-412f-aa9d-c2b2e8fad417", "error": null}

Despite took a long time, renaming worked.

**Comment by alinefm** [comment]
Hi @lcorreia 

it is not an error message. It is an information message which represents the action you took on template.
From what I investigate the code "KCHTMPL0003L" is for the message "Update template '%(ident)s'", ie, no error is throw or reported.
