### ISSUE TITLE
Fedora 24: Unable to deactivate logical storage pool

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/kimchi#1042]
![screen shot 2016-09-15 at 6 33 28 pm](https://cloud.githubusercontent.com/assets/6681745/18568298/f8e57706-7b72-11e6-9da0-55ce92ae77c4.png)

**Comment by alinefm** [comment]
Hi @biancafc 

The error is probably because you have a LVM (/dev/fedora) which is in use by the system.
I suspect it is the LVM which has the OS installed. So you will not be able to deactivate it, otherwise you will crash your system. =)
