### ISSUE TITLE
Unable to start VM created from remote-url based template on RHEL 7.2

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#1043]
Error showed:

KCHVM0019E: Unable to start virtual machine remote-url. Details: internal error: process exited while connecting to monitor: 2016-09-16T16:49:04.869227Z qemu-kvm: -drive file=http://mirrors.kernel.org:80/fedora/releases/24/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-24-1.2.iso,if=none,id=drive-ide0-1-0,readonly=on,format=raw: could not open disk image http://mirrors.kernel.org:80/fedora/releases/24/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-24-1.2.iso: Driver 'http' is not whitelisted

**Comment by lcorreia** [comment]
This is a duplicated of #1021

**Comment by urako** [comment]
I also sow this.

Both bug #1021 and #1043 is marked as each others duplicate and both was closed.

Is this getting anywhere to being fixed?

**Comment by jhass** [comment]
#1021 is still open.
