### ISSUE TITLE
boot order fix for guest edit 

### ISSUE THREAD

**Issue by harche** [kimchi-project/kimchi#1045]
Whenever the guest is edited the boot order is edited (even if not explicitly specified). This is because of an incorrect condition which checks for boot order (https://github.com/kimchi-project/kimchi/blob/next/model/vms.py#L879)

also on s390x we would always like the first bootable device to be 'cdrom'.

I will work on this issue.

**Comment by alinefm** [comment]
Duplicated of #1012
