### ISSUE TITLE
Live Migration Option

### ISSUE THREAD

**Issue by shawniverson** [kimchi-project/kimchi#1055]
This would be really cool.  I'm not familiar with the kimchi plugin code, but if I get some time I may dig into this and issue a PR...

Basically like the migrate option, except it will do it live and present a warning that this only works on kvm hosts with shared storage.

**Comment by danielhb** [comment]
We already have this option in Kimchi. It's the "Migrate" option. It will do a live migration if the guest is turned on, cold migration if turned off.

**Comment by shawniverson** [comment]
Oh, that is great!  I missed that detail.
