### ISSUE TITLE
Failed to import kimchi

### ISSUE THREAD

**Issue by GerhardK90** [kimchi-project/kimchi#1057]
Hello,
I have updated wok from 2.2.0 to 2.3.0 now I got a problem with kimchi:

**Failed to import plugin plugins.kimchi.Kimchi, error: 'module' object has no attribute 'VIR_DOMAIN_EVENT_ID_DEVICE_ADDED'**

My libvirt version is 1.2.9
I am on debian 8 with kernel version 3.16.0-4-amd64

I also tried to update kimchi but still got this error.

Thank you for your help!

**Comment by geunieve** [comment]
Hello,

I have the same error with  debian 8.6 with kernel version 4.5.7-std-3

**Comment by shii1** [comment]
I have same error.
But freshly installed jessie without any customization yet.

**Comment by JoseGoncalves** [comment]
Same here.
The problem is due to libvirt's event VIR_DOMAIN_EVENT_ID_DEVICE_ADDED.
This event was added in libvirt 1.2.15 and Debian Jessie uses libvirt 1.2.9.

**Comment by bkralik** [comment]
Same for me. Anyone planning to fix this?

**Comment by aarepajuste** [comment]
Has anyone tried a  < 1.2.15 version of libvirt?

**Comment by JoseGoncalves** [comment]
@aarepajuste anyone that uses an unmodified version of Debian jessie uses libvirt < 1.2.15, more precisely, 1.2.9.
