### ISSUE TITLE
Failed to migrate guest back to original host. - (man-in-the-middle attack error)

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#1065]
Steps to reproduce:
1. Migrate a guest-1 from host-A to host-B.
2. Migrate the guest-1 from host-B to original host-A.
3. Failed with following error -

   KCHVM0066E: Unable to determine remote host hypervisor and architecture. Error: Cannot recv data: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @ WARNING:  
   REMOTE HOST IDENTIFICATION HAS CHANGED! @ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY! Someone could  
   be eavesdropping on you right now (man-in-the-middle attack)! It is also possible that a host key has just been changed. The fingerprint for the ECDSA key sent by the  
   remote host is 82:59:08:b4:42:71:02:1d:b4:e9:5b:10:57:fb:b6:af. Please contact your system administrator. Add correct host key in /root/.ssh/known_hosts to get rid of  
   this message. Offending ECDSA key in /root/.ssh/known_hosts:1 ECDSA host key for 9.x.x.103 has changed and you have requested strict checking.  
   Host key verification failed.: Connection reset by peer

**Comment by danielhb** [comment]
@jay-katta the backend of live migration changed quite a bit after @archu-s changes. Can you please test it again?

**Comment by danielhb** [comment]
@jay-katta just tried this scenario and it worked. My guess is that in your env the ssh login from host B to A is failing due to the change of the ECDSA fingerprint of host A. This is purely a SSH error.

Free free to reopen this issue if you fix the ssh back and forth login between host A and B and the migration keeps failing.
