### ISSUE TITLE
"Delete guest" , is giving the error in log file

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#1066]
"Delete guest" , is giving the following error in the log file- 
WOKOBJST0001E: Unable to find 18d0efd1-1297-4a90-99be-280596a5c70b in datastore 
Unable to get storage volume by path: Storage volume not found: no storage vol with matching path '/var/lib/libvirt/images/18d0efd1-1297-4a90-99be-280596a5c70b-0.img' 

Steps to reproduce 
1. Add the template from iso 
2. Add guest using the above template 
3. Delete the above guest 
4. wok-error.log prints the above error messages

**Comment by alinefm** [comment]
It is because Kimchi is not storing storage volume on database anymore but seems while deleting the guest, Kimchi still tries to delete the storage volume information from the database.
