### ISSUE TITLE
VirtualBox guest

### ISSUE THREAD

**Issue by JulioJu** [kimchi-project/kimchi#1078]
Hi,

Is it possible to manage VirtualBox guest into Kimchi ? When I run a VirtualBox guest with kvm hypervisor, I see nothing in Kimchi on the tab  Virtualization / Guests.

Thinks in advance for your answer !

JulioJu

**Comment by alinefm** [comment]
Hi @JulioJu 

Kimchi relies on libvirt to manage virtual machines. So you will only see the virtual machines that libvirt shows to you on "virsh list --all"

**Comment by JulioJu** [comment]
Ok thanks ;-) !
