### ISSUE TITLE
Cannot create a NFS storage

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/kimchi#1082]
I'm not able to add a new NFS storage in Fedora 25:

<img width="820" alt="captura de tela 2016-12-06 as 18 07 09" src="https://cloud.githubusercontent.com/assets/6681745/20941971/38fab06a-bbe0-11e6-8ba5-6d11b75949bd.png">

wok error log:
```
KCHPOOL0013E: Unable to create NFS Pool as export path 127.0.0.1:/home/bianca/dir-test mount failed
rc: 32 error: umount: 127.0.0.1:/home/bianca/dir-test: mountpoint not found
 returned from cmd: umount -f 127.0.0.1:/home/bianca/dir-test
```

**Comment by alinefm** [comment]
Hi @biancafc 

Seems your NFS server is not right configured.
Could you paste the output of "showmount -e" ?

**Comment by biancafc** [comment]
I guess my configuration was missing something. I've tested again and this time it's working fine.
