### ISSUE TITLE
Kimchi backup

### ISSUE THREAD

**Issue by ProofWoW** [kimchi-project/kimchi#1085]
Hello,
who can help me, how i can make a full backup of Kimchi VM's ?
Thanks

**Comment by alinefm** [comment]
Hi @ProofWoW 

Kimchi runs on top of libvirt so the main guest configuratio is hold by libvirt in the guest XML.

To full backup the guest you will need to keep attention on:

- Guest disks: the default path is /var/lib/libvirt/images but the guests can have disks not in that directory.
To confirm which files you need to backup check the disks paths in Edit Guest > Storage tab
- libvirt guest XML: /etc/libvirt/qemu
- Kimchi guest info: /usr/share/kimchi/objectstore

I think that is all related to guest backup. Hope it helps.

**Comment by diego-vieira** [comment]
Just found this:
https://gist.github.com/cabal95/e36c06e716d3328b512b

**Comment by alinefm** [comment]
I will close the issue by now. Feel free to reopen if you need more support on that.
