### ISSUE TITLE
Fix javascript long lines

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#1086]
Maximum line lenght for a javascript filee in Debian is 512 characters.

Fix those kimchi files:
    ui/spice-html5/thirdparty/sha1.js line length is 755 characters (>512)

**Comment by alinefm** [comment]
Hi @lcorreia 

The file you pointed is imported from spice-html5 project. It should not be part of the debian/ubuntu package as debian/ubuntu has the correspondent spice-html5 into the official repositories.

I have confirmed and make-deb does it properly:

```
alinefm@alinefm-Standard-PC-i440FX-PIIX-1996:~/wok/src/wok/plugins/kimchi$ dpkg --contents kimchi-2.3.0-79.git94a5499.noarch.deb | grep spice
drwxr-xr-x root/root         0 2016-12-19 14:40 ./usr/share/wok/plugins/kimchi/ui/spice-html5/
drwxr-xr-x root/root         0 2016-12-19 14:40 ./usr/share/wok/plugins/kimchi/ui/spice-html5/pages/
-rw-r--r-- root/root      7444 2016-12-19 14:40 ./usr/share/wok/plugins/kimchi/ui/spice-html5/pages/spice_auto.html
```

The only file needed is the HTML which was modified by us to point to the right JS location.

Said that, I don't think we need to do anything related to that.
I can point to you the non-minified files but again, the spice-html5 JS files should not be part of the package.

They are only added when using the build option "--with-spice-html5"

**Comment by lcorreia** [comment]
I agree. Lintian complains about it because it's in the source tarball. I've added an override to document that.

**Comment by alinefm** [comment]
Ok. So I will close this issue by now.
