### ISSUE TITLE
 During hot-unplug of a single VF, all the VF's of the PF are getting detached. 

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#1096]

**Comment by danielhb** [comment]
I verified that the problem occurs in a Host OS Cent OS build. After hot plugging 3 virtual functions (CX4 card), hot unplugging the most recently hot plugging VF cause all 3 VFs to be hot unplugged too.

I am looking into it.

**Comment by danielhb** [comment]
Bug is invalid. The bug was reporter in a version of Host OS where SR-IOV isn't supported yet.

**Comment by danielhb** [comment]
I am reopening the bug because there is some flaws in Kimchi backend that are provoking this bug.
