### ISSUE TITLE
no virtualization tab in centos

### ISSUE THREAD

**Issue by cake99** [kimchi-project/kimchi#1097]
I have installed kimchi based on the redhat documentation you have on your site.  I can access teh web page but cannot do much (i don't have the virtualizarion tab, only the host tab and Wok).  What am i missing?

**Comment by artooro** [comment]
I'm having the same issue on ubuntu. Installed kimchi and the config is enabled under /etc/wok/plugins.d and gingerbase works just fine. But kimchi does not appear under the web interface.

**Comment by artooro** [comment]
In /var/log/wok/wok-error.log I see 

```
*** Kimchi: Running dependable feature tests ***
[23/Dec/2016:11:49:18] ENGINE Started monitor thread 'Session cleanup'.
QEMU stream support .......: False
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***

[23/Dec/2016:11:49:18] ENGINE Bus STARTED
WOKAUTH0002E: You are not authorized to access Kimchi
```

**Comment by artooro** [comment]
In my case from reading further, it looks like kimchi tries to create a new storage pool called images while this is a pre-existing KVM installation and I already had a storage pool called images. I don't want to delete the existing one because it contains live disks. So not sure what to do.

```
Fatal: Unable to create storage pool default. 
Details: operation failed: Storage source conflict with pool: 'images'
Failed to import plugin plugins.kimchi.Kimchi, error: Storage pool default does not exist or is not active. Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
```

**Comment by artooro** [comment]
Resolved by editing /etc/kimchi/template.conf and setting all the fields.
It wasn't enough to only do the storage section. I had to do everything. Once edited kimchi started up OK with a `systemctl restart wokd.service`

**Comment by alinefm** [comment]
Hi @artooro 

The libvirt default storage pool points to /var/lib/libvirt/images and what Kimchi tries to do is to enable this storage pool to be used.
In your case, your system does not have the libvirt default storage pool, instead of that the pool called 'images'

I am not sure it is from a configuration change in your system or some Linux distribution specific detail.
Which OS are you using?

**Comment by wammz** [comment]
Hi @artooro,
I'm facing the challenge on Centos 7.3 (https://github.com/kimchi-project/kimchi/issues/1103#issuecomment-276932594).
Do you mind telling me which flags you changed in /etc/kimchi/template.conf to make it work?
