### ISSUE TITLE
Guest disk names

### ISSUE THREAD

**Issue by catborise** [kimchi-project/kimchi#1101]
Hi,

It is very nice and smooth application but whenever i create a guest from template, it gives disk names randomly. Usually it causes some problems. Could the disk names can be same as guest name? why random names? (could it be patched by me?) 

thanks

**Comment by alinefm** [comment]
Hi @catborise 

Which problems are you getting due the disks names do not match the guest name?

In past, Kimchi created the disks names according to guest name, but as Kimchi supports internationalization, the guest name may contain any type of character and some of them not allowed as file name. (Think about Japonese/Chinese characters, for example)

Of course, any patch is welcome! We just need to understand better your scenario and provide the best solution to final user. =)

Today, on Storage Volume management view, you can get an idea on which volumes are in used by which guests so maybe it may avoid problems on deleting a volume still in use (not user that is one of the problems you mentioned above)

Please, feel free to share your thoughts on that and submit patches as well.

**Comment by catborise** [comment]
i have 6 virtualization host and 50 vm. All images on nfs share(/var/lib/libvirt/images). 
basic administrators uses web gui but others uses cli. backup, restore, resizing, various checking operations are performed by cli. so if we use random names for vms, there is a mess. we cannot distinguish them easily. 

if there is a problem with kimchi or related app how can we elaborate which vm or its disk. we may use libvirt to specify disk and vm names but why... random names may useful for cloud if vms are your cattle, but your virtual machines are your cats and dogs random names come nothing with burden.

i hope i can specify myself :)

thanks.

**Comment by alinefm** [comment]
I understand your point @catborise 
But how do we can solve it without having problems with special characters? (as I have explained above)
