### ISSUE TITLE
Can not see Virtualisation tab in kimchi 

### ISSUE THREAD

**Issue by wammz** [kimchi-project/kimchi#1103]
Hi
I followed instructions on the kimchi pages but after logging into kimchi as root, i do not see the Virtualisation tab under Host. Did I miss a package or do i need to do any configs on libvirt?

My environment is Wok 2.3.1-0, Ginger 2.3.1-0, ginger-base 2.2.2-0. Its on CentOS 7.3

**Comment by alinefm** [comment]
Hi @wammz 

You need to install Kimchi http://kimchi-project.github.io/kimchi/downloads/
Ginger is not needed to get Kimchi installed - only Wok and Ginger Base.

**Comment by wammz** [comment]
i installed it but still it doesnt appear (virtualisation tab). i had to un-install and re-install but with no success.

**Comment by alinefm** [comment]
Check the logs and paste the output here. When Wok is not able to load a plugin there is an error there.

**Comment by wammz** [comment]
hi, 
thanks for the quick response. Here is what the wok-error.log is saying:
Fatal: Unable to create storage pool default. 
Details: operation failed: Storage source conflict with pool: 'images'
Failed to import plugin plugins.kimchi.Kimchi, error: Storage pool default does not exist or is not active. Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
[02/Feb/2017:13:35:34] ENGINE Listening for SIGHUP.
[02/Feb/2017:13:35:34] ENGINE Listening for SIGTERM.
[02/Feb/2017:13:35:34] ENGINE Listening for SIGUSR1.
[02/Feb/2017:13:35:34] ENGINE Bus STARTING
[02/Feb/2017:13:35:34] ENGINE Serving on 127.0.0.1:8010

*** Kimchi: Running dependable feature tests ***
[02/Feb/2017:13:35:34] ENGINE Started monitor thread 'Session cleanup'.
QEMU stream support .......: False
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***

[02/Feb/2017:13:35:34] ENGINE Bus STARTED

**Comment by alinefm** [comment]
Kimchi uses by default the libvirt 'default' network and storage pool.
Seems your system has a pool called 'images' pointing to /var/lib/libvirt/images
Change the /etc/kimchi/template.conf to point to the right storage pool name.
Also check if the default network is active: sudo virsh net-list --all

There was another bug which the person reported the issue with the default storage pool.
Could you tell me if you did any change on that area or libvirt changed the default storage pool name to 'images'?

After doing the changes in template.conf file, restart wokd.

**Comment by wammz** [comment]
Hi, the only change on this KVM installation is addition of a single bridge interface.
What exactly do i do to point to the right storage pool? My default setting in template.conf says pool= default and its commented and virsh net-list --all give the following:
sudo virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes

**Comment by alinefm** [comment]
Check the pools in libvirt: sudo virsh pool-list --all
 Is there a default pool there or only 'images' ?

**Comment by wammz** [comment]
hi,
So i changed (in temlate.conf)  #pool= default to 
pool=pool1
this was after creating a new pool (named pool1) and new volume (vol1) in virt-manager and now i see the Virtualisation tab in kimchi.
by the way the result for sudo virsh pool-list --all is now:
sudo virsh pool-list --all
 Name                 State      Autostart 
-------------------------------------------
 images               active     yes       
 ISO                  active     yes       
 pool1                active     yes       
 root                 active     yes

**Comment by alinefm** [comment]
Great! I will check if the libvirt default pool name changed to 'images' to avoid this same problem on future again.

**Comment by wammz** [comment]
Many thanks for the assistance.

**Comment by boistordu** [comment]
Same problem but not quite:

```
*** Ginger Base: Running capabilities tests ***
System Report Tool ...: True
Loading AptUpdate features.
System Update Tool ...: True
Repo Management Tool .: deb
*** Ginger Base: Capabilities tests completed ***
Failed to import plugin plugins.kimchi.Kimchi, error: Class plugins.kimchi.Kimchi can not be imported, error: cannot import name websocket
[07/Aug/2017:19:14:19] ENGINE Listening for SIGHUP.
```

any idea?

**Comment by alinefm** [comment]
Closing this issue as everything was resolved.
