### ISSUE TITLE
Change template default for disk cache mode

### ISSUE THREAD

**Issue by knozzle** [kimchi-project/kimchi#1107]
When creating a new VM from a default template, the VM is unable to start due to the cache mode set to 'none'. 

`KCHVM0019E: Unable to start virtual machine vm-test-01. Details: internal error: process exited while connecting to monitor: 2017-02-14T00:10:01.846252Z qemu-system-x86_64: -drive file=/var/lib/libvirt/images/7540773b-1ebb-4165-bd6d-293205980340-0.img,format=qcow2,if=none,id=drive-virtio-disk0,cache=none: file system may not support O_DIRECT 2017-02-14T00:10:01.846394Z qemu-system-x86_64: -drive file=/var/lib/libvirt/images/7540773b-1ebb-4165-bd6d-293205980340-0.img,format=qcow2,if=none,id=drive-virtio-disk0,cache=none: Could not open '/var/lib/libvirt/images/7540773b-1ebb-4165-bd6d-293205980340-0.img': Invalid argument`

I am able to get the VM to start if I modify the VM directly and set the cache mode to 'Hypervisor default' when editing the VM from virsh or libvirt-manager. Is there a way to set this as the default in the Kimchi config? I checked /etc/kimchi/template.conf, but it seems that there isn't an option for that. 

Edit: I found out why cache='none' isn't working for my setup. ZFS does not support direct I/O [as tracked on this bug ticket.](https://bugs.launchpad.net/nova/+bug/959637/comments/15)

**Comment by ET-Bent** [comment]
Related to #1091.

**Comment by alinefm** [comment]
Hi @knozzle @ET-Bent 

Thanks for reporting this problem!
We are already discussing in the community a way to allow user set the cache mode, IO mode and disk driver.

But Kimchi should not assume a cache mode value  which may not work for every disk file (breaking a guest setup).
(For example, I found some GlusterFS files can not work with cache=none too).
Said that, in parallel, I will work in a patch to check the disk file accepts Direct IO and if not, let the libvirt sets the default cache mode.

**Comment by alinefm** [comment]
FYI, cache=none is set by default on Kimchi to allow live migration.
