### ISSUE TITLE
Save Button not sending

### ISSUE THREAD

**Issue by fritz-net** [kimchi-project/kimchi#1111]
I use the current git versions which I installed over existing packages. When I try to change bootorder the new order is displayed in the console log but when i press save nothing happens (in the network tab only notification is loaded nothing else).

Which data should i append to help solving the issue? or where should i look if i'd like to try solving it myself?

**Comment by fritz-net** [comment]
I tried do make my installation clean from git (has not worked out perfectly). However i fixed the problem for me in https://github.com/fritz-net/kimchi/commit/b431852a96cd466eb2a47c7033aed3e180998e5c

![image](https://cloud.githubusercontent.com/assets/2499282/23339194/3e089cde-fc1d-11e6-9abb-d9c9f46aba15.png)

**Comment by alinefm** [comment]
Hi @fritz-net 

Thanks for reporting and providing a patch.
I got your patch from https://github.com/fritz-net/kimchi/commit/b431852a96cd466eb2a47c7033aed3e180998e5c.patch and have already applied it upstream.

Commit 5c80d731eec41c65f6d241a7898c832f1629b263

Please, next time you can follow the instructions at https://github.com/kimchi-project/kimchi/wiki/How-to-Contribute to submit a patch for review e etc.
Kimchi community does not work based on pull requests.
