### ISSUE TITLE
Kimchi-poject Dependencies

### ISSUE THREAD

**Issue by tunkaflux** [kimchi-project/kimchi#1114]
Hello,

Simple question really, is there a need for "texlive-fonts-extra"? On Ubuntu, this pulls in almost all X11 components (xterm, etc...) and I would like to avoid that.

**Comment by abittner** [comment]
Hello,
+1 for that one. I installed it yesterday on a fresh Ubuntu Xenial x64 and it started to pull in 2.6 GiB of packages. This kind of "shocked" me :-)

**Comment by alinefm** [comment]
Hi @tunkaflux @abittner 

We have plans to make it optional. But today it is required due internal configuration. You will need to hack the code to workaround that if you want.

**Comment by JoseGoncalves** [comment]
Commit 68c906a removed the "texlive-fonts-extra" dependency, at least in Debian 8.7 where I've tested.

**Comment by gamvrosi** [comment]
@alinefm would it be possible to package releases (for all of kimchi, wok, etc) with these commits? I am currently facing some issues with a server installation because of these dependencies.
