### ISSUE TITLE
Error to create bridge interface

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/kimchi#1119]
Even when I disable NetworkManager, I still can't create a bridge interface.

<img width="694" alt="screen shot 2017-03-17 at 16 57 15" src="https://cloud.githubusercontent.com/assets/6681745/24060617/d57c452e-0b32-11e7-9a65-836e5737082f.png">

**Comment by alinefm** [comment]
Fixed by 8280b226b30d86b26f03d2588cac6615f8869ff6
