### ISSUE TITLE
Debian packaging missing dependencies

### ISSUE THREAD

**Issue by JoseGoncalves** [kimchi-project/kimchi#1125]
When making a Debian package for kimchi 2.4.0 with "make deb", the resulting package has the following information:

```
$ dpkg -I kimchi-2.4.0-0.noarch.deb 
 new debian package, version 2.0.
 size 568658 bytes: control archive=7157 bytes.
     792 bytes,    33 lines      control              
     812 bytes,    33 lines      control.in           
   13693 bytes,   456 lines      Makefile             
     784 bytes,    17 lines      Makefile.am          
   13347 bytes,   456 lines      Makefile.in          
 Package: kimchi
 Version: 2.4.0
 Section: base
 Priority: optional
 Architecture: all
 Depends: wok (>= 2.1.0),
          ginger-base,
          python-imaging,
          python-configobj,
          novnc,
          python-jsonschema (>= 1.3.0),
          python-libvirt,
          gettext,
          libvirt-bin,
          nfs-common,
          qemu-kvm,
          python-parted,
          python-psutil (>= 0.6.0),
          python-ethtool,
          sosreport,
          python-ipaddr,
          python-lxml,
          open-iscsi,
          python-guestfs,
          libguestfs-tools,
          spice-html5,
          python-magic,
          python-paramiko
 Build-Depends: xsltproc,
                gettext,
                python-lxml
 Maintainer: Aline Manera <alinefm@br.ibm.com>
 Description: Kimchi web application
```

Because kimchi requires package **ebtables** and **dnsmasq** to be installed in order to work, these packages should be added also as dependencies for the Debian package.

**Comment by alinefm** [comment]
Hi @JoseGoncalves 

Kimchi does not depend on ebtables neither dnsmasq.

**Comment by JoseGoncalves** [comment]
I remember when I installed Kimchi the first time on a Debian 8 machine errors related to not having dnsmasq installed on wok log file and that prevented the Virtualization tab from appearing. The same is discussed at #1100.
Nevertheless, I will try again from scratch again and report back the result.

**Comment by JoseGoncalves** [comment]
OK. I've reinstalled latest Kimchi version from scratch in a Debian 8.7 host and no extra dependencies were needed to install.
It seems that extra dependencies that I've seen in the past on ebtables and dnsmasq do not exist any more.
For the record, here what I've done to install Kimchi:

```
wget http://kimchi-project.github.io/wok/downloads/latest/wok.noarch.deb
wget http://kimchi-project.github.io/gingerbase/downloads/latest/ginger-base.noarch.deb
wget http://kimchi-project.github.io/kimchi/downloads/latest/kimchi.noarch.deb

sudo dpkg -i wok.noarch.deb
# deps error
sudo apt-get -f install
# SSL cert error => Manual install SSL certificate at /etc/wok/
sudo apt-get -f install

sudo dpkg -i ginger-base.noarch.deb
# deps error
sudo apt-get -f install

sudo dpkg -i kimchi.noarch.deb
# deps error
sudo apt-get -f install

sudo systemctl restart wokd
```
The only minor hiccup on the process was that the wok package installation fails due to the SSL certificate not being installed. After I install it manually, all went OK.

**Comment by JoseGoncalves** [comment]
I'm reopening this issue because, after I made a reboot on my host machine, Kimchi was not able to start and I got the following messages at /var/log/wok/wok-error.log:

```
Fatal: Unable to activate network default.
Details: direct firewall backend requested, but /sbin/ebtables is not available: No such file or directory
Failed to import plugin plugins.kimchi.Kimchi, error: Network default does not exist or is not active. Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
```

So, after initial installation all was working fine, but after a reboot on the host machine a check is made for the existence of **/sbin/ebtables** that fails because I don't have **ebtables** installed.

**Comment by JoseGoncalves** [comment]
Some additional info on this issue.
After I change the /etc/kimchi/template.conf file to ensure only valid network interfaces are set on main/networks variable all runs fine.
But, it seems to me, that a default value set on the Kimchi installation should not trigger a check that would require a package (ebtables) that is not a dependency of kimchi.

**Comment by alinefm** [comment]
@JoseGoncalves Kimchi does not depends on ebtables! It seems to be a libvirt dependency or other thing specific to Debian.

**Comment by JoseGoncalves** [comment]
@alinefm Kimchi may not have any direct dependency on ebtables, but what I see on my Debian 8.7 distro is that with the default configuration, after a reboot on the host machine, a test on ebtables is triggered what cause kimchi not being able to start.
Maybe something related with default network interface configuration?
As I told you before, after I changed the /etc/kimchi/template.conf to:
```
[main]
# List of networks separated by comma
# Represents the virtual network interfaces to be assigned to guest
networks = External1,
```
were "External1" is a properly configured network interface, the ebtables check is not triggered and Kimchi starts without problems.

**Comment by alinefm** [comment]
Hi @JoseGoncalves 

Hrm... Try to remove the comma at the end of the virtual network name. Maybe it is assuming an empty string a second network name and it is causing some parsing errors (?).

**Comment by JoseGoncalves** [comment]
Hi @alinefm 

The problem is not related with the comma, because all it's OK if I use "External1" with a comma at the end. This issue only occurs with the default configuration installed in /etc/kimchi/template.conf.

**Comment by chr0mag** [comment]
I can reproduce this in Arch Linux as well. However, _ebtables_ & _dnsmasq_ are actually optional _libvirt_ dependencies and are only required for NAT/DHCP guest networking. (_bridge-utils_, required for bridged networking is also an optional dependency.)

It is certianly possible to setup a functional _libvirt_ without these (eg. using [routed](https://jamielinux.com/docs/libvirt-networking-handbook/routed-network.html) networking w/static IP addresses).
