### ISSUE TITLE
KCHVM0019E-Could not open iso -Permission denied

### ISSUE THREAD

**Issue by MillionSky** [kimchi-project/kimchi#1126]
[enviroment]
CentOS 7.3.1611 minimal
Wok 2.4.0-0
Gingerbase 2.3.0-0
kimichi 2.4.0-0

[action]
start virtual machine

[error message]
KCHVM0019E: Could not start virtual machine ubuntu_server_12.04.5_1. Detail info：internal error: qemu unexpectedly closed the monitor: 2017-04-07T05:47:57.288643Z qemu-kvm: -drive file=/mnt/hgfs/ubuntu-12.04.5-server-i386.iso,format=raw,if=none,id=drive-ide0-1-0,readonly=on: could not open disk image /mnt/hgfs/ubuntu-12.04.5-server-i386.iso: Could not open '/mnt/hgfs/ubuntu-12.04.5-server-i386.iso': Permission denied

**Comment by MillionSky** [comment]
Resolved!
Close the firewall.
`setenforce 0`

But in https://github.com/kimchi-project/wok/wiki/SElinux-troubleshooting, the firewall was not closed.
Dose there any other method to resolve this problem?

**Comment by alinefm** [comment]
Hi @MillionSky 

The error you reported is a libvirt permission error. That means libvirt does not have the right permissions to work with the ISO file.
The instructions on that case, is to move the ISO files under /var/lib/libvirt/images or /var/lib/kimchi/isos as those directories have the right permissions set for libvirt.
Otherwise, consider moving the ISO file ownership to libvirt:libvirt.

**Comment by MillionSky** [comment]
@alinefm 
Thanks very much!
I have try the three methods:
- move the ISO files under /var/lib/libvirt/images
   Verified, it works.
- move the ISO files under /var/lib/kimchi/isos
   Verified, it works.
- moving the ISO file ownership to libvirt:libvirt
   Failed. chown fail: libvirt is invalid user, chgrp works.
  The same error message appears.

**Comment by alinefm** [comment]
@MillionSky I am glad to know it is working now.
About the libvirt user, probably it is not the right value. You will need to search what should it be.
I will close this issue by now. Please, reopen if needed.

**Comment by amit213** [comment]
@alinefm Thank you. Very helpful tip.
