### ISSUE TITLE
How to set "OS Type" info on VMs created before Kimchi installation?

### ISSUE THREAD

**Issue by JoseGoncalves** [kimchi-project/kimchi#1127]
Hi,

Is there any way to be able to show on the "OS Type" column of the Guests tab a proper OS icon and name instead of icon "VM" and name "Unknown" for VMs that were created before Kimchi was installed?

Best regards,
José Gonçalves

**Comment by danielhb** [comment]
I don't know how far can we inspect the installed guest OS in Kimchi level in order to detect it, but this is something to consider.

**Comment by JoseGoncalves** [comment]
Auto-detect the OS would be the ideal solution, but if not possible or too hard to implement, a manual option would be perfectly fine for me.

**Comment by alinefm** [comment]
Kimchi already does that on Template. It works for ISO and image files. So probably, it would be easy to extend that to the Guest level.
I will take a look on how that could work and turn back to you soon.

**Comment by GalenOfTheShadows** [comment]
I'll "+1" this. I would be nice if I could at the least manually set the icons. I have a couple hypervisors I'm testing this out on that have several VMs already existing, and it's kind of annoying to look at "Unknown" all the time. I was able to "rebuild" a CentOS 7 VM using my CentOS base template and muckabout with all the libvirt XML to make it EFI again and configure EFI to boot, etc, etc, but it took over an hour to do by hand.

I'd gladly submit a patch if it weren't for the fact that my mind starts to wander every time I start reading others' code and I end up completely off topic. ;-)
