### ISSUE TITLE
Windows browser support (IE or Edge)

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#1135]
Verify Kimchi/Wok is working as expected on a Windows browser.

**Comment by overcookedTOFU** [comment]
At first glance, Kimchi/Wok 2.4.0 seem to work fine in IE 11.15063.0 and Edge 40.15063.0 (on Windows 10 Pro, version 1703, build 15063.138).  I tried creating, installing and running a new xubuntu 16.04 VM.  Xubuntu installed perfectly using novnc and I was able to adjust the memory for the VM using the Kimchi web interface.

Is there more rigorous testing required?

**Comment by alinefm** [comment]
Hi @overcookedTOFU 

Thanks for testing Kimchi and Wok on IE and Edge. I think those tests you made are enough by now.
Could you continue to do those tests time by time to ensure we don't lack support on those browsers?

Anyway, I think we can close this issue if you don't have any more feedbacks to provide.

**Comment by overcookedTOFU** [comment]
No more feedback to provide from my end.  I'll continue to test from time to time and report issues as I discover them.  Please feel free to close this issue.
