### ISSUE TITLE
Doc bug: Wrong URL for wok

### ISSUE THREAD

**Issue by mtlynch** [kimchi-project/kimchi#1140]
There is a small error in the documentation on two different Kimchi pages:

http://kimchi-project.github.io/kimchi/downloads/
http://kimchi-project.github.io/wok/downloads/

>Then access Wok in your favorite browser https://\<machine-ip\>/8001

Should be:

>Then access Wok in your favorite browser https://\<machine-ip\>**:8001**

(colon instead of slash)

**Comment by danielhb** [comment]
Thanks for reporting it. I'll fix it asap.

**Comment by danielhb** [comment]
Fixed. Thanks!
