### ISSUE TITLE
Template creation errors

### ISSUE THREAD

**Issue by shii1** [kimchi-project/kimchi#1157]
Hello,
I have just installed kimchi to give it another go, but I'm not able to get past template.

When I try to use preconfigured images, I get following error:
KCHVM0005E: Remote ISO image is not supported by this server.
Not sure how to verify it.

When I try to create a template using downloaded iso (debian 8 or 9):
KCHTMPL0020E: Unable to create template due error: KCHIMG0001E: Error probing image OS information: part_list: parted print: /dev/sda: Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes.

Debian GNU/Linux 9 (stretch) SMP Debian 4.9.30-2+deb9u2 
libvirt 3.0.0-4
ii  ginger                               2.4.0
ii  ginger-base                          2.3.0
ii  kimchi                               2.5.0 
ii  wok                                  2.5.0

**Comment by foi** [comment]
same on fedora 26, kimchi 2.5.0, wok 2.5.0

**Comment by Fredrik81** [comment]
I have same error code but a bit different message.
KCHTMPL0020E: Unable to create template due error: KCHIMG0001E: Error probing image OS information: part_list: parted print: /dev/sda: Error: Invalid partition table - recursive partition on /dev/sda.

I just installed wok and kimchi then i removed the default ISO store and added a new ISO store on different drive. So the drive where the ISOs is stored is not sda it's a btrfs raid 1

**Comment by alinefm** [comment]
Hi @shii1 @foi 

I don't have any Debian system to validate it. Debian is not usually tested by Kimchi community.
About the problem on Fedora 26, Kimchi 2.5.0 was validated on Fedora 25. I will try to get a Fedora 26 system to test it and return to you soon.

@Fredrik81 

Which OS are you seeing that?

**Comment by shii1** [comment]
Hi @alinefm 
Too bad, kimchi looked ideal for dev/qa. But it would be good idea to remove debian from the list if its not being tested.
I assumed its supported since its mentioned here:
https://github.com/kimchi-project/wok/#install-dependencies

**Comment by alinefm** [comment]
@shii1 It is an open source community in which people contribute thinking about their preferred OS.
Debian was already focus of some people before but today there is no one working closely on it. Don't you want to be that person? :-)

The file you mentioned is only an installation guide. Unfortunately, it does not mean the project is free of bugs.

If I can reproduce the problem on Ubuntu 17.04 or Fedora 26, I will take a look to fix that.

**Comment by Fredrik81** [comment]
Hello
I use Ubuntu 17.10.
I tested and if I create a json file with URL to the iso under the
configuration directory, than I'm able to create a template.
But if I use the ISO from the data store then I get the error message.

Regards,
Fredrik

tis 25 juli 2017 kl. 20:17 skrev Aline Manera <notifications@github.com>:

**Comment by alinefm** [comment]
Thanks for the information, @Fredrik81 

So you tried to create a Template from a predefined remote ISO (aka, from a URL) and it failed, right?
Just to make sure I will follow the same steps as yours.

**Comment by Fredrik81** [comment]
Hello
No its a local BTRFS raid1 on same server as Kimchi.
ISO datastore is called "ISO" and path is //mnt/Kimchi/ISO

Regards,
Fredrik

tis 25 juli 2017 kl. 20:28 skrev Aline Manera <notifications@github.com>:

**Comment by shii1** [comment]
@alinefm 
Of course I dont expect it to be bug free, no software really is :) 
I would like to help with the issue, but python isnt really my thing. Learning new language would probably take more time I can afford.
If I can help with some debugs tho, I will be glad to do so.

**Comment by alinefm** [comment]
@shii1 Did you get the same problem while using which type of ISO? A remote URL, from local dir pool?

**Comment by shii1** [comment]
@alinefm 
There are 2 different errors. One is from remote url (preconfigured templates which come with kimchi).
Second one is by using my own iso images to create a template. For my own, it will extract the iso into /tmp directory and then fails with KCHIMG0001E.

**Comment by Fredrik81** [comment]
Hello,
Some more details.
Attached is a picture of how my ISO store looks like and if image is uploaded there it will fail.
![image](https://user-images.githubusercontent.com/21292774/28728344-9df473c0-73c8-11e7-9256-0b7f77122bca.png)

But if i create a template under "/etc/kimchi/distros.d" it work. I pasted how the template looks like that i created.
/etc/kimchi/distros.d$ cat rockstor.json
[
    {
        "name": "rockstor-3.9.1",
        "os_distro": "rockstor",
        "os_arch": "x86_64",
        "os_version": "3.9.1",
        "path": "https://netix.dl.sourceforge.net/project/rockstor/Rockstor-3.9.1.iso"
    }
]

**Comment by tjgruber** [comment]
Same issue for me, but on both Fedora 25 and Fedora 26.

1.  I download an .iso from the Fedora website to my computer.
2.  In Kimchi, I upload the .iso file to the correct place.
3.  I attempt to create a template using the .iso I just uploaded, and I get that error:

> KCHTMPL0020E: Unable to create template due error: KCHIMG0001E: Error probing image OS information: part_list: parted print: /dev/sda: Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes.

What must I do to fix this issue?

I can work around it for now, by using an existing built-in template such as the Fedora 24 one, and then just changing the .iso path before turning on the VM.  But I'd really like to know if there's some commands I can run to fix it.

![image](https://user-images.githubusercontent.com/15575143/28997533-80cc3fbc-7a17-11e7-8d62-4ddad671cde3.png)


![image](https://user-images.githubusercontent.com/15575143/28997525-4b2e8cc0-7a17-11e7-997c-56e6b4ee2fee.png)

**Comment by alinefm** [comment]
Hi all,

I was able to create a Template using a Fedora 26 image. I am still trying to reproduce that, but it works for me.

**Comment by CMeza99** [comment]
I just set up kimchi 2.5.0 and wok 2.5.0 on Fedora 26 and have this same issue. dunno if this helps:
```
# uname --kernel-name --kernel-release --kernel-version
Linux 4.12.9-300.fc26.x86_64 #1 SMP Fri Aug 25 13:09:43 UTC 2017

# parted --list
Model: ATA SAMSUNG SSD SM87 (scsi)
Disk /dev/sda: 512GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End    Size   File system  Name                  Flags
 1      1049kB  211MB  210MB  fat16        EFI System Partition  boot, esp
 2      211MB   735MB  524MB  ext2
 3      735MB   512GB  511GB                                     lvm
```

**Comment by alinefm** [comment]
I could reproduce that now. I am working on a patch to fix that.

**Comment by cjsoftuk** [comment]
I, too, have just hit this on Debian 9.1 (along with the outstanding libvirt-bin situation).  Pleased to see it's being worked on.  If there's anything I can do to help @alinefm - please let me know as I have a client project stalled because of it.

**Comment by Cybso** [comment]
I've applied the patch but the error message remains (tested with a Debian 9 netboot iso)

**Comment by Jugulaire** [comment]
Hello, 
Could you please give us the command to do the fix ? I got the error and i'm unable to correct it...

**Comment by Timi7007** [comment]
Even after deploying the patch it doesn't work. My **LVM** has `sector size (logical/physical): 512B/4096B`, the error I get from Kimchi says
~~~
KCHTMPL0020E: Unable to create template due error: KCHIMG0001E: Error probing image OS information: part_list: parted print: /dev/sda: Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes.
~~~

**Comment by andreas-aeschlimann** [comment]
In case someone else has trouble finding the location of templates.py, here it is (Ubuntu 18):
`/usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/templates.py`

I manually applied the fix from https://github.com/kimchi-project/kimchi/commit/1ec059af4040c50b1a7b9a34253510a46ca09d3b, restarted wokd with `sudo service wokd restart` and then all was good.

**Comment by jocarren** [comment]
> Even after deploying the patch it doesn't work. My **LVM** has `sector size (logical/physical): 512B/4096B`, the error I get from Kimchi says
> 
> ```
> KCHTMPL0020E: Unable to create template due error: KCHIMG0001E: Error probing image OS information: part_list: parted print: /dev/sda: Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes.
> ```
> 
> **EDIT**: I'm now using a [workaround](https://gist.github.com/Timi7007/890dfd690aeae285212286d91e42a50b):
> 
> ```
> cd /etc/kimchi/distros.d && sudo mv ubuntu.json ubuntu_backup.json && sudo wget https://gist.githubusercontent.com/Timi7007/890dfd690aeae285212286d91e42a50b/raw/ubuntu.json && sudo service wokd restart && cd -
> ```
> 
> This adds a Ubuntu Server 18.04.1 image from the download-server. That way a template can be created and I can setup VMs.

Tried it, it doesn't appear on the list.

Running ubuntu server 18.04

**Comment by thecrypt0hunter** [comment]
Run this to update template.py
'sudo wget -q https://raw.githubusercontent.com/kimchi-project/kimchi/1ec059af4040c50b1a7b9a34253510a46ca09d3b/model/templates.py -O /usr/lib/python2.7/dist-packages/wok/plugins/kimchi/model/templates.py'
