### ISSUE TITLE
Web console (livetile) not working

### ISSUE THREAD

**Issue by tjgruber** [kimchi-project/kimchi#1158]
All seems well in Kimchi.  I can create templates and VMs without issue and run them.

In the "Guests" tab, it lists my running virtual machines:

![image](https://user-images.githubusercontent.com/15575143/28421565-6979fa2a-6d1a-11e7-9316-0299435bf079.png)

When I click on the "Livetile" pic or "Connect" to a VM, it opens up a new window, and times out.  It says the following:

![image](https://user-images.githubusercontent.com/15575143/28422133-039c483c-6d1c-11e7-9b74-94ee8342eb3c.png)

I get the same result no matter I run Fedora 25 or Fedora 26.

I'm not sure what else I can do.

Here is my basic install process:

== Install Kimchi ==

1. dnf instal kimchi
2. Open ports:
	firewall-cmd --add-port=8000/tcp --permanent
	firewall-cmd --add-port=8001/tcp --permanent
	firewall-cmd --add-port=64667/tcp --permanent
	firewall-cmd --reload
	semanage permissive -a httpd_t
2. systemctl enable kimchid
6. nano /etc/libvirt/qemu.conf
	Uncomment user/group root
3. reboot now

---------------------------

**Comment by alinefm** [comment]
Hi @tjgruber 

You are running a really one version of Kimchi. It may be Kimchi < 2.0. We are now on Kimchi 2.5
Please, update your Kimchi and check if everything is working fine on the latest release available.

**Comment by tjgruber** [comment]
Wow, yes... you are correct.  It's Kimchi Version: 1.5.1-0.

I did not suspect that using dnf install kimchi would give me such an old version...?  Why?

I will see what I need to do to upgrade, and try again.  Then report my results here.

**Comment by tjgruber** [comment]
There's no upgrade path.  So I had to do a "dnf install wok.rpm".  Then I could do a "dnf upgrade kimchi.rpm".

Well this completely broke everything.

I ended up doing a clean install of WOK first, then installing Kimchi.

But now I'm forced to install a GUI (and all the crap it comes with) on my server! (this is not acceptable)... so that I can use a web browser to browse to localhost.

I wish there were step by step instructions... from no WOK or Kimchi installed, to fully functional on Fedora 25 or Fedora 26.  I've tried all the trickery messing with all the configs to get it browseable remotely... that ends up breaking everything too.  The whole point of this is to access it remotely.  It's a shame setting it up for that isn't reasonably doable.

What exactly must I do so I can go to https://ip:8001 to access Kimchi remotely?

**If I cannot access WOK/Kimchi remotely, is there a way to get the web console working in version 1.5.1-0?

**Comment by tjgruber** [comment]
Hmm, I didn't do anything and now I can access it remotely.

What happened?

**Comment by tjgruber** [comment]
This is what I am left with now.  A non-functional web console, that never shows the full screen.

![image](https://user-images.githubusercontent.com/15575143/28431088-c8d13138-6d37-11e7-814a-6f5c015ad11d.png)

**Comment by alinefm** [comment]
Fedora repository does not have the latest packages. But you can found them at http://kimchi-project.github.io/kimchi/downloads/ and follow the step bu step to install it.

Related to the console problem you reported, I'd ask you to confirm the problem exists in the latest version (2.5.0) because I don't think it's worth to debug a too old version right now.

**Comment by tjgruber** [comment]
After redoing some things, the Spice web-console seems fine now.

But the VNC web-console does not work, and I can't find any information on getting it to work, as your step by step instructions do not include anything relating to this:

![image](https://user-images.githubusercontent.com/15575143/28436692-b62300e2-6d4c-11e7-807f-0e7a9d9f3a88.png)

**Comment by alinefm** [comment]
The VNC problem is the same as reported at #1165.

I will close this issue and keep tracking on 1165
