### ISSUE TITLE
no virtualization tab - kimchi not starting up 

### ISSUE THREAD

**Issue by boistordu** [kimchi-project/kimchi#1160]
```
*** Ginger Base: Running capabilities tests ***
System Report Tool ...: True
Loading AptUpdate features.
System Update Tool ...: True
Repo Management Tool .: deb
*** Ginger Base: Capabilities tests completed ***
Failed to import plugin plugins.kimchi.Kimchi, error: Class plugins.kimchi.Kimchi can not be imported, error: cannot import name websocket
[07/Aug/2017:19:14:19] ENGINE Listening for SIGHUP.
```
environement ubuntu 16.04.3
any idea?

**Comment by alinefm** [comment]
Hi @boistordu 

Which version of Wok and Kimchi are you using?
Seems there are not in sync and Kimchi is requiring a python module on Wok which does no exist.

**Comment by boistordu** [comment]
mmmmh yeah I ve just downloaded kimchi today and upgrade it. so maybe it'w ok, i'm goign to check

**Comment by boistordu** [comment]
@alinefm no same problem .
So let's take a beat here. 
I've clone wok in /root 
done the autogen -> make -> make install 
normally it should have updated my version right? because I've the 2.3.1 version . I'm not launching by python src/wokd since then I won't have the kimichi plugin loaded either (I've tried) and I won't have the comfort to be able to use ysstemctl and to have the /var/log/wok/wok-*.log 

So what should I do?

**Comment by boistordu** [comment]
But indeed if I launch it with python then I would have the 2.5.0 but it doesn't resolve my problem

**Comment by boistordu** [comment]
So apparently I've installed wok from the packaging in ubuntu before. 
So how to do this? because with your small readme i can't do it. kimchi doesn't incorporate by itself into wok when I install the deb package obviously. + it means that if I would like to wok run as a service I would need to put all the files at the good place + do the systemd files myself.

**Comment by boistordu** [comment]
@alinefm okey my bad, it seems that my first autogen --system didn't go through the first time so it didn't install the new version. notw it has. 
thanks for remind it to me.

**Comment by alinefm** [comment]
@boistordu Glad to know it is working now. :-)
