### ISSUE TITLE
kimchi ssl

### ISSUE THREAD

**Issue by shadowmm** [kimchi-project/kimchi#1177]
nginx: [emerg] BIO_new_file("/etc/kimchi/kimchi-cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/kimchi/kimchi-cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by alinefm** [comment]
Hi @shadowmm 

Could you give a better description on what problem you are having?

**Comment by shadowmm** [comment]
Nevermind I fixed that problem. But now i have a new problem. Everytime i start kimchi the wok virtualization tab doesnt show up in the webpanel. It says default network already exists

**Comment by shadowmm** [comment]
Loading AptUpdate features.
Loading AptUpdate features.
Fatal: Unable to activate network default.
Fatal: Unable to activate network default.
Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
Details: error creating bridge interface virbr0: File exists
Details: error creating bridge interface virbr0: File exists
Loading AptUpdate features.
Loading AptUpdate features.
Fatal: Unable to find network default.
Fatal: Unable to find network default.
Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
Details: Network not found: no network with matching name 'default'
Details: Network not found: no network with matching name 'default'

**Comment by shadowmm** [comment]
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# Bridge between eth0 and eth1
auto virbr0
iface virbr0 inet dhcp
   bridge_ports enp0s25
   bridge_stp off
   bridge_fd 0
   bridge_maxwait 0

/etc/network/interfaces

**Comment by shadowmm** [comment]
You can close this thread. I solved the problem. I had some configuration erros
