### ISSUE TITLE
fresh install ssl protocol error

### ISSUE THREAD

**Issue by alazare619** [kimchi-project/kimchi#1190]
fresh install on centos 7, when trying to go to https://ip:8001 i get ssl protocol error...when going via http it redirects properly however. that being said i have to navigate via the port as other apps reside on http.

**Comment by LNFWebsite** [comment]
This is normal. Kimchi uses a self-signed SSL certificate by default. In a production environment you may want to consider using [Let's Encrypt](https://letsencrypt.org/) or buy certificates from a company such as Digicert or GoDaddy.

**Comment by alazare619** [comment]
this is not a self signed cert error. This was a ssl protocol error. They are diffrent. ssl protocol error means it attempted to initiate an ssl connection but failed. I can not test this further as I moved away from KVM.

**Comment by LNFWebsite** [comment]
I believe some browsers report an invalid certificate as a 'protocol error' as you said.
