### ISSUE TITLE
Active Development?

### ISSUE THREAD

**Issue by warllo54** [kimchi-project/kimchi#1207]
I noticed it's been awhile since a new version was released. I was wondering if this project is still active and if new features will be added?

**Comment by LNFWebsite** [comment]
ditto.

**Comment by saulhuerta** [comment]
Well, there are people active and trying to help to others.

I think the project is alive.

Regards

**Comment by eBeagle** [comment]
Unfortunately there has been no new version for over 1 year. The last version 2.5 was released in April 2017.

I believe most of the active developers in this project were from IBM and they probably have other priorities. It's a shame. It's a great project with a lot of potential.

At the moment I'm testing XCP-ng as an alternative to Kimchi/KVM. It's in active development and seems more mature than Kimchi.

**Comment by marclaporte** [comment]
The WikiSuite project is actively using: http://wikisuite.org/Kimchi

How to install: http://wikisuite.org/How-to-install-Kimchi-on-ClearOS

Our source: http://wikisuite.org/Source-Code#Kimchi

We have one pull request here:
https://github.com/kimchi-project/kimchi/pull/1257

And work started on Bootstrap 4:
https://github.com/kimchi-project/kimchi/issues/1255

Here are our development priorities:
http://wikisuite.org/Kimchi-and-KVM-development

We upstream everything: http://wikisuite.org/FAQ#Is_WikiSuite_just_a_list_of_software_

If you'd like to get involved in Kimchi, please contact me (my email is easy to find)

Marc

**Comment by alinefm** [comment]
Hello everyone!

I know there has been a long time without a new Kimchi release. That happened because IBM stopped sponsoring Kimchi at the beginning of 2017 and after that, I started a new job and moved to a new country. I needed some time to reorganize myself and get proper attention back to Kimchi. Sorry about that.

But, I will do all I can to keep the project and the community alive. I've just accepted some PRs (and others need to be rebased in order to get accepted) and I am working on make Wok and Kimchi python3 compatible and allow Kimchi to connect to a external libvirt URL rather than the one in which Kimchi is installed. These will be the main features of next Kimchi release.

**Comment by saulhuerta** [comment]
Thanks Aline!



Regards

**Comment by eBeagle** [comment]
Hi Aline,

That's great news! Welcome back. Hope you are settle on your new life.

I hope once you kick start the development process we can get more people involved in the project whatever way they can.

> Hello everyone!
> 
> I know there has been a long time without a new Kimchi release. That happened because IBM stopped sponsoring Kimchi at the beginning of 2017 and after that, I started a new job and moved to a new country. I needed some time to reorganize myself and get proper attention back to Kimchi. Sorry about that.
> 
> But, I will do all I can to keep the project and the community alive. I've just accepted some PRs (and others need to be rebased in order to get accepted) and I am working on make Wok and Kimchi python3 compatible and allow Kimchi to connect to a external libvirt URL rather than the one in which Kimchi is installed. These will be the main features of next Kimchi release.

**Comment by Alterjero** [comment]
hi everybody
someone have news since april ?

**Comment by eBeagle** [comment]
Please see comment from @alinefm  at https://github.com/kimchi-project/kimchi/issues/1278#issuecomment-548400178

**Comment by Alterjero** [comment]
thanks @eBeagle

**Comment by alinefm** [comment]
New Wok and Kimchi releases are out!

Join Slack if you want too: https://bit.ly/2MZpqNw
