### ISSUE TITLE
Wrong tab into Storage section

### ISSUE THREAD

**Issue by kerub19** [kimchi-project/kimchi#1215]
Hi,
Using firefox 58.0.2 and chrome 64.0.3282.119, into the Storage, table view, section the tab are wrong; switching into "view gallery", the tab are better
![1](https://user-images.githubusercontent.com/36406695/36146354-a86aabec-10b4-11e8-88ff-92d710017376.JPG)
![2](https://user-images.githubusercontent.com/36406695/36146356-a887420c-10b4-11e8-942b-2f239b4de35e.JPG)

**Comment by shiftycow** [comment]
Can confirm. Using Wok 2.5 and Kimchi 2.5.0 on Centos 7
![image](https://user-images.githubusercontent.com/237453/36286030-1ba3a624-126b-11e8-8ac3-b56de6343332.png)

**Comment by kerub19** [comment]
Yes, I'm using Wok 2.5 on Centos 7.3

**Comment by alinefm** [comment]
I will take a look on it
