### ISSUE TITLE
kvmusertest.py: hardcoded path prevents kimchi module from loading when /usr/local prefixes /var

### ISSUE THREAD

**Issue by ut3** [kimchi-project/kimchi#1224]
https://github.com/kimchi-project/kimchi/blob/40de989457a967d1bcab37b1df2e2e439e32a7db/kvmusertests.py#L64

`filename = '/var/run/libvirt/qemu/%s.pid' % KVMUSERTEST_VM_NAME`

On my system, the correct path is: 
 ` filename = '/usr/local/var/run/libvirt/qemu/%s.pid' % KVMUSERTEST_VM_NAME`

**Comment by alinefm** [comment]
Fix merged.
