### ISSUE TITLE
Dialog "Edit Guest --> Storage --> Add" labels size as GB but is actually KB

### ISSUE THREAD

**Issue by ut3** [kimchi-project/kimchi#1228]
![wok-kb-gb](https://user-images.githubusercontent.com/9812150/39376130-777e44f0-4a05-11e8-8412-6670e8e23786.jpg)

The above field is labeled as "GB" but inspection with libvirt's _virsh_ indicates that the field is actually KiB. 

For a disk created with "20" entered in the above dialog, I get this output from _virsh_
```
virsh vol-info --pool default /usr/local/var/lib/libvirt/images/1524848902206.img
Name:           1524848902206.img
Type:           file
Capacity:       20.00 KiB
Allocation:     324.00 KiB
```

**Comment by navsau** [comment]
Bug in Wok 2.5.0.0

**Comment by jocarren** [comment]
I'm having this exact same issue.
