### ISSUE TITLE
Can't add Disk to Template

### ISSUE THREAD

**Issue by FastFelix771** [kimchi-project/kimchi#1230]
Hi, im using Kimchi 2.5.0 on Ubuntu 16.04.4 LTS - fresh install.

I've added an Ubuntu 18.04 ISO to my iso storage - it detected it perfectly.
If i want to create a template, it actually creates it, but editing it is impossible because it contains no disks - and pressing the "Add Storage" button does nothing.

I'll append some error messages / logs i find, asap.

**Comment by alinefm** [comment]
I added some documentation about it in here: https://github.com/kimchi-project/kimchi/wiki/Troubleshooting

Sorry for the delay on replying back.
