### ISSUE TITLE
Will there be a patch rollup / New official release (AKA 2.5.1 or similar)?

### ISSUE THREAD

**Issue by Modusmundi** [kimchi-project/kimchi#1244]
Hey there,

While I don't really mind diving into the issues section of a given project and patching code on my own system, it is always nice to have something that represents the current state of the code out there so you don't have to deal with drift.

That said, is there any push towards a new deb/rpm/snap/appimage/flatpak/whatever the cool kids are using these days to come out with the reprentative changes that have occurred over the past ~10 months?

**Comment by jaydrogers** [comment]
How do you even apply patches? I just did a fresh install today but ran into this issue (https://github.com/kimchi-project/kimchi/pull/1172#issuecomment-406833749) which prevents noVNC from being used (making it very difficult to install new machines).

I installed from the `.deb` file. Is it possible to apply patches or do I need to install from source all of the time?

**Comment by Modusmundi** [comment]
So if it's  an issue in the python, you can just take the fixed code and throw it into the file that needs fixing.

If it's not, well, usually it's more involved than that.

**Comment by alinefm** [comment]
New release available: https://github.com/kimchi-project/kimchi/releases/tag/3.0.0

Some more context about it: https://github.com/kimchi-project/kimchi/issues/1278
