### ISSUE TITLE
After installing KIMCHI on Ubuntu 18.4, only "Wok" tab is visible! 

### ISSUE THREAD

**Issue by kuntalbasu** [kimchi-project/kimchi#1246]
After installing KIMCHI on Ubuntu 18.4, only "Wok" tab is visible! 
Host and Virtualization tab is missing.

![image](https://user-images.githubusercontent.com/34010710/44062904-f8183bae-9f7b-11e8-86bb-f9e9f639e49d.png)

**Comment by PMaynard** [comment]
Check if Kimchi is enabled.

**Comment by kuntalbasu** [comment]
I followed following article to re-install KIMCHI;
http://www.ubuntuboss.com/ubuntu-server-16-04-as-a-hypervisor-using-kvm-and-kimchi-for-vm-management/

Now, I can see the host tab. But virtualization tab is still missing!!

Screenshot from 2018-08-24 21-17-00

**Comment by kuntalbasu** [comment]
I am getting following error;

```
$ sudo dpkg -i kimchi-2.5.0-0.noarch.deb
Selecting previously unselected package kimchi.
(Reading database ... 177840 files and directories currently installed.)
Preparing to unpack kimchi-2.5.0-0.noarch.deb ...
Unpacking kimchi (2.5.0) ...
dpkg: dependency problems prevent configuration of kimchi:
 kimchi depends on python-imaging; however:
  Package python-imaging is not installed.

dpkg: error processing package kimchi (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 kimchi
```
Please help ..

**Comment by yxmline** [comment]
ar x kimchi-2.5.0-0.noarch.deb
tar -zxvf control.tar.gz
sed -i 's/python-imaging/python-pil/g' control
tar c Makefile Makefile.am Makefile.in control control.in | gzip -c > control.tar.gz
ar rcs kimchi-2.5.0-0.noarch_patched.deb debian-binary control.tar.gz data.tar.xz
https://github.com/kimchi-project/kimchi/issues/1242

**Comment by alinefm** [comment]
Thank you for reporting this problem.

The fix for it is already in master branch and will be in the next official release.
