### ISSUE TITLE
Creating internal snapshots of virtual machines has been deprecated on RHEL 7.6

### ISSUE THREAD

**Issue by eBeagle** [kimchi-project/kimchi#1259]
I believe Kimchi currently only takes internal snapshots and I'm assuming this feature will stop working on RHEL 7.6 and CentOS 7.6 as well once it is released. 

[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.6_release_notes/chap-red_hat_enterprise_linux-7.6_release_notes-deprecated_functionality](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.6_release_notes/chap-red_hat_enterprise_linux-7.6_release_notes-deprecated_functionality)

> ### Creating internal snapshots of virtual machines has been deprecated
>
> Due to their lack of optimization and stability, internal virtual machine snapshots are now deprecated. In their stead, external snapshots are recommended for use. For more information, including instructions for creating external snapshots, see the Virtualization Deployment and Admnistration Guide.

**Comment by sming56** [comment]
Unsubscribe me please.
