### ISSUE TITLE
autogen failed on opensuse 12.3

### ISSUE THREAD

**Issue by shaohef** [kimchi-project/kimchi#126]
> ./autogen.sh 
> ./autogen.sh: line 3: aclocal: command not found
> ./autogen.sh: line 4: automake: command not found
> ./autogen.sh: line 5: autoreconf: command not found
> Failed to generate configure script.  Check to make sure autoconf, 
> automake, and other build dependencies are properly installed.

**Comment by jfdnet** [comment]
HI I just installed opensuse 42.1 but there is no automake & autoconf exit in repo
