### ISSUE TITLE
Possible to update wok/kimchi without interruption to VMs?

### ISSUE THREAD

**Issue by genewitch** [kimchi-project/kimchi#1262]
I updated my wok server due to backend kernel updates that messed something up. The old version had reliance on gingerbase, the 2.5.0 didn't. I didn't have any VMs running and all of my VMs were intact. We're going to do this on a production server but we'd like to know if there is potential for service interruption on the VMs.

thank you in advance and feel free to close this issue :-)

**Comment by alinefm** [comment]
Hi @genewitch 

On Wok and Kimchi update, the VMs will keep as they are. Only the Wok and libvirt services will be restarted.
