### ISSUE TITLE
Kimchi / Wok not listening on port 8001

### ISSUE THREAD

**Issue by sammcj** [kimchi-project/kimchi#1270]
- CentOS 7
- Installed with latest 2.5.0 release packages
- No kimchi, wok or libvirt config file changes
- Followed install instructions provided
- Services started and running without error
- `netstat -lnp | grep 8001` shows that nothing is listening on port 8001
- If I SSH with local port forwarding (e.g. `-L 8001:127.0.0.1:8001 -L 8010:127.0.0.1:8010 -L 64667:127.0.0.1:64667`) I can access wok on http://127.0.0.1:8010 (note the port and no HTTPS) but logging in (with the correct password) simply returns me to the login page. (A bit like https://github.com/kimchi-project/kimchi/issues/1232#issuecomment-501956360)

**Comment by alinefm** [comment]
@sammcj could you confirm the fix provided for #1232 fixed your problem?

**Comment by sammcj** [comment]
@alinefm no it didn't fix it.

```
grep service= /usr/lib/python2.7/site-packages/wok/auth.py
    def authenticate(username, password, service="system-auth"):

netstat -lnp | grep 8001
```

Nothing listening on 8001

**Comment by piotr-gbyliczek** [comment]
I have just installed fresh centos 7 on a vm and installed both rpms from 2.5.0 release.

```
yum install https://github.com/kimchi-project/kimchi/releases/download/2.5.0/wok-2.5.0-0.el7.centos.noarch.rpm
yum install https://github.com/kimchi-project/kimchi/releases/download/2.5.0/kimchi-2.5.0-0.el7.centos.noarch.rpm
systemctl daemon-reload
systemctl start wokd
```

Was able to start wokd fine, connect to the VM on port 8001, and log in as user existing in the vm.

**Comment by sammcj** [comment]
Interesting.

Are there any files that aren’t cleaned up by a yum uninstall of the packages?

I’ll try tomorrow and report back.

--
Sam McLeod

**Comment by piotr-gbyliczek** [comment]
Not much left after uninstall : 

```
[root@kimchi-test ~]# locate kimchi
/usr/lib/python2.7/site-packages/sos/plugins/kimchi.py
/usr/lib/python2.7/site-packages/sos/plugins/kimchi.pyc
/usr/lib/python2.7/site-packages/sos/plugins/kimchi.pyo
/usr/share/kimchi
/var/lib/kimchi
/var/lib/kimchi/objectstore
[root@kimchi-test ~]# locate wok
/etc/wok
/etc/systemd/system/wokd.service.d
/etc/wok/dhparams.pem
/etc/wok/plugins.d
/usr/share/wok
/usr/share/wok/plugins
/var/lib/wok
/var/lib/wok/logs
/var/lib/wok/objectstore
/var/lib/wok/user-requests.data
/var/lib/wok/ws-tokens
/var/lib/wok/ws-tokens/woknotifications
```
Not sure about uninstalling from older releases, but I guess installing 2.5.0, uninstalling it, and installing it again should give a working app regardless of the previous configs.

**Comment by ricardo-ml** [comment]
if disabled IPV6 in centos,  you need to delete "listen [::]:80 default_server;" in /etc/nginx/nginx.conf
this problem is system can't run nginx.
