### ISSUE TITLE
Can we get a new release

### ISSUE THREAD

**Issue by Oxymoron290** [kimchi-project/kimchi#1278]
It's been two years since the last release located at https://github.com/kimchi-project/kimchi/releases

Can we get a new one? Some dependencies have changed since 2.5.0

Edit: For anyone who stumbles across this issue, here is more reading material - #1265 & #1207

**Comment by alinefm** [comment]
I am working on this. As we switched to python3 I need to validate it for Ubuntu, Fedora and OpenSUSE.

**Comment by Modusmundi** [comment]
I know this is off topic but hearing Kimchi is getting a new release is probably the best thing I have heard in probably months RE: projects I follow.

I love Kimchi as a management interface for my home test lab- I wish I knew python better so I could help.

**Comment by alinefm** [comment]
I am looking forward for the next release too.

**Comment by W9CR** [comment]
Thanks for the update, I know all to well how much work goes into this.  FYI our project, AllStar Link <https://allstarlink.org> uses this to manage our VMs and provides connectivity for about 3500 active nodes on a given day.

**Comment by alinefm** [comment]
> Thanks for the update, I know all to well how much work goes into this. FYI our project, AllStar Link https://allstarlink.org uses this to manage our VMs and provides connectivity for about 3500 active nodes on a given day.

Wow! I am glad to know about it. Hope we are doing a good job together (Kimchi and AllStart Link) ;-)

**Comment by alinefm** [comment]
Just an update, it is taking longer than I expected due to some personal matters but I am working on it when time permits.

**Comment by Queuecumber** [comment]
@alinefm do you need help? I'm happy to help if you have something for me to do

**Comment by alinefm** [comment]
@Queuecumber could you get the latest code (master branch) and try to build, generate the rpm and install it in a openSUSE LEAP 15.1 or CentOS 8 system? You can do it with nested virtualization if you don't have any system with those OS. 

I finished up on Ubuntu 19.10, some people are testing on Debian and I am going to Fedora 30 right now.

**Comment by alinefm** [comment]
BTW, we have a Slack workspace now, if anyone wants to join: channel #kimchi at http://kimchi-project.slack.com

**Comment by marclaporte** [comment]
3.0 has been released: https://github.com/kimchi-project/kimchi/releases/tag/3.0.0

**Comment by marclaporte** [comment]
@alinefm: I don't see how to join (be added to) the Slack room.

**Comment by alinefm** [comment]
> 3.0 has been released: https://github.com/kimchi-project/kimchi/releases/tag/3.0.0

Not yet!! hehe I am generating the packages to proper create the release tonight

**Comment by alinefm** [comment]
> @alinefm: I don't see how to join (be added to) the Slack room.

what does happen when you click the link? http://kimchi-project.slack.com

It should redirect you to Slack and then you login/create an account and it is all. The channel name is `kimchi`

**Comment by alinefm** [comment]
Yay!! 🎉 Wok and Kimchi 3.0 are released!

https://github.com/kimchi-project/wok/releases/tag/3.0.0
https://github.com/kimchi-project/kimchi/releases/tag/3.0.0

Enjoy it and let me know if you find any problems!

I am still working on a guide on how to install Wok and Kimchi on CentOS as there are some dependencies missing in there.

**Comment by Modusmundi** [comment]
@alinefm I've wrote one for Ubuntu (On the older version), I can probably do one for Cent if you give me a few days.

https://modusmundi.com/2018/03/02/eat-your-kimchi/

**Comment by alinefm** [comment]
@Modusmundi For sure! Take your time! And Thank you!

From what I noticed, we need to manually download novnc and/or spice-html5 and proper install it under /usr/share to have it working with Kimchi as CentOS does not have those packages.

And probably install python3-cheetah and python3-cherrypy via pip too.

**Comment by alinefm** [comment]
For those who wants to join the Slack channel, here is the right link https://bit.ly/2MZpqNw
(Thanks, @marclaporte for confirming it)
