### ISSUE TITLE
Actions on storage tab not working and system with high load

### ISSUE THREAD

**Issue by Fantu** [kimchi-project/kimchi#1281]
Hi, I'm trying kimchi, built from git today and installed on ubuntu 18.04.
When I open storage tab actions on default pools are not working, switching to other tab still show always storage tab content and made host with high load indefinitely.
I not understand what is going, I also tried to set debug logging but wok log show only a "loop of this line":
`Run command: systemctl is-active libvirtd.service`
Any idea of how is happen and how to solve it or at least to better debug?
Thanks for any reply and sorry for my bad english.

**Comment by alinefm** [comment]
Thank you for reporting, @Fantu 

I've just pushed a fix for that.

**Comment by Fantu** [comment]
Thanks for the fix, @alinefm 
I tested it now and I confirm that issue is solved.
