### ISSUE TITLE
Debian packages without Depends (in debian/control)

### ISSUE THREAD

**Issue by Fantu** [kimchi-project/kimchi#1282]
Hi, I build wok and kimchi from git on ubuntu 18.04 and did make deb.
The generated packages don't have deps (field Depends missed in debian/control).

**Comment by alinefm** [comment]
Hey @Fantu 

How did you generate the deb? You need to:

`sudo ./build-all.sh
make deb`

**Comment by Fantu** [comment]
then I think the "Build and Install" part of readme should be updated

**Comment by alinefm** [comment]
`sudo ./build-all.sh` is a utility script in wok that builds wok and all plugins. The README in Kimchi does exactly what `build-all.sh` does but only for Kimchi.

**Comment by Fantu** [comment]
I tried but didn't solved the issue, debian/control of wok package generated contains:
`Package: wok
Version: 2.5.0
Section: base
Priority: optional
Architecture: all
Maintainer: Aline Manera <aline.manera@gmail.com>
Description: Wok - Webserver Originated from Kimchi`

I did a fast search, I saw also control.in that contain @UBUNTU_DEPS@ but with grep in wok there isn't when replace it.
I also tried 2.5.0 on stretch but is not installable "out of the box" even if should have all prerequisite, debian/control should be changed replacing "libvirt-bin," with "libvirt-bin | libvirt-daemon-system," (| is used for alternatives)
can you give me a small hint on where is defined and replaced please?

it would be better to make a complete debian packaging and propose it for uploading to debian (and consequently it will also be taken from all the derivatives) but I don't have enough time now, maybe I'll do it if we use Kimchi in production (at work)

about basic things we needed (for migrate from actual kvm management console) and seems missed from fast 2.5 test I found:
- missed autostart (seems present in latest version from git)
- add iso hotplug (with vm on seems not possible with kimchi)
- add iso from pool (if is possible can you tell me how please? select show me only disk even if vm is off and there is a pool active containing iso), possibility to select vnc or spice of both are present (there is only console button with automatic choice or I'm wrong?)
- full italian translation (I'll can do even if probably not very good)
- add of the workaround to make clean shutdown works near always also with windows vm (is better to see in latest 3-4 years was added a better thing to used, a workaround we use in actual console is to do dom.QemuMonitorCommand(libvirt.VIR_DOMAIN_QEMU_MONITOR_COMMAND_HMP,"mouse_move 100 100") before shutdown api).

thanks for any reply

**Comment by Fantu** [comment]
I did another fast search, I found in configure.ac "UBUNTU_DEPS=./build-aux/ubuntu-pkg-deps", build-aux/ubuntu-pkg-deps have content and seems right but I not understand where is the issue.
I also found generateDepsFiles.py that use dependencies.yaml but I didn't know if is possible change "libvirt-bin" with "libvirt-bin | libvirt-daemon-system" or the correct way for same result (near nothing experience with yaml, low with python)

**Comment by alinefm** [comment]
Hey @Fantu 

I tried to reproduce what you described and I was only able to do so when I ran `build-all.sh` without ` sudo` which failed with a permission error as you can see below:

` 
guest@guest:~/wok/contrib/DEBIAN$ make control
cd ../.. && /bin/bash ./config.status contrib/DEBIAN/control
./config.status: line 513: config.log: Permission denied
Makefile:315: recipe for target 'control' failed
make: *** [control] Error 1
` 

After running it again with ` sudo` it worked fine and control has all the dependencies needed.

**Comment by Fantu** [comment]
Hi, thanks for reply, build of software and its packages should be possible also without root privilege.

**Comment by alinefm** [comment]
AFAIU, it needs sudo because of automake to do file substitution.
