### ISSUE TITLE
configure: error: cannot run /bin/sh build-aux/config.sub

### ISSUE THREAD

**Issue by lkthomas** [kimchi-project/kimchi#1283]
[root@localhost kimchi]# ./autogen.sh --system
configure.ac:54: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:55: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
configure.ac:46: installing 'build-aux/install-sh'
configure.ac:46: installing 'build-aux/missing'
Makefile.am:22: installing 'build-aux/py-compile'
aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
configure.ac:54: error: required file 'build-aux/compile' not found
configure.ac:54:   'automake --add-missing' can install 'compile'
configure.ac:54: error: required file 'build-aux/config.guess' not found
configure.ac:54:   'automake --add-missing' can install 'config.guess'
configure.ac:54: error: required file 'build-aux/config.sub' not found
configure.ac:54:   'automake --add-missing' can install 'config.sub'
autoreconf: automake failed with exit status: 1
configure: loading site script /usr/share/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a Python interpreter with version >= 3.6... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.7
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.7/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib64/python3.7/site-packages
checking for pep8... /usr/bin/pep8
checking for git... /usr/bin/git
checking for rpmlint... /usr/bin/rpmlint
checking python module: unittest... yes
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
configure: error: cannot run /bin/sh build-aux/config.sub

**Comment by alinefm** [comment]
I am glad you figured out how to solve this problem.
