### ISSUE TITLE
Ubuntu installation problems - wokd service not starting. 

### ISSUE THREAD

**Issue by pallebone** [kimchi-project/kimchi#1289]
Tried my best to follow a guide on installing Kimchi but getting stuck starting the wokd service. Would anyone know what to do? Websoxketproxy is installed. 

Output of

sudo systemctl -l status wokd.service

>

● wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/lib/systemd/system/wokd.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/wokd.service.d
           └─kimchi.conf
   Active: failed (Result: exit-code) since Fri 2019-12-13 20:28:41 EST; 17min ago
     Docs: https://github.com/kimchi-project/wok/wiki
  Process: 1122 ExecStart=/usr/bin/wokd (code=exited, status=1/FAILURE)
 Main PID: 1122 (code=exited, status=1/FAILURE)

Dec 13 20:28:40 Shinobi wokd[1122]: Traceback (most recent call last):
Dec 13 20:28:40 Shinobi wokd[1122]:   File "/usr/bin/wokd", line 30, in <module>
Dec 13 20:28:40 Shinobi wokd[1122]:     import wok.server
Dec 13 20:28:40 Shinobi wokd[1122]:   File "/usr/lib/python2.7/dist-packages/wok/server.py", line 28, in <module>
Dec 13 20:28:40 Shinobi wokd[1122]:     from wok import auth, config, websocket
Dec 13 20:28:40 Shinobi wokd[1122]:   File "/usr/lib/python2.7/dist-packages/wok/websocket.py", line 28, in <module>
Dec 13 20:28:40 Shinobi wokd[1122]:     from websockify import WebSocketProxy
Dec 13 20:28:40 Shinobi wokd[1122]: ImportError: No module named websockify
Dec 13 20:28:41 Shinobi systemd[1]: wokd.service: Main process exited, code=exited, status=1/FAILURE
Dec 13 20:28:41 Shinobi systemd[1]: wokd.service: Failed with result 'exit-code'.
~
![BA458909-62F9-49C0-948F-DCDEF45FCC76](https://user-images.githubusercontent.com/11403137/70841621-e680af00-1de9-11ea-99a8-5331f686b9c2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu server 20.04
 - Version 2.5
![5C43D51F-F445-4EA5-A372-2879A0852EE5](https://user-images.githubusercontent.com/11403137/70841635-044e1400-1dea-11ea-9c4c-bb523aec9bd8.png)

**Comment by tacobash** [comment]
I'm having the same issue on Ubuntu Desktop 19.10.

**Comment by Kiln707** [comment]
I had the same issue on Ubuntu 18.10.
I worked around this by running sudo -H pip3 install websockify
Wok is running for me

**Comment by pallebone** [comment]
Unfortunately for me running : sudo -H pip3 install websockify returned the following - Requirement already satisfied: websockify in /usr/lib/python3/dist-packages (0.8.0)
So it is already installed but not able to be detected on 20.04.

P

**Comment by Kiln707** [comment]
I'm sorry, I looked closer at what you posted with your problem and realized i made a mistake. It appears you are using version 2.5 release, which uses python2. The front page readme is updated as 3.0 uses python3.

In your case, try sudo -H pip install websockify

**Comment by pallebone** [comment]
Thank you, I can confirm this resolves the problem.

**Comment by alinefm** [comment]
I will close this issue as it was already solved.

Please, try to update to the latest version ans follow the instructions at https://github.com/kimchi-project/kimchi/releases/tag/3.0.0
