### ISSUE TITLE
what is the file that generate /etc/libvirt/qemu/vm-name.xml ?

### ISSUE THREAD

**Issue by Alterjerof** [kimchi-project/kimchi#1292]
For writing in azerty with my french keyboard, i do
The xml file is located in "/etc/libvirt/qemu/vm-name.xml"
I changed the Line
From:
graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1'
To:
graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='fr'

and restarted libvirt-bin.

But is possible to automate that?
So what is the file that generate /etc/libvirt/qemu/vm-name.xml ? for automate.

thx for help

**Comment by HTPC-Schrauber** [comment]
The files in /etc/libvirt are created by libvirt. You should not edit them directly.
Use "virsh edit vm-name" to edit the VM definition. This way you do not need to restart libvirt-bin.

**Comment by Alterjerof** [comment]
ok I try that.
thx for issue

**Comment by Alterjerof** [comment]
So if i understand, is impossible to automate the add keymap='fr'
Or i don't understand how use virsh edit vm-name in ubuntu.

If your can confirm, thx

**Comment by HTPC-Schrauber** [comment]
virsh edit takes you directly into the editor. So it is impossible to script this.

But you can use 'virsh dumpxml vm-name > vm-name.xml' to get the xml definition into a file. Then change this xml using sed or something. Then use 'virsh define vm-name.xml' to recreate the VM with the changed definition.

**Comment by Alterjerof** [comment]
i try automate with Inotify.

thx for help
