### ISSUE TITLE
Virtualization not showing up on supported CPU

### ISSUE THREAD

**Issue by darzu84** [kimchi-project/kimchi#1294]
Hello,

I installed kimchi on my clearos machine, I can access the wok but the virtualization tab is missing (see screenshoot).

My cpu is virtualization capable  I already cheked this (HPE Microserver gen10) I don't understand how to debug further

`egrep '(vmx|svm)' --color=always /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm perfctr_core perfctr_nb bpext ptsc cpb hw_pstate retpoline_amd ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic vgif overflow_recov
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm perfctr_core perfctr_nb bpext ptsc cpb hw_pstate retpoline_amd ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic vgif overflow_recov
`
here is a screenshot with the interface what I see [https://www.dropbox.com/s/ouxhv5utlifwoa1/kimchi.png?dl=0](url) someone could help please to debug the issue?

thanks

**Comment by alinefm** [comment]
Hey @darzu84 

How did you install wok and kimchi?

Could you run `sudo python3 /bin/wokd --environment=dev` and paste the output? There will be a message "Unable to load plugin KImchi due to...."

**Comment by darzu84** [comment]
Hey @alinefm in had install using `yum install kimchi` , after this I had also installed a beta version on the recomandation from clearos community (I had posted also there my issue)
`yum update *kimchi* --enablerepo=clearos-contribs-testing`

I got the following version

`rpm -qa | grep kimchi
app-kimchi-core-1.1.8-1.v7.noarch
app-kimchi-1.1.8-1.v7.noarch
kimchi-2.5.0-0.v7.noarch`

I tried your suggestion but first I had no python3 installed after installation when I try to run the command I got the following errors:

`
sudo python3 /bin/wokd --environment=dev
Traceback (most recent call last):
  File "/bin/wokd", line 28, in <module>
    from optparse import OptionParser
  File "/usr/lib64/python3.6/optparse.py", line 77, in <module>
    import textwrap
  File "/usr/lib64/python3.6/textwrap.py", line 8, in <module>
    import re
  File "/usr/lib64/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
`

Thanks

**Comment by darzu84** [comment]
i reinstalled now kimchi again and the virtualization tab is showing! 
Could it be that the reason was the python3 missing?

**Comment by alinefm** [comment]
Mostly probably! Kimchi and Wok are now python3.
