### ISSUE TITLE
Cannot connect to guest console via VNC

### ISSUE THREAD

**Issue by pallebone** [kimchi-project/kimchi#1295]
After creating a VM, I it starts but I cannot connect to it to view it. When i click "view console" it attempts to connect to:

https://192.168.3.21:8001/plugins/kimchi/novnc/vnc_auto.html?port=8001&path=/websockify?token=VWJ1bnR1RDE5MDQtdm0tMQ&encrypt=1

However the output of this page is:
Something went wrong, connection is closed

How can I begin to troubleshoot this problem?

OS: Ubuntu 20.04
Browser: Latest Firefox from snap
Version: 2.5

Kind regards
Pete

**Comment by alinefm** [comment]
Hi @pallebone 

Could you provide more details about it? I encourage everyone to open a bug following the Bug template we setup so we have some details on where to start.

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora 31, Ubuntu 19.10]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 2.5, local@<sha>]

**Comment by pallebone** [comment]
Apologies. I have updated OP with this detail.

**Comment by pallebone** [comment]
I see on my other ticket you asked me to update to version 3. Would you prefer I abandon trying to get 2.5 to work and try 3 instead or would you prefer to fix this first then I try upgrade to 3?

P

**Comment by alinefm** [comment]
Thank you for the updates! I think this is already fixed on Kimchi 3.0

Could you try it instead of 2.5?

**Comment by pallebone** [comment]
Hi there,

Thank you, upgrading to 3.0 helped and fixed the issue. Apologies for not using 3.0 right away, the only instructions I found were for 2.5.

Kind regards
Pete

**Comment by Criptos** [comment]
can you list what packages have you installed? 
I have the same issue with 3.0

**Comment by pallebone** [comment]
Hi there,

Apologies, I no longer have the box running this software. Although it did work, it did was not suitable for my particular use case so ended up not using it. I cant tell you what packages were installed as a result, as I no longer have that install.

Kind regards
Peter

**Comment by alinefm** [comment]
Probably fixed by https://github.com/kimchi-project/wok/commit/5761c37d46fb32fdad846d3249c1517cc04e4686

The fix will be available in the next release.
