### ISSUE TITLE
Python ipaddr module is deprecated - switch to built in ipaddress

### ISSUE THREAD

**Issue by NickJH** [kimchi-project/kimchi#1298]
In python3 the ipaddr module appears to be deprecated - https://pypi.org/project/ipaddr/ and https://github.com/google/ipaddr-py. It may be a drop-in replacment just by changing `ipaddr.` to `ipaddress.` in xmlutils/network.py, tests/test_networkxml.py, network.py and model/networks.py, then remove any mention of python3-ipaddr as a dependency.

**Comment by alinefm** [comment]
I am working on it
