### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by Alterjerof** [kimchi-project/kimchi#1308]
i install wok kimchi on my ubuntu 19.10 with a releases (https://github.com/kimchi-project/kimchi/releases/tag/3.0.0)
just with that before:
sudo apt -y update && sudo apt -y upgrade
sudo apt install -y nginx-core (if i don't install that i have error message)
and i have just a wok banner and a blank page (no login page)

i try this the 2 site (https://github.com/kimchi-project/wok/wiki/Troubleshooting) (https://github.com/kimchi-project/kimchi/wiki/Troubleshooting)

but nothing

plz help

**Comment by alinefm** [comment]
hey @Alterjerof ! Could you provide logs or screenshot of browser inspector?

For logs:

    sudo service wokd stop
    sudo python3 /bin/wokd --environment=dev

For screenshot: right click on wok page >> Inspect >> Console (any errors in there?)

**Comment by Alterjerof** [comment]
the issue have change, now i don't have a blank page but a login page & when i try connect i reload in the same page.

logs:
adminubuntu@ubuntu:~$ sudo python3 /bin/wokd --environment=dev
Push server created on address /run/user/0/woknotifications
Plugin configuration file /etc/wok/plugins.d/__pycache__.conf doesn't exist.
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'FEATURETEST_VM'
libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'FEATURETEST_POOL'

*** Kimchi: Running feature tests ***
Service Libvirtd running ...: True
libvirt: Storage Driver error : operation failed: no storage pools were found on host '127.0.0.1'
operation failed: no storage pools were found on host '127.0.0.1'
NFS Target Probe support ...: True
Fibre Channel Host support .: True
Kernel VFIO support ........: True
Network Manager running ....: False
Memory Hotplug support .....: True
*** Kimchi: Feature tests completed ***

Unknown device type: drm
Unknown device type: drm
libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'default'
libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'ISO'
Unknown device type: drm
Unknown device type: drm
Unknown device type: drm
[20/Feb/2020:17:12:34] ENGINE Listening for SIGTERM.
[20/Feb/2020:17:12:34] ENGINE Listening for SIGHUP.
[20/Feb/2020:17:12:34] ENGINE Listening for SIGUSR1.
[20/Feb/2020:17:12:34] ENGINE Bus STARTING
[20/Feb/2020:17:12:34] ENGINE Started monitor thread 'Autoreloader'.
[20/Feb/2020:17:12:34] ENGINE Serving on http://127.0.0.1:8010

*** Kimchi: Running dependable feature tests ***
127.0.0.1 - - [20/Feb/2020:17:12:34] "HEAD /plugins/kimchi/images/icon-fedora.png HTTP/1.1" 200 4449 "" ""
127.0.0.1 - - [20/Feb/2020:17:12:34] "GET /plugins/kimchi/images/icon-fedora.png HTTP/1.1" 206 4449 "" ""
QEMU stream support .......: True
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***

[20/Feb/2020:17:12:34] ENGINE Bus STARTED
[20/Feb/2020:17:13:15] ENGINE Started monitor thread 'Session cleanup'.
188.2.5.57 - - [20/Feb/2020:17:13:15] "POST /login.html HTTP/1.0" 200 22001 "https://188.1.0.220:8001/login.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"


Console:
![image](https://user-images.githubusercontent.com/59047788/74948419-9848e700-53fc-11ea-8904-60aa45c9f631.png)

thx for help

**Comment by Alterjerof** [comment]
Just for be sure.
The login/password is a login of server like kimchi 2.5, or they are a default login/password ?

thx for help

**Comment by Alterjerof** [comment]
Is a proxy problem sorry for this issu. Now is good thx for you time.
