### ISSUE TITLE
No VNC in Centos 8

### ISSUE THREAD

**Issue by Criptos** [kimchi-project/kimchi#1333]
**Describe the bug**
Error Server disconnected (code: 1006) |   at 

**To Reproduce**
1. Go to 'Gusest'
2. Click on 'VNC/Spice'

**Expected behavior**
Enter VNC. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4574233/92804854-3fcc3d80-f37e-11ea-9700-c58fbe723a4c.png)

**Desktop (please complete the following information):**
 - OS: Centos 8 
 - Browser Chrome
 - Version 3.0

**Additional context**

**Comment by alinefm** [comment]
Fixed by https://github.com/kimchi-project/wok/commit/5761c37d46fb32fdad846d3249c1517cc04e4686

It will be available in the next release.
