### ISSUE TITLE
Need pause/resume operation for VMs

### ISSUE THREAD

**Issue by sming56** [kimchi-project/kimchi#152]
When the VM is paused by other tools like virt-manager, Kimchi can display the VM in the list.  However, Kimchi can not manage the paused VM anymore.  "start operation" will cause a "failed to start" error message.  A "pause" and "resume" operation would be added to Kimchi VM's operation to resolve such problems.

**Comment by cd1** [comment]
Commit 82e5658587ad32cf1a06a555732897e2e7f3e523 has added the VM actions "suspend" and "resume". However, the UI still needs to be updated in order to allow the user to trigger those actions.

**Comment by cd1** [comment]
Commit a1ad10e enabled this feature on the UI.
