### ISSUE TITLE
Kimchi should handle libvirt connection failures

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#201]
I have tested Kimchi in my laptop and noticed 2 things:

1- Kimchi daemon does not start if libvirt service is not up
Kimchi daemon/server could start ans warn the users about the problem in the browser.

2- Kimchi is not able to handle libvirt service failures
I stopped  libvirt service and the browser did not give any warning. The screen started to work strangely and freeze without clues.

I now Kimchi is strongly dependent of Libvirt, but I understand that it is a distinguished service and server, so it should handle this kind of failures.

**Comment by pvital** [comment]
RFC submitted to ML
http://lists.ovirt.org/pipermail/kimchi-devel/2016-April/014656.html
