### ISSUE TITLE
disk type in template

### ISSUE THREAD

**Issue by pradeepkumars** [kimchi-project/kimchi#220]
user should have choice to choose disk type option in template

**Comment by alanoe** [comment]
I am very interested in this feature. I and my team often want to use an "incremental" qcow2 disk and we need to run qemu commands manually to do it.

**Comment by Truja** [comment]
I just sent patches to mailing list with the UI support. Waiting for review.
@alinefm you may want to assign this issue to me.

**Comment by Truja** [comment]
UI patch committed upstream: 
commit 7a4bd1b
