### ISSUE TITLE
Ip validation

### ISSUE THREAD

**Issue by pradeepkumars** [kimchi-project/kimchi#285]
IP validation fails if uder provide below  IP for template, nfs pool.

101.10.10.10

It accepts 3 digits also 

Ideal check would be: 

!/^((2[0-4]\d|25[0-5]|[01]?\d\d?)\.){3}(2[0-4]\d|25[0-5]|[01]?\d\d?

If java script provide any other better check for ipv4/ipv6, that would be ever more better.

**Comment by alinefm** [comment]
It is part of #37
