### ISSUE TITLE
Inconsistent button status when adding or creating new resources.

### ISSUE THREAD

**Issue by pvital** [kimchi-project/kimchi#317]
There are some button status inconsistent on add/create pages. For example, when creating a new guest the button "Create" is disabled until the minimum of the required fields are filled. However when creating a new storage pool the button "Create" is enabled by default.

All button status of add/create pages should be consistent - it should be disabled by default until the minimum of the required fields are filled.

**Comment by pvital** [comment]
The behavior reported in this issue still happens in Kimchi 2.0.0 (actually tested with HEAD of git on 2016-01-07) but only in Network tab, after click to add a new network. For all other tabs the 'Create' button is disabled until all required fields are filled.

![screenshot from 2016-01-07 09-04-26](https://cloud.githubusercontent.com/assets/699330/12169140/e4709a92-b51d-11e5-9406-eb329e5eae03.png)

**Comment by sstoppler** [comment]
Patch sent to ML for review.

**Comment by sstoppler** [comment]
Patch applied upstream:  https://github.com/kimchi-project/kimchi/commit/351917d8e642b7eadc94a6eeda20dc337ffb774f

**Comment by pvital** [comment]
Tested and it's working with 351917d.
Closing.
