### ISSUE TITLE
Loosen Debian Control-file dependencies

### ISSUE THREAD

**Issue by mfonville** [kimchi-project/kimchi#328]
Currently Kimchi 'depends' within the debian control file on certain dependencies that are too tight and can break setups.
For example the 'firewalld' dependency can break current server installations by enforcing such an application without the user/administrator being notified about the necessity of setting up specific firewall rules for this new automatically pulled-in application.

I would propose to change such dependencies to 'recommends' for some of the 'utilities' that are not necessary to execute kimchi and a 'suggests' for a package like 'firewalld' that can unintentionally break your system.

**Comment by alinefm** [comment]
Fixed by 5ab71df7622ecd8ac0c6e271b3ce2d4cbc403706
