### ISSUE TITLE
Account for network boot/install leveraging  DHCP/TFTP/(NFS/HTTP/FTP) network installation servers.

### ISSUE THREAD

**Issue by fnovak** [kimchi-project/kimchi#372]
create a guest template without forcing the guest to have a virtual CD-ROM drive connected to an actual distribution ISO file.

In production environments, it would be fairly common to install guests using network installation servers rather than virtual CD-ROM drives.  All common Linux distributions support network installations and document how to set up DHCP/TFTP/(NFS/HTTP/FTP) network installation servers.

It would be very helpful if it were possible to create guests without virtual CD-ROM drives at all.  Post-install, once networking is up, guests can simply access ISO files directly (via loopback mounting).  It's unlikely that a network-installed guest would ever need a virtual CD-ROM drive at all.

**Comment by Truja** [comment]
I have worked with Alan on this.
@alinefm please, assign to me. Thanks

**Comment by Gibby** [comment]
Any updates on this?

**Comment by pvital** [comment]
V1 for backend patch-set submitted to ML

**Comment by pvital** [comment]
Back-end part committed. 
Need UI improvements to be able to create netboot templates.

**Comment by pvital** [comment]
For UI screen, the proposal is add two ratio buttons before the current content, where user can select between the options to create a netboot template and image template. The image template option must be the default option and selected automatically when user access the screen. When user selects the netboot option, the current content must be hidden.

So, in top of current content, we must have:

```
( ) Netboot template 
(*) Image template

File Path: 
[=================]
<same content as displayed today>

[Create] [Cancel]
```

If netboot option is selected, the screen must be like:

```
(*) Netboot template 
( ) Image template

<content here is hidden>

[Create] [Cancel]
```

**Comment by sstoppler** [comment]
Patch sent to ML for review on 6/13.

**Comment by sstoppler** [comment]
Patch applied upstream (v3):  https://github.com/kimchi-project/kimchi/commit/51d69ce84397bb75057320a93447508a396f51a9
