### ISSUE TITLE
Add disk attachment to guest template

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/kimchi#378]
While creating new template in kimchi , it is necessary to have an option which can provide flexibility to add an extra disk/volume to the guest template. Usually extra disk attachment is a useful requirement and user wants to have flexibility to add or remove several other disks to the guest.

**Comment by Truja** [comment]
@alinefm please, assign this to me, I have developed the UI part !

**Comment by Truja** [comment]
This is done, please close
