### ISSUE TITLE
UI: optimize packagesupdate and repository requests

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#381]
Now every time switch back to "Host" tab, UI will resend:
    GET /packagesupdate
    GET /repositories
These two requests are time consuming and possibly results will not change in a long period.
So UI may want to cache the result to boost the response. And correspondingly, the backend will modify the two request response logic to indicate whether previous results are out of date.

**Comment by cd1** [comment]
What do you mean with _"the backend will modify the two request response logic to indicate whether previous results are out of date"_? AFAIK, in order for the backend to tell whether there are packages to be updated, it needs to run the underlying command again (e.g. `yum update`), so it will consume the same amount of time.

I agree with a possible cache done by the UI but I don't understand how the backend can help.

**Comment by alinefm** [comment]
It was moved to Ginger Base https://github.com/kimchi-project/gingerbase/issues/123
