### ISSUE TITLE
create a higher resolution kimchi icon

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#384]
When using Google Chrome, a new window is created (vs a tab) for a console session. Then, when alt+tab'ing to other windows, I can see the kimchi icon instead of the Google icon. This kimchi icon is very blurry, so, I think that creating a bigger image for the icon would give kimchi a prettier icon when switching between windows.

You can also see the icon in the tray on gnome desktop. The icon is smaller so it isn't as blurry. I can screenshot that one, though, so I'll add that image.
![screenshot from 2014-06-24 09 21 08](https://cloud.githubusercontent.com/assets/4493281/3372432/0c1f2c94-fbab-11e3-9467-048fd2400ec1.png)

**Comment by alinefm** [comment]
Fixed by 81b8ee4a
