### ISSUE TITLE
kimchi leaks resources

### ISSUE THREAD

**Issue by usernameisalreadytaken2014** [kimchi-project/kimchi#388]
After spinning up 2 virtual machines and connecting to the VM consoles a couple times:

<pre>
$ ps -ef --forest
root      1632     1  3 Jul16 ?        06:51:14 /usr/bin/python /usr/bin/kimchid
root      1818  1632  0 Jul16 ?        00:00:01  \_ [python] <defunct>
root      4140  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root      5221  1632  0 Jul16 ?        00:00:23  \_ python /usr/lib/python2.7/dist-packages/kimchi/websockify.py 127.0.0.1:646
root     12148  5221  0 Jul16 ?        00:00:01  |   \_ [python] <defunct>
root     14075  5221  0 Jul16 ?        00:00:01  |   \_ [python] <defunct>
root     16601  5221  0 Jul16 ?        00:00:00  |   \_ [python] <defunct>
root     18790  5221  0 Jul16 ?        00:00:00  |   \_ [python] <defunct>
root     18808  5221  0 Jul16 ?        00:00:00  |   \_ [python] <defunct>
root     18887  5221  0 Jul16 ?        00:00:00  |   \_ [python] <defunct>
root     18914  5221  0 Jul16 ?        00:00:00  |   \_ [python] <defunct>
root      6371  1632  0 Jul16 ?        00:00:00  \_ [nginx] <defunct>
root      6460  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root      8641  1632  0 Jul16 ?        00:00:00  \_ [nginx] <defunct>
root      8648  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root      9829  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     10876  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     12258  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     13333  1632  0 Jul16 ?        00:00:00  \_ [nginx] <defunct>
root     13419  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     14715  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     15890  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     17085  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     17902  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     18982  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     20035  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     21850  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     22827  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     24171  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     24974  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     26046  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     27720  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     28545  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     29890  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     30762  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     32196  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root       591  1632  0 Jul16 ?        00:00:00  \_ [nginx] <defunct>
root       698  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root      4049  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     12230  1632  0 Jul16 ?        00:00:00  \_ [nginx] <defunct>
root     12371  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     13550  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     14679  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     16129  1632  0 Jul16 ?        00:00:00  \_ [nginx] <defunct>
root     16303  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     17428  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
root     18273  1632  0 Jul16 ?        00:00:00  \_ [python] <defunct>
</pre>

Lots of zombie processes all parented by kimchid.
Spin up a hundred virtual machines and you're looking at a fork bomb.

**Comment by alinefm** [comment]
Closing it due inactivity.
Please, reopen it with the requested information.

**Comment by usernameisalreadytaken2014** [comment]
Linux 3, but unsure of the minor version since it is on auto-upgrade.

The problem seems to have gone away.

(I removed Nginx and replaced it with Varnish to make it easy to do everything on port 443.  That may be related to why the zombies processes disappeared, not sure..)

Please close, I'll open a new case if it pops up again...
