### ISSUE TITLE
ISO upload via GUI

### ISSUE THREAD

**Issue by usernameisalreadytaken2014** [kimchi-project/kimchi#391]
It would be great if the user could upload an ISO image directly from the Kimchi GUI.

(I have a tightly coded web upload manager I wrote, ~ a hundred lines of code including HTML5 file drop support, progress bars and everything, that I'd like to contribute.  But unfortunately it's in NodeJS, not Python :-/.)

**Comment by cd1** [comment]
Fixed by 8a83cbe669b085af27aae4b6f33cc905f1ae3bf4, 2d4cb230a11d6bd80882d82b50f37b48d0295fb8 and 577d85d53b6301175beae29b4e10de0f1a28ec18.

**Comment by aiminickwong** [comment]
so should change to python？
