### ISSUE TITLE
kimchi should not create random networks and storage locations

### ISSUE THREAD

**Issue by usernameisalreadytaken2014** [kimchi-project/kimchi#392]
After starting Kimchi the first time, there are "default" storage locations and "default" network.

OK, not a big deal, I can remove those either in Kimchi or via virsh or whatever, and create the actual networks I must have in my environment, and point to the actual NFS storage locations that Kimchi should use.

But everytime kimchid restarts, those pesty, annoying "default" things pop up again.  One of them is even a network that gives virtual machines access to resources that they definitely should not have access to, such as VMs for testing malware suddenly having an open link to the Internet.

I hacked the source code of kimchi to just plain and simple remove all the pesky default items that kimchi creates.

Not sure if the patch I've made is agreeable by Kimchi authors though, since it's just "snip-snip-snip" ?

I can post the patch if it sounds reasonable.

Maybe there should be a better place to put default networks and locations.  Like support for specifying the default items in the config file, so that users who DO NOT want the default items can remove them from the config files, people that distribute kimchi can change the config files and adjust the defaults to their distro, etc...

**Comment by imbeta** [comment]
Any update on this? 
My system has custom storage and network configuration, so Kimchi restoring defaults is just a pita. I know I'm too anal about this but It's messing my system and so far it's the only thing stopping me from using Kimchi.
If some one could point me on how to hack the code to disable this, it'd appreciated it :-)!

**Comment by alinefm** [comment]
@imbeta You can comment lines 47-49 on model/model.py and lines 45-46 on model/networks.py

**Comment by imbeta** [comment]
@alinefm Thanks, that made the trick!

**Comment by alinefm** [comment]
Fixed by e1ac63623feec72ce583aee396947f34a344b546 e0a6fb586a464b65f3c22480209eef4665fe2202 b61931d4b29bc1c3eb4c1087b6df70f7bc8d99e5

Now Kimchi has a template config (/etc/kimchi/template.conf) file that handles the default values to create a template.
If you don't want to use the default values used by Kimchi, please update the template.conf file accordingly to your needs.
