### ISSUE TITLE
Guest disk: Allocate storage volume when attaching disk to vm

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#406]
When attaching vm disk, besides specifying an existent volume, we need to give use an option to just specify a storage pool without volume, kimchi can allocate a new volume for vm, specifiying the volume size. This is a useful scenario for extending vm storage.

**Comment by sstoppler** [comment]
Patch applied upstream:
https://github.com/kimchi-project/kimchi/commit/ea99ac451e7cb4247ff9c19447d0c052be45073a
