### ISSUE TITLE
Blank screen when I click on Templates tab

### ISSUE THREAD

**Issue by mopsfelder** [kimchi-project/kimchi#407]
My host system (where kimchi is installed) is behind a firewall that needs authentication in order to have Internet access.  The firewall asks for authentication periodically.

I have configured some remote Fedora templates, as suggested by kimchi web interface, and some local templates using local ISO images I copied to /var/lib/libvirt/images/isos.

When the host has Internet access, everything works just fine.  But when the host has no Internet access and I click on Templates tab, a blank screen is displayed.  Even my local templates are not displayed.

I verified that kimchi has a time out period when reaching remote URL of the templates.

It'd be great if the web interface loaded local templates before the remote ones.  And if displayed a progress bar or a message saying what it's doing behind the blank screen.

**Comment by alanoe** [comment]
I experimented the same issue. It took me some time to figure out that the web UI was stuck because of the firewall.

**Comment by alinefm** [comment]
Fixed by 0d7e872d1db7384bb68f6a3dc8c993a5bf072433
