### ISSUE TITLE
Consider moving to Bootstrap or Foundation soon, or at the next theme revamp

### ISSUE THREAD

**Issue by marclaporte** [kimchi-project/kimchi#410]
Hi!

Every few years, apps typically undergo a revamp of their theme system to take advantage of new technical possibilities and to refresh the look & feel. The Kimchi theme/branding is really nice so there is no rush, but something to consider when the time comes.

Some fantastic new opportunities have emerged in last few years:
http://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)
http://en.wikipedia.org/wiki/Foundation_(framework)

This provides many benefits, one of which is easy access to theme generators and thousands of free and paid themes. But also "mobile-first" design and intensive testing with all browsers, etc. Many PHP apps have moved to Bootstrap, like Joomla!, Moodle, phpMyFAQ, Tiki Wiki CMS Groupware, etc. ClearOS is moving to Bootstrap in version 7.

And it's not just PHP apps. Syncthing & WebVirtMgr also use Bootstrap.
https://github.com/syncthing/syncthing/tree/master/gui/bootstrap
https://github.com/retspen/webvirtmgr/blob/master/templates/base.html

The two main options are:
http://www.google.com/search?q=Bootstrap+vs+Foundation

Both are excellent. Bootstrap has more mind share:
http://trends.builtwith.com/docinfo/Twitter-Bootstrap
http://trends.builtwith.com/docinfo/Foundation

Here are two great resources for FLOSS code & designs:
http://bootswatch.com/
http://bootsnipp.com/

Best regards,

M ;-)

**Comment by la0wei** [comment]
agreed

**Comment by alinefm** [comment]
Kimchi and Wok 2.0 has a new UI design which makes use of Bootstrap.
