### ISSUE TITLE
"test_delete_running_vm" fails on Fedora 20

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#450]
The test function `test_delete_running_vm` is failing.

I'm running Fedora 20 on an extracted tarball from commit 1ab51bf.

## How to reproduce ##

1. Extract the tarball to any directory.
2. Install Kimchi's requirement packages.
3. Run `./autogen.sh` from the repository working directory.
4. Run `sudo make check`.

## Expected behaviour ##

After step (4), a report should be displayed indicating that the tests were successful, including `test_delete_running_vm`.

## Actual behaviour ##

After step (4), a report is displayed indicating that `test_delete_running_vm` has failed.

Below is the test function summary:

>  ======================================================================
>  ERROR: test_delete_running_vm (test_model.ModelTests)
> \----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/vianac/kimchi-master/tests/test_model.py", line 1106, in test_delete_running_vm
>     inst.vm_start(u'kīмсhī-∨м')
>   File "/home/vianac/kimchi-master/src/kimchi/model/vms.py", line 510, in start
>     {'name': name, 'err': e.get_error_message()})
> OperationFailed: KCHVM0019E: Unable to start virtual machine k\u012b\u043c\u0441h\u012b-\u2228\u043c. Details: Invalid argument

**Comment by clnperez** [comment]
There's a RH bug for this: https://bugzilla.redhat.com/show_bug.cgi?id=1062943
Sheldon opened it a year ago. We should try to pursue it there. In the meantime, I can look into removing non-ascii characters from our tests, and put a test for non-ascii characters in that we know will fail to remind us about this.

**Comment by cd1** [comment]
that will work for the testcase (which is what this issue is about), but a Kimchi user won't still be able to start a VM containing non-unicode characters. and as this looks like a libvirt bug, there's nothing we can do here for that case...

**Comment by cd1** [comment]
[Cole Robinson suggested](https://bugzilla.redhat.com/show_bug.cgi?id=1062943#c9) to use the XML tag `<title>` to store the Unicode name of the VM, while keeping the ASCII name on `<name>`. That way, Fedora (and other distros) would be able to start VMs with "Unicode names".

We could give that a try.

**Comment by ramonmedeiros** [comment]
I'll take a look

**Comment by ramonmedeiros** [comment]
Hi,

as we debugged today, we have two problems:

1) The problem of the bug: libvirt cannot use special characters on name (on Fedora >19)

2) Some libraries and protocols cannot handle unicode. Like, if you add a VM called "café" on fedora 19, and try to start vnc, it will crash due an error on base64 library.

To use the solution proposed by RH, we will need to change kimchi to no handle name, but id instead.

**Comment by ramonmedeiros** [comment]
I proposed a solution at the maillist[1]. Basycally, i will create VMs with name and title tags. The name will store a string without special characters, and title will store the correct name. 

Source: http://lists.ovirt.org/pipermail/kimchi-devel/2015-April/010379.html
