### ISSUE TITLE
Firewall ports are not open after firewall restart

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#456]
After installing Kimchi via an RPM file, the firewall ports are correctly open; but after restarting the firewall service, the ports are not open anymore. Therefore, after a system reboot (which also restarts the firewall service), the app cannot be accessed from outside the server.

I'm running Fedora 20, Kimchi installed by an RPM generated on commit 1ab51bf.

## How to reproduce ##

1. Install Kimchi via an RPM file.
2. Check the firewall active services (`sudo firewall-cmd --list-services | grep kimchid`).
3. Restart the firewall service / reboot the system.
4. Repeat step (2).

## Expected behaviour ##

Step (4) should display the same output as step (2) - the ports should always be open.

## Actual behaviour ##

Step (4) doesn't display the `kimchid` service in the current firewall configuration.

**Comment by ramonmedeiros** [comment]
I will do it
