### ISSUE TITLE
repositories: Kimchi does not display metalink information

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#461]
Some YUM repositories may be configured with "metalink" instead of baseurl or mirrorlist.
In this case, Kimchi should be able to properly display the information to user.

From http://linux.die.net/man/5/yum.conf
metalink Specifies a URL to a metalink file for the repomd.xml, a list of mirrors for the entire repository are generated by converting the mirrors for the repomd.xml file to a baseurl.

[alinefm@alinefm]$ more /etc/yum.repos.d/fedora.repo 
[fedora-debuginfo]
name=Fedora $releasever - $basearch - Debug
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/releases/$releasever/Everything/$basearch/debug/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch
enabled=0
#metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

![28c72be7670390ca](https://cloud.githubusercontent.com/assets/4921718/4360164/f0085ee4-4278-11e4-9660-793591d08694.jpg)

**Comment by cd1** [comment]
Commit 1c716c6 has fixed this issue on the backend side. However, the UI still needs to be updated so the user can see and edit the field `metalink`.

**Comment by alinefm** [comment]
It was moved to Ginger Base https://github.com/kimchi-project/gingerbase/issues/124
