### ISSUE TITLE
Error in the log when using VMs not created by kimchi

### ISSUE THREAD

**Issue by wenwang1989** [kimchi-project/kimchi#465]
When kimchi deal with VMs that are not created by kimchi or build before we introducing "metadata", an error "metadata not found: Requested metadata element is not present" will continuously appear in the log, I have one suggestion from the feedback that is it possible to have this part removed? I mean the error message. One proper suggestion is :"Whichever function is causing that can be redirected to device called /dev/null so that it won't come to /var/log/messages". This error message comes up when we check the setMetadata() support.

**Comment by alinefm** [comment]
Fixed by ee0c11d3268e4742490744a47542562a12619e16
