### ISSUE TITLE
Feature: Show boot menu for a guest

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#467]
We can add a small check box on the Template tab to allow the boot menu to appear for a guest.

It is contolled by the 'bootmenu' tag in the 'os' xml element:

\<os>
    \<type arch='x86_64' machine='pc-i440fx-1.6'>hvm</type>
    \<boot dev='hd'/>
    \<boot dev='cdrom'/>
    \<bootmenu enable='yes' timeout='3000'/>
  \</os>

See: http://libvirt.org/formatdomain.html#elementsOSBIOS

**Comment by danielhb** [comment]
Fixed by d62079b

ps: no template option added at this time - bootmenu will be an 'Edit Guest' menu only.
