### ISSUE TITLE
Unable to pop up error changing PCI passthrough without IOMMU

### ISSUE THREAD

**Issue by wenwang1989** [kimchi-project/kimchi#490]
While using firefox, without the IOMMU, error pops up correctly: 

KCHVMHDEV0003E: No IOMMU groups found. Host PCI pass through needs IOMMU group to function correctly. Please enable Intel VT-d or AMD IOMMU in your BIOS, then verify the Kernel is compiled with IOMMU support. For Intel CPU, add intel_iommu=on to your Kernel parameter in /boot/grub2/grub.conf. For AMD CPU, add iommu=pt iommu=1.

But in IE, the screen just blinks and close the dialogue

How to reproduce:
1. Using IE and go to "Guest" tab 
2. Click "Action" and then "Edit"
3. Select "PCI" tab then change the options with "+" or "-"
screen just blinks and dialogue exited.

**Comment by cd1** [comment]
I can also confirm this issue using Chrome 41.0.2272.76 (64-bit) on Fedora 21.

**Comment by sstoppler** [comment]
@wenwang1989 @cd1 - Would you mind retrying this on latest version of Kimchi?  The PCI panel has gone through some changes and this may have gone away.  I tried it on Chrome  Version 52.0.2743.116 (64-bit) on Ubuntu 16.04 (as well as FF - although it didn't seem like it had that problem in that browser) and was unable to reproduce it.  Thanks!

**Comment by satishdotpatel** [comment]
In my kernel grub i have "intel_iommu=on iommu=pt"  both option set does that wrong?  I thought iommu=pt isn't just for AMD it just to provide good performance
