### ISSUE TITLE
System leftovers after uninstalling Kimchi

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#496]
After installing and uninstalling Kimchi the system has some leftovers:

[root@localhost ~]# find / -name kimchi
/etc/kimchi
/var/lib/kimchi
/var/log/kimchi
/usr/lib/python2.7/site-packages/kimchi
/usr/share/kimchi

**Comment by alinefm** [comment]
After installaing and removing Kimchi, some files keep on system under /etc/kimchi

    Before unstalling Kimchi
    [root@rhel7-vm ~]# find / -name kimchi
    /etc/kimchi
    /var/lib/kimchi
    /var/log/kimchi
    /usr/lib/python2.7/site-packages/kimchi
    /usr/share/kimchi

    Removing Kimchi
    [root@rhel7-vm ~]# yum remove kimchi
    Loaded plugins: langpacks, product-id, rhnplugin, subscription-manager
    This system is receiving updates from RHN Classic or Red Hat Satellite.
    Resolving Dependencies
    --> Running transaction check
    ---> Package kimchi.noarch 0:1.4.0-88.gitd5e7800.el7 will be erased
    --> Finished Dependency Resolution

    After unstalling Kimchi
    [root@rhel7-vm ~]# find / -name kimchi
    /etc/kimchi
    [root@rhel7-vm ~]# ls /etc/kimchi/
    kimchi-cert.pem kimchi-key.pem nginx_kimchi.conf

**Comment by ramonmedeiros** [comment]
i will take a look on this. I'm suspecting that the variables used on Fedora are not the same on RHEL

**Comment by cd1** [comment]
Fixed by 7fbb521930cb4e03bfa4f127bc73de3a02ef23a4 and 738165deb93b346f735be80b630bb1108ffe3eb0.
