### ISSUE TITLE
unsupported configuration: hda-duplex not supported in this QEMU binary

### ISSUE THREAD

**Issue by yuntongjin** [kimchi-project/kimchi#502]
make check on opensuse13.2 under kimchi 1.4rc1

======================================================================
ERROR: test_delete_running_vm (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 1306, in test_delete_running_vm
    inst.vm_start(u'kīмсhī-∨м')
  File "/home/simon/kimchi/src/kimchi/model/vms.py", line 878, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine k\u012b\u043c\u0441h\u012b-\u2228\u043c. Details: unsupported configuration: hda-duplex not supported in this QEMU binary

======================================================================
ERROR: test_image_based_template (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 237, in test_image_based_template
    inst.vm_start('kimchi-vm')
  File "/home/simon/kimchi/src/kimchi/model/vms.py", line 878, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine kimchi-vm. Details: unsupported configuration: hda-duplex not supported in this QEMU binary

======================================================================
ERROR: test_vm_cdrom (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 480, in test_vm_cdrom
    inst.vm_start(vm_name)
  File "/home/simon/kimchi/src/kimchi/model/vms.py", line 878, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine kimchi-cdrom. Details: unsupported configuration: hda-duplex not supported in this QEMU binary

======================================================================
ERROR: test_vm_disk (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 389, in test_vm_disk
    inst.vm_start(vm_name)
  File "/home/simon/kimchi/src/kimchi/model/vms.py", line 878, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine kimchi-cdrom. Details: unsupported configuration: hda-duplex not supported in this QEMU binary

======================================================================
ERROR: test_vm_edit (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 962, in test_vm_edit
    inst.vm_start('kimchi-vm1')
  File "/home/simon/kimchi/src/kimchi/model/vms.py", line 878, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine kimchi-vm1. Details: unsupported configuration: hda-duplex not supported in this QEMU binary

======================================================================
ERROR: test_vm_lifecycle (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 116, in test_vm_lifecycle
    inst.vm_start('kimchi-vm')
  File "/home/simon/kimchi/src/kimchi/model/vms.py", line 878, in start
    {'name': name, 'err': e.get_error_message()})
OperationFailed: KCHVM0019E: Unable to start virtual machine kimchi-vm. Details: unsupported configuration: hda-duplex not supported in this QEMU binary

----------------------------------------------------------------------
Ran 169 tests in 152.688s

FAILED (errors=6, skipped=3)
Makefile:479: recipe for target 'check-local' failed
make[3]: *** [check-local] Error 1
make[3]: Leaving directory '/home/simon/kimchi/tests'
Makefile:353: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/simon/kimchi/tests'
Makefile:355: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/home/simon/kimchi/tests'
Makefile:414: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by alinefm** [comment]
I have faced the same issue on a fresh Ubuntu 14.10 installation with my new laptop.
After some investigation, I identified it happened because I installed libvirt prior to enable virtualization on system BIOS.
So I needed to reinstall libvirt (after enabling virtualization on system BIOS) to get it working properly.

**Comment by cd1** [comment]
If that's the case, this is not Kimchi-related and we can close this issue.
