### ISSUE TITLE
"test_vm_disk" fails

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#507]
The test function `test_vm_disk` is failing.

I'm running Fedora 20 on a extracted tarball from commit tag `1.4.0-rc1`.
## How to reproduce
1. Extract the tarball to any directory.
2. Install Kimchi's requirement packages.
3. Run `./autogen.sh --system` from the repository working directory.
4. Run `sudo ./run_tests.sh test_model.ModelTests.test_vm_disk` from inside the directory `tests`. The test function also fails when running the complete test suite (i.e. `sudo make check`).
## Expected behaviour

After step (4), a report should be displayed indicating that the test `test_vm_disk` was successful.
## Actual behaviour

After step (4), a report is displayed indicating that `test_vm_disk` has failed.

Below is the test function summary:

> \======================================================================
> ERROR: test_vm_disk (test_model.ModelTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_model.py", line 390, in test_vm_disk
>     disk = _attach_disk()
>   File "test_model.py", line 329, in _attach_disk
>     disk = inst.vmstorages_create(vm_name, disk_args)
>   File "/home/vianac/kimchi/src/kimchi/model/vmstorages.py", line 144, in create
>     raise OperationFailed("KCHVMSTOR0008E", {'error': e.message})
> OperationFailed: KCHVMSTOR0008E: Error while creating new storage device: operation failed: open disk image file failed

**Comment by danielhb** [comment]
I can see the same error in my laptop, running Fedora 20. I'll take a look into it. Perhaps it is a symptom of something more serious.

**Comment by danielhb** [comment]
Patch sent to kimchi ML:

[PATCH] test_model: using default pool in test_vm_disk

**Comment by ramonmedeiros** [comment]
Here is the results of some tests:

Test 1
Fedora 21 (fresh install):
Directory: /root/KIMCHI
Test failed

Test 2
Fedora 21 (fresh install):
Directory: /home/KIMCHI
Test succesfuly

Seems that the problem can be running the test on /root directory. @danielhb please, post your environment. The test at your home failed.

**Comment by alinefm** [comment]
That is not applicable anymore on Fedora 25. I will close this issue by now.
