### ISSUE TITLE
Do not fill the screen with error when restarting/shutting down the host

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#510]
When the user restarts or shuts down the host, the screen is completely filled with error messages because the server has [obviously] been disconnected.

I'm running Fedora 20, Chrome 39.0.2171.71 (64-bit), on a extracted tarball from commit tag `1.4.0-rc1`.

## How to reproduce ##

1. Install and start Kimchi.
2. Login with an admin account (e.g. `root`).
3. Switch to the tab "Host" and click on the button "Restart". __WARNING:__ if you run this on localhost, your system will be restarted!

## Actual behaviour ##

After step (3), the screen is filled with numerous occurrences of the following error message:

> Can not contact the host system. Verify the host system is up and that you have network connectivity to it. HTTP request response rejected.

## Expected behaviour ##

After step (3), a more graceful way of disconnecting from the system should happen (e.g. logging out).

**Comment by alinefm** [comment]
Fixed by 9e47f9e0a43a7e6917981d7ab25664f69d598f3e
