### ISSUE TITLE
Cannot create a debug report

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#511]
An error is raised every time I try to create a debug report, thus, I can never create one.

I'm running Fedora 20, Chrome 39.0.2171.71 (64-bit), on a extracted tarball from commit tag `1.4.0-rc1`.

## How to reproduce ##

1. Install and start Kimchi.
2. Login with an admin account (e.g. `root`).
3. Switch to the tab "Host", scroll down to the section "Debug reports".
4. Click on the menu entry "Generate".
5. Click on the button "Generate".

## Actual behaviour ##

A few seconds after step (5), the following error message is displayed on the screen:

> Unexpected exception: KCHDR0003E: Unable to create debug report report-1417539367369. Details: 1.

And the following stack trace is saved to `/var/log/kimchi/kimchi-error.log`:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/kimchi/asynctask.py", line 70, in _run_helper
>     self.fn(cb, opaque)
>   File "/usr/lib/python2.7/site-packages/kimchi/model/debugreports.py", line 82, in sosreport_generate
    'err': retcode})
> OperationFailed: KCHDR0003E: Unable to create debug report report-1417536227053. Details: 1.

## Expected behaviour ##

After step (5), a debug report should be created successfully.

**Comment by alinefm** [comment]
I could not see this issue anymore on Fedora 23.
I will close it by now. Please, reopen if the problem persists for you.
