### ISSUE TITLE
"Software updates" doesn't show available updates

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#512]
There are a few updates to be downloaded on my system but Kimchi doesn't display them. The problem persists even after restarting the system. AFAIU, Kimchi should prompt me to update all available packages.

I'm running Fedora 20, Chrome 39.0.2171.71 (64-bit), on a extracted tarball from commit tag `1.4.0-rc1`.

## How to reproduce ##

1. Install and start Kimchi.
2. Login with an admin user (i.e. `root`).
3. Switch to the tab "Host" and scroll down to the section "Software updates".

## Actual behaviour ##

After step (3), the section "Software update" is empty.

The backend returns an empty list when running `GET /host/packagesupdate`, so there's nothing to be displayed by the UI.

Here is some command output for debugging:

> [vianac@localhost kimchi]$ curl -s -k -u \<user\>:\<password\> -H 'Content-Type: application/json' -H 'Accept: application/json' https://localhost:8001/host/packagesupdate
> [][vianac@localhost kimchi]$ sudo yum update
> Loaded plugins: langpacks, refresh-packagekit
> Resolving Dependencies
> --> Running transaction check
> ---> Package gstreamer-ffmpeg.x86_64 0:0.10.13-14.fc20 will be installed
> ---> Package gstreamer-plugins-ugly.x86_64 0:0.10.19-14.fc20 will be installed
> --> Processing Dependency: libopencore-amrwb.so.0()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> --> Processing Dependency: libmpeg2.so.0()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> --> Processing Dependency: libx264.so.138()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> --> Processing Dependency: libtwolame.so.0()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> --> Processing Dependency: libmp3lame.so.0()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> --> Processing Dependency: liba52.so.0()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> --> Processing Dependency: libopencore-amrnb.so.0()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> --> Processing Dependency: libmad.so.0()(64bit) for package: gstreamer-plugins-ugly-0.10.19-14.fc20.x86_64
> ---> Package gstreamer1-libav.x86_64 0:1.2.4-3.fc20 will be installed
> ---> Package gstreamer1-plugins-bad-freeworld.x86_64 0:1.2.4-1.fc20 will be installed
> --> Processing Dependency: libmpeg2encpp-2.1.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libvo-amrwbenc.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libmplex2-2.1.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libmjpegutils-2.1.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libfaad.so.2()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: librtmp.so.1()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libmpg123.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libdca.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libmimic.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> --> Processing Dependency: libmms.so.0()(64bit) for package: gstreamer1-plugins-bad-freeworld-1.2.4-1.fc20.x86_64
> ---> Package gstreamer1-plugins-ugly.x86_64 0:1.2.4-1.fc20 will be installed
> --> Running transaction check
> ---> Package a52dec.x86_64 0:0.7.4-18.fc19 will be installed
> ---> Package faad2-libs.x86_64 1:2.7-5.fc20 will be installed
> ---> Package lame-libs.x86_64 0:3.99.5-2.fc19 will be installed
> ---> Package libdca.x86_64 0:0.0.5-7.fc19 will be installed
> ---> Package libmad.x86_64 0:0.15.1b-16.fc19 will be installed
> ---> Package libmimic.x86_64 0:1.0.4-6.fc19 will be installed
> ---> Package libmms.x86_64 0:0.6.4-2.fc20 will be installed
> ---> Package libmpeg2.x86_64 0:0.5.1-10.fc19 will be installed
> ---> Package libmpg123.x86_64 0:1.19.0-1.fc20 will be installed
> ---> Package librtmp.x86_64 0:2.4-1.20131205.gitdc76f0a.fc20 will be installed
> ---> Package mjpegtools-libs.x86_64 0:2.1.0-3.fc20 will be installed
> ---> Package opencore-amr.x86_64 0:0.1.3-3.fc19 will be installed
> ---> Package twolame-libs.x86_64 0:0.3.13-3.fc19 will be installed
> ---> Package vo-amrwbenc.x86_64 0:0.1.2-1.fc19 will be installed
> ---> Package x264-libs.x86_64 0:0.138-2.20131030gitc628e3b.fc20 will be installed
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> \============================================================================================================================================================
>  Package                                        Arch                 Version                                       Repository                            Size
> \============================================================================================================================================================
> Installing for group upgrade "GNOME":
>  gstreamer-ffmpeg                               x86_64               0.10.13-14.fc20                               rpmfusion-free-updates               2.9 M
>  gstreamer-plugins-ugly                         x86_64               0.10.19-14.fc20                               rpmfusion-free                       316 k
>  gstreamer1-libav                               x86_64               1.2.4-3.fc20                                  rpmfusion-free-updates               2.8 M
>  gstreamer1-plugins-bad-freeworld               x86_64               1.2.4-1.fc20                                  rpmfusion-free-updates               157 k
>  gstreamer1-plugins-ugly                        x86_64               1.2.4-1.fc20                                  rpmfusion-free-updates               245 k
> Installing for dependencies:
>  a52dec                                         x86_64               0.7.4-18.fc19                                 rpmfusion-free                        58 k
>  faad2-libs                                     x86_64               1:2.7-5.fc20                                  rpmfusion-free-updates               148 k
>  lame-libs                                      x86_64               3.99.5-2.fc19                                 rpmfusion-free                       339 k
>  libdca                                         x86_64               0.0.5-7.fc19                                  rpmfusion-free                       102 k
>  libmad                                         x86_64               0.15.1b-16.fc19                               rpmfusion-free                        74 k
>  libmimic                                       x86_64               1.0.4-6.fc19                                  rpmfusion-free                        28 k
>  libmms                                         x86_64               0.6.4-2.fc20                                  rpmfusion-free-updates                48 k
>  libmpeg2                                       x86_64               0.5.1-10.fc19                                 rpmfusion-free                        67 k
>  libmpg123                                      x86_64               1.19.0-1.fc20                                 rpmfusion-free-updates               169 k
>  librtmp                                        x86_64               2.4-1.20131205.gitdc76f0a.fc20                rpmfusion-free-updates                69 k
>  mjpegtools-libs                                x86_64               2.1.0-3.fc20                                  rpmfusion-free                       158 k
>  opencore-amr                                   x86_64               0.1.3-3.fc19                                  rpmfusion-free                       172 k
>  twolame-libs                                   x86_64               0.3.13-3.fc19                                 rpmfusion-free                        51 k
>  vo-amrwbenc                                    x86_64               0.1.2-1.fc19                                  rpmfusion-free                        70 k
>  x264-libs                                      x86_64               0.138-2.20131030gitc628e3b.fc20               rpmfusion-free                       569 k
> 
> Transaction Summary
> \============================================================================================================================================================
> Install  5 Packages (+15 Dependent packages)
> 
> Total download size: 8.4 M
> Installed size: 21 M
> Is this ok [y/d/N]: n
> Exiting on user command
> Your transaction was saved, rerun it with:
>  yum load-transaction /tmp/yum_save_tx.2014-12-02.14-15.p84IKj.yumtx

## Expected behaviour ##

After step (3), some packages should be listed in the section "Software updates", the same ones displayed when running `sudo yum update`.

**Comment by cd1** [comment]
I cannot reproduce this bug anymore on Fedora 21.

**Comment by cd1** [comment]
It looks like this issue happens because the UI doesn't display an error message if something wrong occurs while trying to get the list of packages to be updated (and also when trying to get the list of repositories...). So there's no way to tell if the packages grid is empty because there's nothing to be updated or because there was an error when trying to get the packages list. As @alinefm reported in https://github.com/kimchi-project/kimchi/issues/512#issuecomment-65836456, the backend does return an error, but the UI doesn't display it.

I'll send a patch fixing this.

**Comment by alinefm** [comment]
Fixed by b529c0cd876d18ea6d3bee1b809979b785bbcb51
