### ISSUE TITLE
Unable to download ISO to storage pool on Firefox 31.3.0 ESR

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#518]
1. Login as admin
2. Switch to Storage Tab
3. Select any storage pool > Actions > Add Volume
4. Enter the URL: http://distfiles.gentoo.org/releases/x86/autobuilds/current-install-x86-minimal/install-x86-minimal-20141202.iso
5. The "Add" button keeps disabled and I am not able to start the download process

If I remove *any* character from the above URL the "Add" button enables.
Seems there is a character limit in the URL field or something like it.

**Comment by cd1** [comment]
Could you post the bug URL here so we can track it as well?

And while the Firefox team doesn't solve that, I think we should implement the URL validation some other way so it works for Firefox ESR users - or don't validate the URLs at all, as they will fail in the backend anyway in case they're invalid.
