### ISSUE TITLE
Storage pool disk size is reset to 10 when editing a template

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#520]
When I change the storage pool while editing a template, the disk size is always reset back to "10". If I have changed the value to another value (e.g. "15") and then I decide to choose a different storage pool, the value I entered will be lost for no apparent reason.

I'm running Fedora 20, Chrome 39.0.2171.71 (64-bit), on an extracted tarball from commit tag `1.4.0-rc1`.

## How to reproduce ##

1. Install and start Kimchi.
2. Login with an admin user (e.g. `root`).
3. Switch to the tab "Templates".
4. Select an existing template and click on  "Actions" > "Edit".
5. Switch to the tab "Storage".
6. Change the disk size of the storage device to any value different than "10".
7. Select a different storage pool from the combo box.

## Actual behaviour ##

After step (7), the disk size is reset to 10 and the value entered by the user on step (6) is lost.

## Expected behaviour ##

After step (7), only the storage pool should be changed, not the disk size.

**Comment by alinefm** [comment]
Fixed by aca40a17f487b5156f6b4b53cda672ce953cc10f
