### ISSUE TITLE
Dialog shows  contradictory information while extending a logical pool

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#521]
![156f3f3ef2bb36e5](https://cloud.githubusercontent.com/assets/4921718/5281779/c3d16468-7ae7-11e4-9ce2-cf8cb246915e.jpg)

It is a intermittent issue. Sometimes I tried the dialog only displayed the disk list without the message.

**Comment by alinefm** [comment]
It is still reproducible.

![7d6beda630b50b7a](https://cloud.githubusercontent.com/assets/4921718/18490683/782afa5e-79d9-11e6-87c6-58bb5eb6e4a8.jpg)

**Comment by lcorreia** [comment]
Also, "Looking for available partitions..." is never removed from screen.
