### ISSUE TITLE
Inconsistent style in dialog "Edit template"

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#522]
The tabs of the same dialog "Edit template" have different visual style.

I'm running Fedora 20, Chrome 39.0.2171.71 (64-bit), on an extracted tarball from commit tag `1.4.0-rc1`.

## How to reproduce ##

1. Install and start Kimchi.
2. Login with an admin user (e.g. `root`).
3. Switch to the tab "Templates".
4. Select an existing template and click on "Actions" > "Edit".
5. Switch to the tab "General" (the default one).
6. Switch to the tab "Storage".
7. Switch to the tab "Interface".
8. Switch to the tab "Processor".

## Actual behaviour ##

Steps (5) to (8) show different tabs in the same dialog with different styles:

![tmpl-1](https://cloud.githubusercontent.com/assets/169839/5281472/ea705b22-7ae4-11e4-8809-de825427eed6.png)
![tmpl-2](https://cloud.githubusercontent.com/assets/169839/5281471/ea6bbf40-7ae4-11e4-839c-e1fe6c0f6b48.png)
![tmpl-3](https://cloud.githubusercontent.com/assets/169839/5281473/ea71032e-7ae4-11e4-9c12-0028c914a594.png)
![tmpl-4](https://cloud.githubusercontent.com/assets/169839/5281604/518e757c-7ae6-11e4-8f9c-e4870d7283f5.png)

The main points are:

* The tab "General" has the default style for Kimchi. Its text fields and combo box look like the other text fields and combo boxes elsewhere on Kimchi.
* The tab "Storage" uses a combo box and a text field with a style different than the tab "General".
* The tab "Interface" uses a combo box with a style different than the tab "General".
* The tab "Processor" uses a text field and a combo box with a style different than the tab "General". 
  * The disabled text field looks different - it doesn't change the mouse cursor when hovered.
  * The checkbox label isn't aligned with the checkbox item and it isn't clickable - clicking the label should have the same effect as clicking the checkbox item.
  * The extra elements which appear when clicking on the checkbox don't have the fade effect used elsewhere when extra elements are added to the screen due to user choices. For example, see the effect in "Template" > "+" > "Local ISO file" > "I want to use a specific file", "Network" > "+" > "Bridged" (when coming from a different network type).

## Expected behaviour ##

Steps (5) to (8) should show tabs with the same, consistent style.

**Comment by alinefm** [comment]
This issue does not apply to the new UI so I will close it.
