### ISSUE TITLE
UI: Unable to see full disk path in guest configuration

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#523]
![63e89ba629f4a64c](https://cloud.githubusercontent.com/assets/4921718/5283083/926aa91a-7af2-11e4-9663-e71058ebbe5c.jpg)

The disk path is truncated but there is a lot of space on UI do display it completely.

**Comment by sstoppler** [comment]
@alinefm - would you mind revisiting this w/the new UI?  I tried this scenario and it now looks like this with new UI and space has been taken advantage of:

![image](https://cloud.githubusercontent.com/assets/11432111/15516312/0ee4cc12-21a7-11e6-8e16-cffb7552cb64.png)
