### ISSUE TITLE
make check-local failed on opensuse 13.2

### ISSUE THREAD

**Issue by yuntongjin** [kimchi-project/kimchi#528]
simon@linux-fb5b:~/kimchi> make check-local
PYTHONPATH=src contrib/check_i18n.py plugins/*/i18n.py src/kimchi/i18n.py 
Checking for invalid i18n string...
Checking for invalid i18n string successfully
find . -path './.git' -prune -type f -o \
	-name '*.py' -o -name '*.py.in'  | xargs /usr/bin/pyflakes | \
	grep -w -v "\./src/kimchi/websocket\.py" | \
	while read LINE; do echo "$LINE"; false; done
./contrib/check_i18n.py:48:47: invalid syntax
            print "bad i18n string formatting:"
                                              ^
./src/kimchi/asynctask.py:71:25: invalid syntax
        except Exception, e:
                        ^
./src/kimchi/auth.py:172:25: invalid syntax
        except PAM.error, (resp, code):
                        ^
./src/kimchi/config.py.in:67:21: invalid syntax
    except Exception, e:
                    ^
./src/kimchi/control/base.py:106:36: invalid syntax
            except MissingParameter, e:
                                   ^
./src/kimchi/control/utils.py:111:27: invalid syntax
    except ValidationError, e:
                          ^
./src/kimchi/imageinfo.py:72:21: invalid syntax
    print probe_image(sys.argv[1])
                    ^
./src/kimchi/isoinfo.py:501:18: invalid syntax
    print iso_list
                 ^
./src/kimchi/kvmusertests.py:75:12: invalid syntax
    print ut.probe_user()
           ^
./src/kimchi/model/debugreports.py:129:25: invalid syntax
        except Exception, e:
                        ^
./src/kimchi/model/featuretests.py:111:36: invalid syntax
        except libvirt.libvirtError, e:
                                   ^
./src/kimchi/model/hostdev.py:286:31: invalid syntax
        print "No device found"
                              ^
./src/kimchi/model/model.py:81:40: invalid syntax
            except libvirt.libvirtError, e:
                                       ^
./src/kimchi/model/storagepools.py:107:24: invalid syntax
        except KeyError, item:
                       ^
./src/kimchi/model/storagevolumes.py:168:24: invalid syntax
        except KeyError, item:
                       ^
./src/kimchi/model/templates.py:102:25: invalid syntax
        except Exception, e:
                        ^
./src/kimchi/model/vms.py:347:36: invalid syntax
        except libvirt.libvirtError, e:
                                   ^
./src/kimchi/model/vmsnapshots.py:87:70: invalid syntax
        except (NotFoundError, OperationFailed, libvirt.libvirtError), e:
                                                                     ^
./src/kimchi/objectstore.py:51:33: invalid syntax
        objects.sort(key=lambda (_, obj): obj[sort_key])
                                ^
./src/kimchi/repositories.py:134:25: invalid syntax
        except Exception, e:
                        ^
./src/kimchi/rollbackcontext.py:60:33: invalid syntax
            raise undoExcInfo[0], undoExcInfo[1], undoExcInfo[2]
                                ^
./src/kimchi/root.py:135:24: invalid syntax
        except KeyError, item:
                       ^
./src/kimchi/sslcert.py:86:11: invalid syntax
    print c.cert_text()
          ^
./src/kimchi/swupdate.py:158:25: invalid syntax
        except Exception, e:
                        ^
./src/kimchi/template.py:96:19: invalid syntax
    except OSError, e:
                  ^
./src/kimchi/vnc.py:36:44: invalid token
        os.makedirs(WS_TOKENS_DIR, mode=0755)
                                           ^
./src/kimchi/config.py:67:21: invalid syntax
    except Exception, e:
                    ^
./tests/test_mockmodel.py:77:38: invalid syntax
            except cherrypy.HTTPError, e:
                                     ^
./tests/test_model.py:1440:35: invalid syntax
            except OperationFailed, e:
                                  ^
./tests/utils.py:199:24: invalid syntax
        except KeyError, e:
                       ^
./ui/pages/help/gen-index.py:55:19: invalid syntax
    print HTML_HEAD
                  ^
./src/kimchi/exception.py:33: undefined name 'unicode'
./src/kimchi/exception.py:39: undefined name 'unicode'
./src/kimchi/exception.py:43: undefined name 'unicode'
./src/kimchi/exception.py:50: undefined name 'unicode'
./src/kimchi/mockmodel.py:360: undefined name 'unicode'
./src/kimchi/mockmodel.py:573: undefined name 'unicode'
./src/kimchi/model/host.py:100: undefined name 'unicode'
./src/kimchi/model/utils.py:36: undefined name 'xrange'
./src/kimchi/utils.py:77: undefined name 'basestring'
./tests/test_rest.py:189: undefined name 'xrange'
./tests/test_rest.py:982: undefined name 'xrange'
./tests/test_rest.py:1033: undefined name 'xrange'
./tests/test_rest.py:1132: undefined name 'xrange'
./tests/test_rest.py:1631: undefined name 'xrange'
./tests/test_rest.py:1650: undefined name 'xrange'
Makefile:820: recipe for target 'check-local' failed
make: *** [check-local] Error 1

**Comment by ramonmedeiros** [comment]
Hi, i did not reproduce this on my suse 13.2 (vm on my laptop)

Can you give us more details?

**Comment by alinefm** [comment]
Closing based on last comment.
