### ISSUE TITLE
Do not collect stats when stats tab is folded

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#534]
### Description
When stats sub-tab in host tab is folded, we are continuing collecting stats, in fact, users fold this tab means does not care about it any more.

### How to reproduce
*  Login kimchi
*  Use firebug to track the request and responses

### Expected result
Stop querying stats

### Actual result
Stats querying continuing

**Comment by alinefm** [comment]
This issue does not apply to the new UI design. Closing it.
