### ISSUE TITLE
Kimchi does not support NIC hot plug

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#548]
### Description
Adding interface is disabled when kimchi is running

### Expected result
Be able to add an interface when kimchi is running

### Actual result
Adding button is hidden from UI

**Comment by cd1** [comment]
Commit 81dd7ce7648fbf897c7d07b5b154fe1aab766cc8 has added the support for NIC hotplug. However, the UI still needs to be updated in order to allow the user to trigger those actions.

**Comment by cd1** [comment]
Commit 0ef10a162ecd467092e47c0b837a6ce8db51625f has enabled this feature to the UI.
