### ISSUE TITLE
System update may be killed when stopping Kimchi

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#557]
If a system update is still running when the Kimchi service is stopped, it may leave the system in an inconsistent state.

## How to reproduce ##

1. Install and start Kimchi.
2. Login with an admin user (e.g. `root`).
3. Switch to the tab "Host".
4. Scroll down to the section "Software updates".
5. Click on the menu entry "Update All".
  - If it's not enabled, wait for a system update to be available.
6. Perform one of the following operations:
  - Scroll up and click on the button "Shut Down".
  - Scroll up and click on the button "Restart".
  - Stop the Kimchi service.

## Actual behaviour ##

After step (6), the system update might be killed and the system may be left in an inconsistent state.

## Expected behaviour ##

Before step (6) is completed, Kimchi should wait for the system update to finish, so the system is left in a good state.

**Comment by laggarcia** [comment]
Another possibility is to spawn the yum process in the background so that it can keep processing after Kimchi service is restarted.

**Comment by pvital** [comment]
@laggarcia this solves only the case of stop the Kimchi service. If the user click to shutdown or reboot the host, the update process will be compromised anyway.

**Comment by laggarcia** [comment]
@Truja has a tentative fix for this that he might be sending to the community soon (if not already). Basically we are allowing kimchid sibling processes to continue to run after kimchid is stopped.

@pvital, IIRC, yum will inhibit machine shutdown or reboot while it is running. Not sure about other package managers.

**Comment by Truja** [comment]
This is already fixed.
Systemd configuration for Kimchid was changed and YUM process is not stopped when Kimchid dies or restart. Yum becomes a process child of INIT.

**Comment by alinefm** [comment]
Fixed by e1aab0da65f7aa8ee97540ae1698512376bd4f25, baa7cce28116401c3f7aac4f8ef57fa2f4c433ac, 35e33d8e58c805d36f81bd6d605f64de3e719aa4 b2f73636e7353551a870ff9584ec199c4b92ff8d
