### ISSUE TITLE
About CPUs

### ISSUE THREAD

**Issue by sidealice** [kimchi-project/kimchi#562]
If I have 2 x5650( 12cores per CPU) 
How can I input the CPUs under template/guest  parameter? 
The maxium would be 24 right?

**Comment by alinefm** [comment]
Hi @sidealice 
It is only possible in the Template level.
Select the Template you want to change > Edit > Switch to "Processor" tab > Select "Manually set CPU topology" check box and input the values you want.

**Comment by alinefm** [comment]
Closing based on last comment.
