### ISSUE TITLE
Delete network button works even disabled

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#563]
This is easy to reproduce. Open Kimchi and go to Network tab:
1- Create a new NAT network;
2- Click on Actions button. "Start" and "Delete" buttons will be enabled ("Delete" is red);
3- Go to Guest tab and assign the new network to some VM;
4- Back to Network tab, click on Actions button. Now "Start" button is enabled , but "Delete" is disabled.
5- Click on the disabled "Delete" button, it is going to work and ask confirmation.

Warn the user and ask confirmation to delete a network in use is OK, but I think that if the button is visually disabled, it should not work.
The logic must be reviewed.

**Comment by cd1** [comment]
I can confirm this bug on Fedora 21 (Kimchi cfba104, libvirt-1.2.9.1-2.fc21.x86_64, Chrome 39.0.2171.95 (64-bit)).
