### ISSUE TITLE
List volumes other than "format=iso" when creating a template

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#564]
If the user has storage volumes with formats different than "iso", they cannot create a template with those volumes because the web UI only displays volumes with "format=iso". But those volumes are perfectly valid images and libvirt is able to create VMs using them.

AFAIK, all volumes in a logical storage pool are listed by libvirt with "format=raw", so this issue prevents the creation of templates - and VMs - using volumes from logical storage pools.

I'm running Fedora 21 but this issue should be reproduced in any distro.

## How to reproduce ##

1. Install and start Kimchi.
2. Log in with an admin user (e.g. "root").
3. Make sure there is at least one storage volume with a format different than "iso".
  - Switch to the tab "Storage", then click on each storage pool entry, then look for a volume with "Format: raw".
4. Switch to the tab "Templates".
5. Click on the button "+".
6. In the new dialog, click on "Local ISO Image".

## Actual behaviour ##

After step (6), the images referenced in step (3) are not listed.

## Expected behaviour ##

After step (6), the images referenced in step (3) should be listed.

**Comment by ramonmedeiros** [comment]
I will work on it

**Comment by cd1** [comment]
I'll send a patch which opens and inspects every volume inside a logical pool to find out if it's an ISO image. The volumes which don't belong to a logical pool will still rely on the file format provided by libvirt.
