### ISSUE TITLE
Provide a method to filter Kimchi resources

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#57]
Now we display all VM tiles in a single page, When we have dozens of VM tiles we will need to page them.

**Comment by alinefm** [comment]
It was integrated with the new UI deisgn.
Fixed by 611d9e80e9c28054d79bf73350f2ecc2d9eceba5 cbce1ad7807623820a6765c71dc407be3de17cb3 4e85285184c8364ce8056db15de62f73b998ade1 447b5e6b263590d43ee512f96d2d30978e72d3c1
