### ISSUE TITLE
Unable to login using Mac OS X Safari

### ISSUE THREAD

**Issue by pvital** [kimchi-project/kimchi#576]
Unable to login using Safari (Version 8.0.2 (10600.2.5)) web browser from Mac OS X (Yosemite Version 10.10.1 (14B25)). The login page appears but after enter user and password the login page appears again.

Using Google Chrome in the same system the issue doesn't happens.

**Comment by cd1** [comment]
I tested using Safari 8.0.3, MacOS X Yosemite 10.10.2 and I was able to login correctly. Can you update your Safari and try to reproduce this bug again?

**Comment by pvital** [comment]
Something interesting. I could login when the Kimchi server is a Fedora 21, but not when a Debian Testing. The Safari console show the following message:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery-1.10.0.min.map, line 0)

**Comment by cd1** [comment]
Hum, so maybe this issue isn't browser-only related, as I was thinking...

How are you running Kimchi on Debian Testing? Via Git, tarball, .deb package? Please provide the exact commit ID or Kimchi version you're using.

**Comment by pvital** [comment]
Using git code (build as usual: ./autogen.sh --system; make; sudo src/kimchid) , last commit a17379a

**Comment by pvital** [comment]
It's working now with latest HEAD from github repository. Closing
