### ISSUE TITLE
virDomainListAllSnapshots not supported by test driver on Fedora 20

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#577]
I ran the tests and got over 100 failures. I thought about just disabling the snapshot tests if this isn't supported, but then I saw that snapshots for a domain are now deleted on a VM, so the fix would be a lot more involved than that. I figured I should let Cristian handle this since he just implemented all the snapshot patches.

Here's the stack trace from my pdb session:

(Pdb) s
--Call--
> /home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py(64)wrapper()
-> def wrapper(*args, **kwargs):
(Pdb) s
> /home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py(65)wrapper()
-> try:
(Pdb) s
> /home/christy/git/kimchi-upstream/src/kimchi/model/libvirtconnection.py(66)wrapper()
-> ret = f(*args, **kwargs)
(Pdb) s
--Call--
> /usr/lib64/python2.7/site-packages/libvirt.py(2228)listAllSnapshots()
-> def listAllSnapshots(self, flags=0):
(Pdb) s
> /usr/lib64/python2.7/site-packages/libvirt.py(2230)listAllSnapshots()
-> ret = libvirtmod.virDomainListAllSnapshots(self._o, flags)
(Pdb) s
libvirt:  error : this function is not supported by the connection driver: virDomainListAllSnapshots
> /usr/lib64/python2.7/site-packages/libvirt.py(2231)listAllSnapshots()
-> if ret is None:
(Pdb) s
> /usr/lib64/python2.7/site-packages/libvirt.py(2232)listAllSnapshots()
-> raise libvirtError("virDomainListAllSnapshots() failed", conn=self)
(Pdb) 
--Call--
> /usr/lib64/python2.7/site-packages/libvirt.py(31)__init__()
-> def __init__(self, defmsg, conn=None, dom=None, net=None, pool=None, vol=None):

libvirt version: libvirt-1.1.3.8-1.fc20.x86_64
libvirt-python: libvirt-python-1.1.3.8-1.fc20.x86_64

**Comment by alinefm** [comment]
@clnperez could you confirm if reverting the commit fe38d2383db7bb3c1ae6283a5931f8984dda0d8c solves the problem?

**Comment by clnperez** [comment]
@alinefm - It definitely got rid of all the error messages about the test driver, but it still left failures in the REST tests due to an assert in almost every test:  AssertionError: 201 != 500

FYI: With that commit reverted, the new failure report was failures=20, errors=12, skipped=2

**Comment by clnperez** [comment]
I think we can close this issue, and I'll open a new one for the other issues with F20.
