### ISSUE TITLE
Kimchi does not handle "Pause"  state

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#578]
If you start a VM and pause (via VirtManager), Kimchi will display VM as off.

If you try to power on the VM, kimchi will display "Cannot power on, domain is still running".

Would be nice to include the pause button in the guest tab and also handle this state.

**Comment by ramonmedeiros** [comment]
If the VM is paused and you start it, kimchi will display correctly as running

**Comment by ramonmedeiros** [comment]
Seems that @cd1 already submitted a patch for this. This issue can be closed.

**Comment by cd1** [comment]
I submitted the patch for the backend code - which, by the way, will not be applied before the next release, 1.4.1. But in order to solve the problem you described here, the UI must also be updated, and that hasn't been done yet.
