### ISSUE TITLE
qemu_iso_stream_dns returns wrong value

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#579]
# Description
Feature tests which count on a running kimchi server, e.g. qemu_supports_iso_stream, qemu_iso_stream_dns, does not perform right when kimchi server is not running

# How to reproduce
On a system not supporting qemu_iso_stream_dns, import feature tests module and call qemu_iso_stream_dns, you will see qemu_iso_stream_dns returns True

# Reason
When kimchi server is not running, qemu-io returns with return code 0 rather than error code.
[royce@localhost tests]$ sudo qemu-io -r http://localhost:8080/images/icon-fedora.png -c 'read -v 0 512'
[sudo] password for royce: 
CURL: Error opening file: Failed connect to localhost:8080; Connection refused
qemu-io: can't open device http://localhost:8080/images/icon-fedora.png
no file open, try 'help open'
[royce@localhost tests]$ echo $?
0

**Comment by cd1** [comment]
Fixed by d5e780038940814254361da57c4459ce437637f7.
