### ISSUE TITLE
Error usage of feature tests on model tests

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#580]
## Description
Some feature tests count on a running kimchi server: qemu_supports_iso_stream, qemu_iso_stream_dns, so they cannot be used for model tests

**Comment by cd1** [comment]
Isn't this a duplicate of issue #579?

**Comment by lvroyce** [comment]
No, they are different issues, 579 means qemu_iso_stream_dns function is implemented wrong. This means we cannot use these two functions in feature tests. Please reopen.

**Comment by cd1** [comment]
Fixed by d5e780038940814254361da57c4459ce437637f7.
