### ISSUE TITLE
Feature Suggestion: Random MAC Address when cloning VM

### ISSUE THREAD

**Issue by demon012** [kimchi-project/kimchi#581]
Hey guys,

I like to have a template virtual machine that is setup to use as a template for when I need a new virtual machine.

I then just clone the VM but the problem is it clones every aspect including it's mac address. 

It would be nice when cloning to have the option to clone with a new random mac address via some checkbox or another clone button.

I know this is not high priority but it is a nice thing to have as it removes the need to use virsh edit to change the mac address of the cloned vm.

I may also take a stab at implementing this myself if I get some spare time.

Thanks,

Alan

**Comment by demon012** [comment]
Clone has been removed from VM's (I was using an older version of Kimchi).

**Comment by cd1** [comment]
Which version of Kimchi are you using? The clone feature has not been removed, and it does create a new random MAC address for each new VM.

Let us know if you can accomplish this feature, it should be available to you.
