### ISSUE TITLE
Arch Linux not identified as a modern distribution so is set to use the e1000 NIC driver

### ISSUE THREAD

**Issue by demon012** [kimchi-project/kimchi#583]
When creating virtual machines via a template Kimchi currently just sets the network driver to e1000. This does not perform as well as virtio so I currently have to go and manually edit the VM's model type using virsh edit. 

It would be nice if we could click a checkbox to either set the driver to virtio or to type the driver we want into a box (more flexible).

**Comment by demon012** [comment]
Actually, I just went poking around in the code and I see what Kimchi has done, Kimchi is not identifying Arch Linux as a modern distribution so it is setting its virtual network adapter to be e1000.

I will work on a patch to make it identify Arch as a modern distribution as it is rolling release like Gentoo.

**Comment by demon012** [comment]
I submitted a patch to the kimchi mailing list that fixes this problem.

**Comment by alinefm** [comment]
Fixed by 2aacf14756c8d076a69114e914248e8b372c51d2 and 7fd7aedff9250fcedf941933129013a6afd9311f
