### ISSUE TITLE
make clean' does not revert its changes from 'make rpm'

### ISSUE THREAD

**Issue by laggarcia** [kimchi-project/kimchi#585]
After running make rpm, if you run make clean to clean all the build artifacts and get a clean source tree again, you'll still have files left from the make rpm process.

Steps to reproduce:

1) make rpm
2) make clean
3) git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ChangeLog
	modified:   plugins/sample/po/en_US.po
	modified:   plugins/sample/po/pt_BR.po
	modified:   plugins/sample/po/sample.pot
	modified:   plugins/sample/po/zh_CN.po
	modified:   po/de_DE.po
	modified:   po/en_US.po
	modified:   po/es_ES.po
	modified:   po/fr_FR.po
	modified:   po/it_IT.po
	modified:   po/ja_JP.po
	modified:   po/kimchi.pot
	modified:   po/ko_KR.po
	modified:   po/pt_BR.po
	modified:   po/ru_RU.po
	modified:   po/zh_CN.po
	modified:   po/zh_TW.po

no changes added to commit (use "git add" and/or "git commit -a")
[laggarcia@lagarcia kimchi]$

**Comment by ramonmedeiros** [comment]
Would be nice to change the name of this issue to "make clean does not revert changes on files", since every file list above was edited, not created. 

To fix this, we must create new files instead of editing, like we do with Makefile (there is a .am file, which is tracked by git)

**Comment by clnperez** [comment]
The new title can still be misinterpreted. I read it and thought that the issue was asking for make clean to do a 'git revert --hard' and set all your local changes back (which seemed like a strange request). How about "'make clean' does not revert its changes from 'make rpm', or 'make should not edit files during 'make rpm,'" or even "'make rpm' leaves behind modified tracked files?"

**Comment by danielhb** [comment]
We have a similar issue in Ginger: https://github.com/kimchi-project/ginger/issues/11

The solution used there was to commit to master the latest version of changelog and translations.

**Comment by alinefm** [comment]
The patch applied does not fix the problem. It only reverts the changes made by 'make rpm' but instead of that, we should prevent 'make rpm' to change file. It should only package the application without modifying anything.

**Comment by danielhb** [comment]
The patch did exactly what the issue complained about

If the idea is to change how make rpm works we need to change the bug title
IMO

Em 08/09/2016 10:11 AM, "Aline Manera" <notifications@github.com> escreveu:
