### ISSUE TITLE
Man page submission for kimchid

### ISSUE THREAD

**Issue by frediz** [kimchi-project/kimchi#587]
Hi,
in debian packaging, I added a manpage to kimchid (which is mandatory for binaries going in /usr/bin).
It would be nice to have it upstream. I based it on kimchid --help, COPYING and AUTHORS file.
Could you review it and consider adding it ?
Thank you

http://paste.debian.net/144230

**Comment by alinefm** [comment]
@frediz Please, send a patch to Kimchi ML for review.
You can check https://github.com/kimchi-project/kimchi/wiki/How-to-Contribute for more details on how to contribute.

**Comment by frediz** [comment]
For reference :
http://lists.ovirt.org/pipermail/kimchi-devel/2015-February/009735.html

**Comment by cd1** [comment]
Fixed by c1553bbf45cbf603abee3caeb38e30afcca7869f.
