### ISSUE TITLE
Sources of minified javascript

### ISSUE THREAD

**Issue by frediz** [kimchi-project/kimchi#588]
Hi,
could you please provide original javascript files (.dev.js) for all minified files in the sources ? This is not only useful for debugging, it's also a requirement of some free software distributions like Debian.

Missing files that are reported by lintian checks :

    ui/libs/jquery-ui.min.js
    ui/libs/jquery-ui-i18n.min.js
    ui/libs/jquery-1.10.0.min.js

Ideally the build process of wordpress would include a way to regenerate automatically the minified files from the corresponding .dev.js file.
Thanks!

**Comment by frediz** [comment]
Could you confirm the sources I found : 
http://code.jquery.com/ui/1.10.3/jquery-ui.js
http://code.jquery.com/jquery-1.10.0.js (but seems having sizzle.js)
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/i18n/jquery-ui-i18n.js (could only find it on googleapis)

**Comment by alinefm** [comment]
@frediz The files under /ui/libs are imported from JQuery UI ((http://jqueryui.com))
