### ISSUE TITLE
Kimchi can leave behind VMs if startup is interrupted

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#589]
Before @Truja submitted the workaround for the update issue, it was noticed that kimchi would fail to start with the error, "dom = conn.defineXML(SIMPLE_VM_XML)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3335, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirtError: operation failed: domain 'A_SIMPLE_VM' already exists with uuid e6fccea8-f7ed-4320-a4cb-b85217d2398."

This is because those checks are done during startup, and if they fail, kimchi fails to start. You can test by creating a vm with the name "A_SIMPLE_VM." The UUIDs do not have to be the same. The libvirt error message is a little misleading in that way.

We need to find a way to make sure that no VMs are left behind by Kimchi if its startup is interrupted for any reason.

**Comment by clnperez** [comment]
@alinefm suggested creating an extra CherryPy listener that would make sure all VMs are cleaned up on exit, and we would need to keep a record of all resources that need to be destroyed.

**Comment by alinefm** [comment]
Patch sent to Kimchi ML: [PATCH] Fix issue #589: Add listener to remove Kimchi leftovers
