### ISSUE TITLE
On F21 and OpenSuse 13.2, we need to install python-requests

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#594]
Everytime i will run tests on this distros, i need to reinstall the package. Seems that the library has been removed from other package

**Comment by cd1** [comment]
That package is listed as a dependency in `docs/README.md`, so you need to install it manually before running the tests.

For Fedora:

    # These dependencies are only required if you want to run the tests:
    $ sudo yum install pyflakes python-pep8 python-requests

For openSUSE:

    # These dependencies are only required if you want to run the tests:
    $ sudo zypper install python-pyflakes python-pep8 python-requests
