### ISSUE TITLE
Memory is set to 0 (null) when editing guest

### ISSUE THREAD

**Issue by pvital** [kimchi-project/kimchi#595]
How to reproduce - using commit 16d7e48 as HEAD:

1. Create a new template and edit it to use 2048MB of RAM;
2. Create a new guest using the create template on step 1;
3. Click on Actions -> Edit;
4. The memory values is 0 (null).

![screenshot from 2015-02-13 11 36 35](https://cloud.githubusercontent.com/assets/699330/6186053/2836e12e-b375-11e4-8a8c-cab26991fa6e.png)

**Comment by ramonmedeiros** [comment]
Did not reproduced on my machine with remote iso template.


Fedora 19
Kimchi HEAD 16d7e48205cb789a191fe130aeeba12fa077ac30

**Comment by ramonmedeiros** [comment]
Still working with local iso template.

**Comment by cd1** [comment]
I confirm this issue on Fedora 21. Newer libvirt versions now return 0 when the user asks for the VM's memory and the VM is shutoff.
