### ISSUE TITLE
Cannot use unallocated images with LVM

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#596]
This is mostly a placeholder until I remember to submit the patch, but we need to set allocation=capacity if the storage pool type is logical.

In vmtemplate.py, something close to:

if 'logical' == self._get_storage_type():
    info['allocation'] = info['capacity']
else:
    info['allocation'] = 0

I'll send this ASAP.

**Comment by clnperez** [comment]
Sent upstream.

**Comment by alinefm** [comment]
Fixed by 3cdb13785d7951339d6d27df4f565f18d8fa03cb
