### ISSUE TITLE
Unable to select radio button "Upload a file" for storage pool

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/kimchi#598]
If you want to select the radio button, it isn't actionable. The radio button needs to be fixed.

**Comment by cd1** [comment]
That's because the upload feature isn't reliable yet, so it's disabled in the UI. As soon as that feature is merged (and works correctly), the radio button should be selectable again.

**Comment by clnperez** [comment]
Well that's confusing. I guess it's not worth changing now, but you'd think it would have been hidden, not just disabled.

**Comment by laggarcia** [comment]
I agree with Christy: we either hide the button or implement the feature.

**Comment by alinefm** [comment]
The option is there and disabled to inform to user the feature will come soon.

**Comment by laggarcia** [comment]
Is there a message saying that the feature will come soon? Sorry, but a disabled options just lead users to misunderstandings...

**Comment by cd1** [comment]
The feature is now available on the web UI and the upload radio button can be selected.
