### ISSUE TITLE
Use log level for better logs

### ISSUE THREAD

**Issue by frediz** [kimchi-project/kimchi#601]
Hi,
kimchi provides various log level. On the other side logs are a bit rough and sometimes scary.
I would be nice to use log levels to enhance log files.
This is a follow up on a ginger issue : https://github.com/kimchi-project/ginger/issues/8 that I'm forwarding  here, following Daniel's advice.

Fred.

**Comment by alinefm** [comment]
Fixed on Wok https://github.com/kimchi-project/wok/issues/35
