### ISSUE TITLE
ubuntu server 14.04 lTS - Not working

### ISSUE THREAD

**Issue by ychoucha** [kimchi-project/kimchi#603]
Hello,

well well,
some look very cool i can't make it works :'(

im on ubuntu 14.04 LTS i have sucessefull compile and lunche the application : 

```
ychoucha[~/kimchi-master] > sudo kimchid --host=0.0.0.0
WebSocket server settings:
  - Listen on :64667
  - Flash security policy server
  - Web server. Web root: /usr/share/kimchi/ui/pages/websockify
  - SSL/TLS support
  - Deny non-SSL/TLS connections
  - proxying from :64667 to targets in /var/lib/kimchi/vnc-tokens
```

but when i try to log in : 
![kvm_web_access_pb](https://cloud.githubusercontent.com/assets/301074/6546243/f1e1bbae-c5ac-11e4-9782-e8328dd940ed.jpg)

what do u think please ?

**Comment by wdevilliers** [comment]
Hi, ychoucha ,try browsing to https://192.168.50.40:8001

**Comment by ychoucha** [comment]
Not Working
![kimchid_not_working](https://cloud.githubusercontent.com/assets/301074/6560092/c920d4b2-c687-11e4-973b-f5744a22cf00.jpg)

**Comment by alinefm** [comment]
@ychoucha Have you properly set up the firewall configuration to open ports 8000/8001/64667?

**Comment by ychoucha** [comment]
We don't have a firewall : 
![firewall_ubuntu](https://cloud.githubusercontent.com/assets/301074/6561016/628dc17c-c68e-11e4-871a-3c0d24e9b5f7.jpg)

**Comment by alinefm** [comment]
@ychoucha Even firewalld?

Also try to run  "sudo kimchid --host=0.0.0.0 --environment=development" to get more output details.

Are you able to access Kimchi from localhost?

**Comment by lvroyce** [comment]
I'm running ubuntu server 14.04 and not able to reproduce this.

**Comment by justhankmoody** [comment]
@ychoucha  -  If ufw disabled try to  check iptables rules.
For example: 
Backup all iptables rules.
run iptables -F for flush all rules and restart kimchi.
If page is open - need  restore rules and open ports.

Or show command result: iptables -L

**Comment by ychoucha** [comment]
ok works on a new frech install.

on my  server i used many think like  : 

tvheadend
domoticz

maybe someone make a conflict
