### ISSUE TITLE
Repository query returns error information

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#607]
Instead of getting repository information, kimchi returns following error:
![screen1](https://cloud.githubusercontent.com/assets/4928887/6613794/be568fee-c8cc-11e4-8310-737b1f129df8.png)

**Comment by lvroyce** [comment]
This is under Ubuntu 14.04

**Comment by alinefm** [comment]
@lvroyce It is expected as there is another process in the host system locking apt.
Make sure the other process has finished and try to reload the grid content by clicking on "Retry" button
