### ISSUE TITLE
Previous peer entry remains when kimchi stops or hostname updated

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#614]
## Reproduction
Keep kimchi default host server address settings, and turn on federation
turn off peer kimchi or change peer kimchi's hostname

## Expect result
when kimchid turn off, peer entry removed
when peer's hostname changes, corresponding peer entry changes

## Actual result
Previous peer entry unchanged

**Comment by alinefm** [comment]
Fixed by bb9ccf7d405898ae13a52fc970376342bbc8154b
