### ISSUE TITLE
RHEL7: System leftovers while removing Kimchi

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#615]
After installaing and removing Kimchi, some files keep on system under /etc/kimchi

* Before unstalling Kimchi
[root@rhel7-vm ~]# find / -name kimchi
/etc/kimchi
/var/lib/kimchi
/var/log/kimchi
/usr/lib/python2.7/site-packages/kimchi
/usr/share/kimchi

* Removing Kimchi
[root@rhel7-vm ~]# yum remove kimchi
Loaded plugins: langpacks, product-id, rhnplugin, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
Resolving Dependencies
--> Running transaction check
---> Package kimchi.noarch 0:1.4.0-88.gitd5e7800.el7 will be erased
--> Finished Dependency Resolution

* After unstalling Kimchi
[root@rhel7-vm ~]# find / -name kimchi
/etc/kimchi
[root@rhel7-vm ~]# ls /etc/kimchi/
kimchi-cert.pem  kimchi-key.pem  nginx_kimchi.conf

**Comment by cd1** [comment]
Isn't this a duplicate of #496?

**Comment by alinefm** [comment]
@cd1 We can consider it as duplicated of #496 and update the bug history.
