### ISSUE TITLE
nginx configuration file should be installed under /etc/nginx/conf.d/

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#616]
The nginx configuration is being installed under /etc/kimchi/nginx_kimchi.conf but it should be under nginx directory (/etc/nginx/conf.d/) as kimchi.conf

**Comment by jrziviani** [comment]
Sent patch '[PATCH] Move kimchi nginx config file to nginx default directory.'

**Comment by alinefm** [comment]
Fixed by fde36c020fb787c3b36339635c7991ff3e2cab47
