### ISSUE TITLE
Unable to edit repository

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#617]
1. Select an existing repository to edit it
2. Do not change any information and select "Save"

Expected behavior:
The information is saved.

If the repository is based on mirrorlist, the following error is displayed:
KCHREPOS0002E: Repository URL must be an http://, ftp:// or file:// URL."

If it is based on baseurl, the error is:
"KCHUTILS0001E: Invalid URI https://rhn.linux.ibm.com/XMLRPC/GET-REQ/rhel-x86_64-server-optional-7"

Those behaviors were identified on RHEL 7.1

**Comment by alinefm** [comment]
On a quick check on backend code (src/kimchi/repositories.py) I found the problem is because we aren't considering the "baseurl" as an empty string.

    def updateRepo(self, repo_id, params):                                      
        (...)
        baseurl = params.get('baseurl', None)                                   
        mirrorlist = config.get('mirrorlist', None)                             
                                                                                
        if baseurl is not None:                                                 
            validate_repo_url(baseurl)                                          
            entry.baseurl = baseurl                                             
                                                                                
        if mirrorlist == '':                                                    
            mirrorlist = None                                                   
                                                                                
        if mirrorlist is not None:                                              
            validate_repo_url(mirrorlist)                                       
        (...)
            entry.mirrorlist = mirrorlist

**Comment by cd1** [comment]
This scenario has already been reported by issue #519 (which is also related to issue #461).

**Comment by alinefm** [comment]
@cd1 This problem is not related to the metalink support.
As I said in the comment #2, the problem happens because we are not assuming the baseurl can be an empty string

**Comment by alinefm** [comment]
But I agree it is the same behavior reported by issue #519 
As this one has more details about the root cause, I'd say to close #519

**Comment by alinefm** [comment]
Patch to fix the base URL issue was sent to ML: [PATCH] Fix issue #617: Base URL may be an empty string when updating YUM repo

I am working on URL validation problem and will send a patch soon.

**Comment by cd1** [comment]
Fixed by 2cf3920.
