### ISSUE TITLE
Unable to check packages update progress after switching tabs

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#618]
1. Start packages update on Tab host
2. Progress will be displayed in the box
3. Switch to Guests tab
4. Go back to Host tab

Expected result
Conitnue to be able to get the packages update progress

Actual result
![4918f5b2a0e65851](https://cloud.githubusercontent.com/assets/4921718/6671667/a0afbc88-cbe5-11e4-981f-be1ead559754.jpg)

**Comment by cd1** [comment]
The update operation has a corresponding Task which can be tracked even after changing tabs, so this issue can be fixed only by updating the UI.

**Comment by alinefm** [comment]
Fixed by e1aab0da65f7aa8ee97540ae1698512376bd4f25, baa7cce28116401c3f7aac4f8ef57fa2f4c433ac, 35e33d8e58c805d36f81bd6d605f64de3e719aa4, b2f73636e7353551a870ff9584ec199c4b92ff8d
