### ISSUE TITLE
RHEL 7.1: Unable to create bridged VLAN network

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#619]
1. Make sure NetworkManager service is running
2. Try to create a bridged VLAN network
3. An error will be displayed and the network will not be created.

internal error: failed to create (start) interface kbeth0-203: failed to execute external program - Running 'ifup eth0.203' failed with exit code 4: Error: Connection activation failed: Master connection not found or invalid\n: internal error: failed to create (start) interface kbeth0-203: failed to execute external program - Running 'ifup eth0.203' failed with exit code 4: Error: Connection activation failed: Master connection not found or invalid

When trying to manually start up the bridge I got the same error:
    [root@rhel7-vm ~]# ifup eth0.203
    Error: Connection activation failed: Master connection not found or invalid

After some investigation, I identified it is because of NetworkManager.
If you edit the /etc/sysconfig/network-scripts/ifcfg-\<bridge-name\> and add "NM_CONTROLLED=no"
you will be able to start up the bridge.

You can also stop the NetworkManager service to avoid this error.

But we need to identify a way to make Kimchi automatically deals with it and do not block the bridged VLAN network creation when NetworkManager is running.

**Comment by alinefm** [comment]
For reference: http://wiki.libvirt.org/page/Networking#Disabling_NetworkManager

**Comment by nerijus** [comment]
NetworkManager supports creating bridges.

**Comment by jrziviani** [comment]
Hello, I'll investigate this issue.

**Comment by jrziviani** [comment]
Sent a patch [PATCH V2 0/2] Warn users about NetworkManager instability

**Comment by ramonmedeiros** [comment]
Hi @cd1,

can we close this bug since ziviani's patch was accepted?

**Comment by cd1** [comment]
What is the commit ID which fixes this issue?

**Comment by jrziviani** [comment]
16a25ce1f3fed69851cf9fdba1c3eda561b7ae56 and 69af91de73a90cbd1ad606916cb38f33d875ca83

**Comment by cd1** [comment]
Issue fixed by the commits above.
