### ISSUE TITLE
error while creating logical storage pool

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#623]
![error-logical](https://cloud.githubusercontent.com/assets/4928887/6683708/7c59d9d8-ccc4-11e4-971f-9c284fd1284f.png)

**Comment by cd1** [comment]
Could you provide more details on how this issue happens? Does it happen every time you select "LOGICAL" as the storage pool type? Do you have any empty disks on your system? What OS are you using?

**Comment by lvroyce** [comment]
I'm on Ubuntu 14.04, nested kvm with one free disk, this error happens every time.

**Comment by cd1** [comment]
Could you try to reproduce this issue on Ubuntu 14.10, which is the latest version of that distro?

**Comment by lvroyce** [comment]
Patch sent: Issue #623: Fix mismatch in host device details query

**Comment by lvroyce** [comment]
This patch is because my swap is built on a LV, and Ubuntu names an LV as "data_lv (dm-1)" in command "lsblk". Kimchi chose to strip "(dm-1)" part in device list to make device names short and clean. But in device detail info query, stripped name "data_lv" does not match "data_lv (dm-1)".
