### ISSUE TITLE
UI: Storage sub-tab in template edit tab does not reflex ISCSI storage volume change 

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#627]
##  Description
When editing a template to use ISCSI storage volume, if change to choose one volume to another, "disk size" column does not reflex this change.

##  Reproduce
1. Prepare an ISCSI target with two LUN of different size. (in my case one 3G, another 100M)
1. Create a storage pool from this ISCSI target
1. Edit a previous template from using dir storage pool to use ISCSI pool
1. Try two ISCSI LUN respectively, you will find "disk size column" does not change even if you changed LUN volume (in my case disk size is always 3G even if I changed to use 100M volume)

**Comment by alinefm** [comment]
Fixed by 99dc469cdcb4860bf173713f1ceac5e1432a1c40
