### ISSUE TITLE
Storage volume ref_cnt is not updated after vm clone

### ISSUE THREAD

**Issue by lvroyce** [kimchi-project/kimchi#628]
## Description
After clone a vm from another, disk's ref_cnt of cloned vm remains to be 0.

## Reproduce
1. Create a vm
1. Clone a vm from this created vm
1. Trying add storage volume to this cloned vm, you will see the cloned disk of this vm listed because of the reference count is 0.

**Comment by cd1** [comment]
Fixed by 8c4386c58fb313acd6751e95a28e01459ee8f3df.
