### ISSUE TITLE
test_get_hostinfo fails on RHEL 7.1

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#631]
The test function `test_model.ModelTests.test_get_hostinfo` fails when running on RHEL 7.1.

I'm running Kimchi from commit 1c716c698bb9cad449ce8891ac567ee959350aa9.

## How to reproduce ##

1. Install Kimchi.
2. Run `sudo ./run_tests.sh test_model.ModelTests.test_get_hostinfo` from the directory `tests`.

## Expected behavior ##

The test executed on step (2) should complete successfully.

## Actual behavior ##

The test executed on step (2) fails with the following message:

```
======================================================================
ERROR: test_get_hostinfo (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 1038, in test_get_hostinfo
    info = inst.host_lookup()
  File "/home/kimchi/kimchi/src/kimchi/model/host.py", line 113, in lookup
    cpus = psutil._psplatform.get_num_cpus()
AttributeError: 'module' object has no attribute 'get_num_cpus'
```

**Comment by jrziviani** [comment]
I'm investigating this issue

**Comment by jrziviani** [comment]
Hello!

Sorry, I couldn't reproduce the error with RHEL7.1.

**Comment by cd1** [comment]
Oh, neither can I anymore :worried:

As the issue isn't reproducible anymore, I'll close it.
