### ISSUE TITLE
Unable to connect from non local host

### ISSUE THREAD

**Issue by kenthinson** [kimchi-project/kimchi#632]
Hello I installed on ubuntu using this websites deb and guide.
http://kimchi-project.github.io/kimchi/downloads/
I am able to connect from localhost:8001
I cannot connect from other ip addresses on my local network.
How can i allow this?

**Comment by cd1** [comment]
It looks like you need to setup your firewall in order to allow remote connections to Kimchi.

Have you tried the commands described in [README](docs/README.md)? Look for the section  __Getting Started__ > __Run__ in that file.

**Comment by alinefm** [comment]
Closing due inactivity and as no one else could reproduce it.
Please, reopen if needed.
