### ISSUE TITLE
Cannot create template from local cdrom ISO

### ISSUE THREAD

**Issue by scotthain** [kimchi-project/kimchi#635]
Hello, I am trying to use the api to create a template and having some issues. I am able to authenticate and list (GET) the /templates endpoint, but when I try to POST to, I get an error.

Here is my json payload that I am posting:
```json
  {
    "cpus":1,
    "cpu_info":{},
    "graphics":{
      "type":"vnc",
      "listen":"127.0.0.1"
    },
    "cdrom":"/var/lib/kimchi/isos/ubuntu-14.04.2-server-amd64.iso",
    "networks":[
      "default"
    ],
    "icon":"images/icon-ubuntu.png",
    "os_distro":"ubuntu",
    "name":"ubuntu1404",
    "disks":[
      {
        "index":0,
        "size":10
      }
    ],
    "invalid":{},
    "os_version":"14.04",
    "storagepool":"/storagepools/default",
    "memory":512,
    "folder":[]
  }
```
The response is:
```json
{
  "reason":"KCHTMPL0016E: Specify an ISO image as CDROM or a base image to create a template",
  "code":"400 Bad Request"
}
```
I have created the same template via the UI and it seems to work there.

Thank you!

**Comment by cd1** [comment]
That error message should be returned when you don't specify "cdrom" or "disk/base" in your template, but we can see that you are specifying "cdrom", so I don't know why you're hitting that error. However, even if we've got past it, you'd hit another error later: some of those fields you're specifying (e.g. "invalid") cannot be used when creating a template; they only exist when you're querying its info. I guess you've created a template, then you've sent "GET /templates/\<your-template\>" and then you've tried to create the same template with the same info. But that shouldn't work, some fields returned by "GET /templates/\<your-template\>" are meant to be GETtable only, not POSTable. Take a look at [this file](https://github.com/kimchi-project/kimchi/blob/master/docs/API.md#collection-templates) for more information on the parameters you should use when sending REST commands.

Also, most of the other fields have default values, so I suggest you not to specify them - it keeps your commands cleaner and less error prone. For example, "os_distro" and "os_version" are detected automatically by Kimchi based on the ISO image specified in "cdrom".

So I'd like you to try creating that template using only the values you really need to specify:

```json
{
  "name": "ubuntu1404",
  "cdrom": "/var/lib/kimchi/isos/ubuntu-14.04.2-server-amd64.iso",
  "memory": 512
}
```

And let us know if it works. I really don't know why you're having that error above (KCHTMPL0016E) when you did specify "cdrom" but I expect your command will work if you use less parameters.

By the way, which operating system are you using? What version of Kimchi are you running?

**Comment by scotthain** [comment]
You're right about trying to build it from the results of the GET - I hadn't even thought of that! I had a few tests set up with minimal data with no success.

With the data you've provided, I receive the same error. There are no errors in the /var/cache/kimchi/kimchi-error.log file and /v/c/k/kimchi-access.log has only the connection:
192.168.101.2 - - [27/Apr/2015:17:07:50] "POST /templates HTTP/1.0" 400 513 "" "Ruby"
192.168.101.2 - - [27/Apr/2015:17:07:50] "POST /templates HTTP/1.0" 400 513 "" "Ruby"

(fyi I am querying through a Ruby application, as you can see).

I am running kimchi master (built from source) on Centos 6.6.

Thanks for your help!

**Comment by scotthain** [comment]
I just spun up an Ubuntu 14.04 machine running the same setup - same result. Just another data point for you!

**Comment by scotthain** [comment]
@cd1 I figured it out! The REST client framework I was using in Ruby was actually wrapping the payload in [ ] as opposed to having it be a single json element.

I'm wondering if the incoming json should be validated? (it probably is already but I am not seeing it in the code)

Either way my issue is resolved, user error! :) Thanks!

**Comment by cd1** [comment]
The incoming JSON _is_ validated by Kimchi. The file src/kimchi/API.json contains validation rules according to the Python module `jsonschema.Draft3Validator`. But apparently it doesn't check whether the payload comes as an array instead of as a map :sweat_smile: I'll take a look that to try to include that kind of validation as well.

Thanks for the update, Scott, and I'm glad your issue has been resolved!
