### ISSUE TITLE
Can't login with FQDN

### ISSUE THREAD

**Issue by jcapik** [kimchi-project/kimchi#636]
When connecting to the web UI with the server FQDN, the login fails with no error. When connecting with short name and specifying the rest of the domain name in search in the /etc/resolv.conf file -OR- when using the IP address, it works correctly. Even Firebug doesn't show any errors. I experience the issue only with Fedora running on PPC64 hosts. I was unable to reproduce the issue on x86_64, but that could be caused by differences in the FQDN assigned to the machines. The issue doesn't appear with older version of kimchi running on PowerKVM.

Failing combination:
Fedora release 22 (Twenty Two)
kimchi-1.4.1-3.fc22.noarch

**Comment by cd1** [comment]
We haven't yet tested Kimchi on non-released distros like Fedora 22. [By the time Fedora 22 is released](https://fedoraproject.org/wiki/Releases/22/Schedule), we'll start focusing on that distro.

Can you make sure Fedora 21 + Kimchi is a failing combination as well? Or does it only happen on Fedora 22?

**Comment by jcapik** [comment]
Hello Crístian.

Fedora 22 is Beta RC3 now. That means it's almost final
and we expect only minor changes. It's well installable
and can be used for tests without worries.
Anyway, I'm burning F21 and gonna test shortly.

Jaromir.

--
Jaromir Capik
Red Hat Czech, s.r.o.
Software Engineer / Secondary Arch

Email: jcapik@redhat.com
Web: www.cz.redhat.com
Red Hat Czech s.r.o., Purkynova 99/71, 612 45, Brno, Czech Republic
IC: 27690016 


----- Original Message -----

**Comment by jcapik** [comment]
I just tested F21 with kimchi-1.4.1-1.fc21 and the FQDN issue is not present.

**Comment by alinefm** [comment]
@jcapik Were you able to confirm that issue on Fedora 22?

**Comment by jcapik** [comment]
> Subject: Re: [kimchi] Can't login with FQDN (#636)
> 
> @jcapik Were you able to confirm that issue on Fedora 22?

The host is currently running F22 and the issue is still present.

Jaromir.

**Comment by jcapik** [comment]
> @jcapik Were you able to confirm that issue on Fedora 22?

After installing the latest F22 updates, the issue is gone.

**Comment by alinefm** [comment]
Closing based on last comment.
