### ISSUE TITLE
ImportError: No module named configobj

### ISSUE THREAD

**Issue by la0wei** [kimchi-project/kimchi#638]
root@debian8:~/kimchi# kimchid --host=0.0.0.0
Traceback (most recent call last):
  File "/usr/bin/kimchid", line 28, in <module>
    import kimchi.server
  File "/usr/lib/python2.7/dist-packages/kimchi/server.py", line 29, in <module>
    from kimchi import mockmodel
  File "/usr/lib/python2.7/dist-packages/kimchi/mockmodel.py", line 33, in <module>
    from kimchi import osinfo
  File "/usr/lib/python2.7/dist-packages/kimchi/osinfo.py", line 25, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj

**Comment by cd1** [comment]
The module `configobj` is provided by the package `python-configobj`. How did you install Kimchi? What version are you running?

As a quick workaround, you can run:

```
$ sudo apt-get install -y python-configobj
```

And then try running Kimchi again. But I'd like to investigate more on why this has happened.

**Comment by scotthain** [comment]
I'm seeing the same issue running from master right now (on Centos 6.6)

**Comment by cd1** [comment]
Could you check if you have `python-configobj` installed in your system?

```
$ rpm -qa | grep python-configobj
```

What's the output of the command above?

**Comment by scotthain** [comment]
Ahhh that's it - I didn't notice the docs had been updated! (I was still using the older base package list) Thanks @cd1!

**Comment by cd1** [comment]
You're welcome!

If you you're running Kimchi from the Git repository, you need to keep an eye on docs/README.md to make sure you're following our latest recommendations (e.g. installing all the required dependencies). That file changes constantly, a `git pull` can always change it. If you're running Kimchi from a binary package, however (e.g. .deb, .rpm), the package itself should pull the dependencies, even if new ones come up.

**Comment by la0wei** [comment]
I'm sorry,I just copied the script in your project main page,but I don't know why it's not installed.
my os is  debian 8 64bit.Linux debian8 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

Many thanks
