### ISSUE TITLE
Connect to guest spawns pop-up; is blocked in any modern browser

### ISSUE THREAD

**Issue by jimsalterjrs** [kimchi-project/kimchi#641]
Ubuntu 14.04-LTS.  Kimchi loads, runs, and shows my VMs - including the screenshots of them on the Kimchi page - but when I click "Action" and "Connect", nothing happens at all.  This is the behavior whether the guest is using VNC or using spice.

**Comment by jimsalterjrs** [comment]
argh. pop-up blocking.

Guys, can we please NOT try to open the console as a pop-up?  Seriously?  That's just a terrible, TERRIBLE idea in the modern internet.

With pop-up blocking disabled, connect to guest works.

**Comment by cd1** [comment]
This issue is a duplicate of #393.
