### ISSUE TITLE
Service not created when building from source

### ISSUE THREAD

**Issue by scotthain** [kimchi-project/kimchi#643]
Hallo! This is probably user error, but I saw https://github.com/kimchi-project/kimchi/issues/602 and figured it might be related...

Here's my setup:
Centos 7 fresh install
building kimchi from source, off tag 'kimchi-1.2.0' (I have reasons! :) )
Installed the pre-req packages

Here's a gist of running the install steps: https://gist.github.com/scotthain/6d2d5c6dd93e3a498ed7

Not sure if there's some step that should be documented or if I'm just doing it wrong.

Thanks and keep up the great work!

**Comment by cd1** [comment]
The service `kimchid` doesn't seem to be installed when you run `sudo make install`. As a workaround for now, you can start the service manually by typing the following command from the Kimchi source directory:

```
sudo src/kimchid
```

In the meantime, we'll work on this issue and fix it.

Thanks for reporting it!

**Comment by scotthain** [comment]
Sweet that is how I've been running it at the moment. Thanks again!

**Comment by ramonmedeiros** [comment]
Just sent the patch. I will advise when it's merged

**Comment by cd1** [comment]
Fixed by 04d2953008523ba56e4fc34b0d3e1e083708753a.
