### ISSUE TITLE
MAC address is not displayed when a NIC is added

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#645]
When a network interface is added to a VM (cold- or hotplugged) via the UI, the interface entry in the dialog is blank and doesn't contain the MAC address. Closing and reopening the dialog correctly displays the MAC address.

I'm running Kimchi 82d4308c29af5b9e6a2d81c006b131f47618a887 on Fedora 21, Chrome 43.0.2357.65 (64-bit).

## How to reproduce ##

1. Install and launch Kimchi.
2. On the tab "Guests", select an existing VM and click on "Edit" > "Interfaces".
3. Click on the button "+".
4. Click on the floppy disk button.

## Actual behavior ##

After step (4), the new NIC is correctly added to the VM but its MAC address is blank.

## Expected behavior ##

After step (4), the new NIC's MAC address should be displayed on its appropriate column.

**Comment by jrziviani** [comment]
Hello! Please, test with https://github.com/kimchi-project/kimchi/commit/34634e9839fd7d18959b2658bdc825095040bc11 (or newer).

**Comment by cd1** [comment]
It seems to be fixed now. Thanks!

Fixed by 34634e9.
