### ISSUE TITLE
Error message in SPICE JS client

### ISSUE THREAD

**Issue by modir** [kimchi-project/kimchi#646]
I just updated to the newest version of kimchi (master as of 27.5) and now I have the following error message whenever I want to connect to a console:

ReferenceError: SpiceMainConn is not defined

Interestingly the small preview windows show correctly the console. So it looks like only the full screen has an issue.

This is the URL which gets opened:

/spice_auto.html?port=64667&listen=1.1.1.1&token=cy1wYXJpLXNlYWZpbGUwMQ&encrypt=1

(I changed the IP address. The rest is the same)

**Comment by cd1** [comment]
What distro are you using? I'm also running the latest version of Kimchi on Fedora 22 and I can open the SPICE client correctly.

Do you have the package `spice-html5` installed on your system?

**Comment by modir** [comment]
It is CentOS7. The strange thing is that it worked a month ago with the older version of kimchi.

And yes, this was the problem. I installed now the package and now it works again. Thanks.

**Comment by cd1** [comment]
Thanks for the update!

A few months ago, we had the code for VNC and SPICE clients embedded on Kimchi, but then we decided to use the system packages instead of shipping them with us. So maybe that's why you had it working before and now it didn't... But I'm glad you solved it now.
