### ISSUE TITLE
Error when creating snapshots: "unable to find kvm-img or qemu-img"

### ISSUE THREAD

**Issue by rdd2** [kimchi-project/kimchi#648]
Hi there, 

when I try to create a snapshot a red error message pops up at the to of the screen:

Unexpected exception: KCHSNAP0002E: Unable to create snapshot '1432829494' on virtual machine 'ubuntu'. Details: internal error: unable to find kvm-img or qemu-img

Host is Ubuntu 14.04 and i can call qemu-img from the command line. 

Any pointers would be appreciated.

**Comment by alinefm** [comment]
Hi @rdd2! We usually test Kimchi in the latest Ubuntu version, ie, 15.04.
Have you encountered the same issue there?

**Comment by alinefm** [comment]
I will close this issue due inactivity. Please, reopen if the problem persists.
