### ISSUE TITLE
Windows guests - default mouse type causing problems

### ISSUE THREAD

**Issue by KingDaveRa** [kimchi-project/kimchi#651]
Hi,

By default Kimchi (or possibly KVM, I'm new to both!) creates a VM with an input type of PS/2 Mouse. This will work, but it leads to the dreaded offset problem whereby the VNC session pointer, and my local pointer don't align at all. This makes controlling the VM very hard. To resolve this, I've been manually dropping to virsh and editing the VM's config to add:

`<input type='mouse' bus='ps2'/>`

This then makes it work. Can this be provided as an option somewhere?

**Comment by cd1** [comment]
Which Windows version are you using on your guest?

**Comment by KingDaveRa** [comment]
I've tried it with XP and 2012 Server R2. Googling around, I found quite a few people with the same issue.

I've also just realised my original post is wrong, I'm actually adding:

`<input type='tablet' bus='usb'/>`

Sorry for confusing the issue!
