### ISSUE TITLE
"make rpm" requests authentication with non-root

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#653]
When running `make rpm` with a non-root user, the script prompts for an authentication because of something related to systemd. When running the same command as root, however, everything works.

I'm running Fedora 22, Kimchi c074f604143168454bfc3dd0009640b03a4b5518.

## How to reproduce ##

1. Clone Kimchi to a new directory and install its dependencies.
2. Run `./autogen.sh`.
3. Run `make rpm`.

Make sure you're logged in as a non-root user.

## Actual behavior ##

After step (3), the Makefile prompts for an authentication. Here is the end of the command output:

```
[...]
make[3]: Entering directory '/home/kimchi/kimchi/rpm/BUILD/kimchi-1.4.1'
make[3]: Nothing to be done for 'install-exec-am'.
/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/kimchid.service': Permission denied
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: Kimchi Test (kimchi)
Password: Failed to execute operation: Connection timed out
Makefile:991: recipe for target 'install-data-local' failed
make[3]: *** [install-data-local] Error 1
make[3]: Leaving directory '/home/kimchi/kimchi/rpm/BUILD/kimchi-1.4.1'
Makefile:803: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/kimchi/kimchi/rpm/BUILD/kimchi-1.4.1'
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
Makefile:501: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/kimchi/kimchi/rpm/BUILD/kimchi-1.4.1'
error: Bad exit status from /var/tmp/rpm-tmp.35YWpT (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.35YWpT (%install)
Makefile:972: recipe for target 'rpm' failed
make: *** [rpm] Error 1
```

`kimchi` is the username I'm logged in, and `Kimchi Test` is the user's full name.

## Expected behavior ##

After step (3), an RPM should be generated successfully, even with a non-root user.

**Comment by ramonmedeiros** [comment]
Please, assign to me

**Comment by ramonmedeiros** [comment]
Hi,

this bug was introduced on 04d2953008523ba56e4fc34b0d3e1e083708753a, but, i'm proposing a solution on patch http://lists.ovirt.org/pipermail/kimchi-devel/2015-June/010746.html.

I will notify you when it's done.
