### ISSUE TITLE
Test "test_storagevolume_action" fails

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#655]
The function `test_storagevolume_action` fails when running `sudo make check` or when running it directly.

I'm using Fedora 22, Kimchi 392feb9775a7e539b611ac2d774fa4a47013beae.

## How to reproduce ##

1. Install Kimchi.
2. Go to the directory `tests`.
3. Type the following command:

```
$ sudo ./run_tests.sh test_model_storagevolume.StorageVolumeTests.test_storagevolume_action
```

## Actual behavior ##

After step (3), the following output is displayed:

```
======================================================================
FAIL: test_storagevolume_action (test_model_storagevolume.StorageVolumeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model_storagevolume.py", line 269, in test_storagevolume_action
    _do_volume_test(self, model, host, ssl_port, 'default')
  File "test_model_storagevolume.py", line 114, in _do_volume_test
    self.assertEquals(500, resp.status)
AssertionError: 500 != 200

----------------------------------------------------------------------
```

## Expected behavior ##

After step (3), the test function should complete successfully.

**Comment by ramonmedeiros** [comment]
Running on Fedora 21, HEAD f8a5bb5ce92ea13bc6de13e2e095ba86be76a6a3 , the error is different:


======================================================================
FAIL: test_storagevolume_action (test_model_storagevolume.StorageVolumeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model_storagevolume.py", line 269, in test_storagevolume_action
    _do_volume_test(self, model, host, ssl_port, 'default')
  File "test_model_storagevolume.py", line 120, in _do_volume_test
    self.assertEquals(0, storagevolume['allocation'])
AssertionError: 0 != 1024

**Comment by alinefm** [comment]
All test cases are passing on Fedora 23.
I will close this issue.
