### ISSUE TITLE
Cannot run yum operations on RHEL 7.1

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#657]
Running kimchi with HEAD c4d040b029dfa7f336b9a4ce8ea91d3d12bb3650 i can't list repositories and install packages.

I can do both operations manually.

**Comment by ramonmedeiros** [comment]
![image](https://cloud.githubusercontent.com/assets/950160/8110294/d2287648-1031-11e5-98ac-fb2cc9311536.png)

**Comment by danielhb** [comment]
Ramon, could you please post the output of the following command:

$ sudo yum check-update -d0

**Comment by ramonmedeiros** [comment]
[root@localhost KIMCHI]# sudo yum check-update -d0

bind-libs-lite.x86_64                                                        32:9.9.4-18.el7_1.1                                                  rhel-x86_64-server-7          
bind-license.noarch                                                          32:9.9.4-18.el7_1.1                                                  rhel-x86_64-server-7          
binutils.x86_64                                                              2.23.52.0.1-30.el7_1.2                                               rhel-x86_64-server-7          
ca-certificates.noarch                                                       2015.2.4-70.0.el7_1                                                  rhel-x86_64-server-7          
dnsmasq.x86_64                                                               2.66-13.el7_1                                                        rhel-x86_64-server-7          
dracut.x86_64                                                                033-241.el7_1.1                                                      rhel-x86_64-server-7          
dracut-config-rescue.x86_64                                                  033-241.el7_1.1                                                      rhel-x86_64-server-7          
dracut-network.x86_64                                                        033-241.el7_1.1                                                      rhel-x86_64-server-7          
freetype.x86_64                                                              2.4.11-10.el7_1.1                                                    rhel-x86_64-server-7          
glusterfs.x86_64                                                             3.6.0.53-1.el7                                                       rhel-x86_64-server-rh-common-7
glusterfs-api.x86_64                                                         3.6.0.53-1.el7                                                       rhel-x86_64-server-rh-common-7
glusterfs-libs.x86_64                                                        3.6.0.53-1.el7                                                       rhel-x86_64-server-rh-common-7
hwdata.x86_64                                                                0.252-7.8.el7_1                                                      rhel-x86_64-server-7          
kernel.x86_64                                                                3.10.0-229.4.2.el7                                                   rhel-x86_64-server-7          
kernel-tools.x86_64                                                          3.10.0-229.4.2.el7                                                   rhel-x86_64-server-7          
kernel-tools-libs.x86_64                                                     3.10.0-229.4.2.el7                                                   rhel-x86_64-server-7          
kexec-tools.x86_64                                                           2.0.7-19.el7_1.2                                                     rhel-x86_64-server-7          
libblkid.x86_64                                                              2.23.2-22.el7_1                                                      rhel-x86_64-server-7          
libgcrypt.x86_64                                                             1.5.3-12.el7_1.1                                                     rhel-x86_64-server-7          
libgudev1.x86_64                                                             208-20.el7_1.3                                                       rhel-x86_64-server-7          
libmount.x86_64                                                              2.23.2-22.el7_1                                                      rhel-x86_64-server-7          
libpcap.x86_64                                                               14:1.5.3-4.el7_1.2                                                   rhel-x86_64-server-7          
librados2.x86_64                                                             1:0.80.8-7.el7cp                                                     rhel-x86_64-server-rh-common-7
librbd1.x86_64                                                               1:0.80.8-7.el7cp                                                     rhel-x86_64-server-rh-common-7
libuuid.x86_64                                                               2.23.2-22.el7_1                                                      rhel-x86_64-server-7          
libxml2.x86_64                                                               2.9.1-5.el7_1.2                                                      rhel-x86_64-server-7          
libxml2-python.x86_64                                                        2.9.1-5.el7_1.2                                                      rhel-x86_64-server-7          
nspr.x86_64                                                                  4.10.8-1.el7_1                                                       rhel-x86_64-server-7          
nss.x86_64                                                                   3.18.0-2.2.el7_1                                                     rhel-x86_64-server-7          
nss-sysinit.x86_64                                                           3.18.0-2.2.el7_1                                                     rhel-x86_64-server-7          
nss-tools.x86_64                                                             3.18.0-2.2.el7_1                                                     rhel-x86_64-server-7          
nss-util.x86_64                                                              3.18.0-1.el7_1                                                       rhel-x86_64-server-7          
openssh.x86_64                                                               6.6.1p1-12.el7_1                                                     rhel-x86_64-server-7          
openssh-clients.x86_64                                                       6.6.1p1-12.el7_1                                                     rhel-x86_64-server-7          
openssh-server.x86_64                                                        6.6.1p1-12.el7_1                                                     rhel-x86_64-server-7          
openssl.x86_64                                                               1:1.0.1e-42.el7_1.6                                                  rhel-x86_64-server-7          
openssl-libs.x86_64                                                          1:1.0.1e-42.el7_1.6                                                  rhel-x86_64-server-7          
python-six.noarch                                                            1.6.1-1.el7                                                          rhel-x86_64-server-7-ost-5    
selinux-policy.noarch                                                        3.13.1-23.el7_1.7                                                    rhel-x86_64-server-7          
selinux-policy-targeted.noarch                                               3.13.1-23.el7_1.7                                                    rhel-x86_64-server-7          
systemd.x86_64                                                               208-20.el7_1.3                                                       rhel-x86_64-server-7          
systemd-libs.x86_64                                                          208-20.el7_1.3                                                       rhel-x86_64-server-7          
systemd-sysv.x86_64                                                          208-20.el7_1.3                                                       rhel-x86_64-server-7          
tzdata.noarch                                                                2015d-1.el7                                                          rhel-x86_64-server-7          
util-linux.x86_64                                                            2.23.2-22.el7_1                                                      rhel-x86_64-server-7          
Obsoleting Packages
qemu-img-rhev.x86_64                                                         10:2.1.2-23.el7_1.3                                                  rhel-x86_64-server-7-ost-5    
    qemu-img.x86_64                                                          10:1.5.3-86.el7_1.2                                                  @rhel-x86_64-server-7         
qemu-kvm-common-rhev.x86_64                                                  10:2.1.2-23.el7_1.3                                                  rhel-x86_64-server-7-ost-5    
    qemu-kvm-common.x86_64                                                   10:1.5.3-86.el7_1.2                                                  @rhel-x86_64-server-7         
qemu-kvm-rhev.x86_64                                                         10:2.1.2-23.el7_1.3                                                  rhel-x86_64-server-7-ost-5    
    qemu-kvm.x86_64                                                          10:1.5.3-86.el7_1.2                                                  @rhel-x86_64-server-7

**Comment by danielhb** [comment]
Ramon, please check https://github.com/kimchi-project/kimchi/issues/660 to track
the other issue you've found
