### ISSUE TITLE
RHEL 7.1 does not translate buttons 

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#661]
How to reproduce:

1) Go to login page on a RHEL 7.1 host

2) Change language

3) Buttons and Tabs will not change. Only errors message will be translated.

**Comment by cd1** [comment]
Could you provide more details about your environment and test case? What browser are you running? Which language did you choose? Which strings remained in English, and which error messages were translated to the language you chose?

I have Kimchi 30ceeea32b3913e09cb7082c4d90022a47594d01 running on RHEL 7.1 and I'm able to change the web UI language perfectly. I'm using Firefox 38.0, I changed the language to "Português (Brasil)", the screen was refreshed and everything from then on was in Portuguese. I was able to login, and every text in every tab was in Portuguese. I also tried different languages and different browsers.

**Comment by ramonmedeiros** [comment]
Hi Cristian,

I was running this VM in my laptop, Fedora 21, using Google Chrome Version 43.0.2357.65. I changed to Portugues and Chinese. Both got the same error described above.

**Comment by alinefm** [comment]
Hi @ramonmedeiros, could you provide a screenshot?

I also tried RHEL 7.1 with the latest Kimchi and everything translated as expected.

![152ecc3607b2b36d](https://cloud.githubusercontent.com/assets/4921718/8258732/ac2e6c06-168d-11e5-8fb5-b109d8adede7.jpg)

**Comment by ramonmedeiros** [comment]
Hi,

today i ran a git pull in the machine that has this bug, and it was fixed.

I will close this bug
