### ISSUE TITLE
Unable to import Debian 8.1 ppc64el netinst iso

### ISSUE THREAD

**Issue by edechaux** [kimchi-project/kimchi#665]
Hello,

I am getting a `KCHISO0001E` error when I try to import a Debian 8.1.0 ppc64el netinst iso. I tried using local and http import with the same result. The iso checksum is verified.

I really don't know how to debug...

**update** 
1. Tried with ubuntu server 15.04 ppc64el CD, local import succeeded.
2. Tried with debian 8.1 ppc64el CD1 (instead of netinst), import still fails.

**update 2**
1. Also fails with the iso DVD. The only difference I can find versus ubuntu is the distribution type and version are not detected. Check screen shot.
![screenshot](https://cloud.githubusercontent.com/assets/6269611/8206850/4b2a5c9e-14fd-11e5-9842-50c3dd1a6980.png)
**update 3**
1. Tried with debian 8.1 powerpc netinstal, local import succeeded, check screenshot.
![capture du 2015-06-17 163003](https://cloud.githubusercontent.com/assets/6269611/8209695/b36b0dce-150e-11e5-82b3-0f9188875484.png)

**Comment by edechaux** [comment]
Just found a workaround:
1. Create an ubuntu template
2. Instantiate a gest base on previous template without starting it
3. Edit the guest configuration and change the iso image from the sdc unit in the storage tab

**Comment by ramonmedeiros** [comment]
Hi,

this bug was recently fixed in commit: dfb220fc5bfcf5299ca614e1593e73cb43b6d920. This bug affects all debian8 ppc64el ISOs.

Please, patch your system and take a look if it's enough.

Thanks.

**Comment by alinefm** [comment]
Closing based on last comment

**Comment by edechaux** [comment]
Thanks, any idea when this patch will be integrated to PowerKVM ?

**Comment by laggarcia** [comment]
PowerKVM is an IBM product. This is something you need to check with IBM support.
