### ISSUE TITLE
Adding Storage volume on nfs storage pool fails

### ISSUE THREAD

**Issue by pawankg** [kimchi-project/kimchi#666]
Adding Storage volume on nfs storage pool fails

Work Environment:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

Steps to reproduce:
1. Set up and start NFS server on local machine.
2. Go to tab "Storage"
3. Click on + sign in upper right hand corner to add storage pool.
4. Under "Define a new storage pool" menu:
    - Give 'Storage Pool Name' as test_nfs_strgpool.
    - In 'Storage Pool Type', select NFS from drop down menu.
    - In 'NFS Server IP' given NFS server ip as  127.0.0.1
    - In 'NFS path' give path as /var/lib/kimchi/nfs_mount/test1
5. After creation of storage pool, go to Actions -> Add Volume
6. Select Upload a file option and browse the file path on the local machine.
7. UI doesn't show any error and not able to see the volume. Looking at /var/log/kimchi-erro.log I see the following errors:
Operation failed with error "Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kimchi/asynctask.py", line 70, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/dist-packages/kimchi/model/storagevolumes.py", line 151, in _create_volume_with_capacity

    'err': e.get_error_message()})
OperationFailed: KCHVOL0007E: Unable to create storage volume Untitled Document in storage pool <libvirt.virStoragePool object at 0x7f453c5aba90>. Details: Failed to create file '/var/lib/kimchi/nfs_mount/test1/Untitled Document': Operation not permitted"

**Comment by alinefm** [comment]
Hi @pawankg, have you properly configured your NFS server according to instructions at https://github.com/kimchi-project/kimchi/blob/master/docs/README.md#known-issues ?

**Comment by abhiramkulkarni** [comment]
@pawankg 

Also, can you add what type of file is being uploaded for adding storage volume?

**Comment by abhiramkulkarni** [comment]
I can see currently latest version of kimchi is allowing any file type to upload.

**Comment by pawankg** [comment]
Thanks Aline for your input. Following the instructions at above mentioned link resolved the issue.
