### ISSUE TITLE
Possible with apache?

### ISSUE THREAD

**Issue by daniel-lucio** [kimchi-project/kimchi#668]
I am not a python coder, but i was reading some portions of code, and I found it looks for specific nginx files.

**Comment by danielhb** [comment]
Yes, kimchi uses nginx ans a proxy and it sets up nginx configuration files according to the command line options.

**Comment by daniel-lucio** [comment]
Le 24 juin 2015, 15:53:35 Daniel Henrique Barboza a écrit :
> Yes, kimchi uses nginx ans a proxy and it sets up nginx 
configuration files
> according to the command line options.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kimchi-project/kimchi/issues/668#issuecomment-115037517


What is the command line option to start without nginx

LD

**Comment by cd1** [comment]
There's no way of disabling nginx when running Kimchi.

**Comment by cd1** [comment]
This issue is a duplicate of #570.
