### ISSUE TITLE
Guest pause operation

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#675]
OS :- Fedora 21
[root@abhiram kimchi-master]# uname -a
Linux abhiram 3.19.7-200.fc21.x86_64 #1 SMP Thu May 7 22:00:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@abhiram kimchi-master]# 

Operation done:-
1)Create and activate guest
2)When try to pause the guest, the error message is not clear. 
Error messag reads "Nothing matches the given URI"

Can you check if this message is appropriate to the end user?

**Comment by ramonmedeiros** [comment]
I can't reproduce it, can you describe more steps?

**Comment by abhiramkulkarni** [comment]
Sure, ramon, when i tried to reproduce now i do not see pause option only.
Something is wrong in my setup?

![screenshot from 2015-07-03 11 37 37](https://cloud.githubusercontent.com/assets/12495213/8493469/0ceaebc4-2178-11e5-94c9-35ecd87c84a5.png)

If required i can download the kimchi and try again before that you could have a look

**Comment by cd1** [comment]
You seem to be using an older version of Kimchi. Make sure you have Kimchi 1.5 (or newer) installed.

**Comment by abhiramkulkarni** [comment]
I am currently using 1.5.0 version.
[Abhiram@abhiram kimchi-master]$ ls
ABOUT-NLS   autogen.sh      ChangeLog   config.rpath   configure.ac   COPYING       docs     Makefile     mo       po         tests
aclocal.m4  autom4te.cache  config      config.status  contrib        COPYING.ASL2  INSTALL  Makefile.am  NEWS     README.md  ui
AUTHORS     build-aux       config.log  configure      CONTRIBUTE.md  COPYING.LGPL  m4       Makefile.in  plugins  src        VERSION
[Abhiram@abhiram kimchi-master]$ cat VERSION 
1.5.0
a[Abhiram@abhiram kimchi-master]$ 

I can download latest one and try

**Comment by ramonmedeiros** [comment]
Please,

run the lastest kimchi.

**Comment by abhiramkulkarni** [comment]
With the latest version the issue is not reproducing. Closing
