### ISSUE TITLE
Add storage volume is failing for nfs type of storage pool but no error message shown on UI

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#676]
Operating system
==============
[Abhiram@abhiram kimchi]$ uname -a
Linux abhiram 3.19.7-200.fc21.x86_64 #1 SMP Thu May 7 22:00:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[Abhiram@abhiram kimchi]$ 

Kimchi Version
============
[Abhiram@abhiram kimchi-master]$ cat VERSION 
1.5.0

Steps performed.
==============
1)Create a nfs storage pool using the kimchi UI
2)Add storage volume by uploading a file (.txt)
3)Add storage volume is failing and no error message shown in UI.

If i remember correctly in earlier versions of kimchi showed error message saying what all are the formats supported while adding nfs volume.

Exception in kimchi_error.log
=======================
Error in async_task 5 
Error in async_task 5 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kimchi/asynctask.py", line 70, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/site-packages/kimchi/model/storagevolumes.py", line 151, in _create_volume_with_capacity
    'err': e.get_error_message()})
OperationFailed: KCHVOL0007E: Unable to create storage volume README.txt in storage pool <libvirt.virStoragePool object at 0x7f643433ff10>. Details: Failed to create file '/var/lib/kimchi/nfs_mount/nfs/README.txt': Read-only file system

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kimchi/asynctask.py", line 70, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/site-packages/kimchi/model/storagevolumes.py", line 151, in _create_volume_with_capacity
    'err': e.get_error_message()})
OperationFailed: KCHVOL0007E: Unable to create storage volume README.txt in storage pool <libvirt.virStoragePool object at 0x7f643433ff10>. Details: Failed to create file '/var/lib/kimchi/nfs_mount/nfs/README.txt': Read-only file system

**Comment by alinefm** [comment]
Hi @abhiramkulkarni!
Did you follow the instructions on README regarding on how setup the NFS server?
https://github.com/kimchi-project/kimchi/blob/master/docs/README.md#known-issues

Seems the NFS server has read-only permission and so you will not be able to add/remove anything from there.

**Comment by abhiramkulkarni** [comment]
Tried reproducing the issue assiging the correct permissions to nfs mount path. Did not see this issue.
Closing for now.

**Comment by abhiramkulkarni** [comment]
Tried reproducing the issue assiging the correct permissions to nfs mount path. Did not see this issue.
Closing for now.
