### ISSUE TITLE
Delete volume feature

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#677]
There is addvolume feature available to storage pools. But i do not see delete volume feature available for storage pools. Is there any specific reason for not having this?

I tried to deactivate storage pool and activate storage pool just to see if volume gets deleted, but its available. I expect volume should not be deleted by activating and deactivating the storage pool.  

So was trying to understand user will not have any scenario to delete volume?

**Comment by cd1** [comment]
There's no specific reason to why this feature isn't implemented, and I agree it should be.

**Comment by alinefm** [comment]
Hi @abhiramkulkarni 

The storage volume delete functionality is already implemented on backend. We are waiting on UI to have it announcement.
We have a specific issue to cover storage volume management UI (#833). I will close this issue by now.
