### ISSUE TITLE
Getting error in logs rc: 1 error:  returned from cmd: ldd /usr/bin/kvm-spice

### ISSUE THREAD

**Issue by rahulmr** [kimchi-project/kimchi#683]
I am getting error as below in the logs.

    rc: 1 error:  returned from cmd: ldd /usr/bin/kvm-spice  
    rc: 1 error:  returned from cmd: ldd /usr/bin/kvm-spice  
    Failed to find qemu binary dependencies:  

This happened after `apt-get update` and `apt-get upgrade -y` on ubuntu vivid

Any help or possible way to debug? I have installed qemu 2.3.0

**Comment by alinefm** [comment]
Hi @rahulmr 
In which logs are you seeing those errors?

The binary /usr/bin/kvm-spice is part of qemu-kvm package.

alinefm@alinefm-ThinkPad-T440:~$ sudo dpkg -S /usr/bin/kvm-spice  
qemu-kvm: /usr/bin/kvm-spice

**Comment by alinefm** [comment]
Closing this issue due inactivity.
Please, reopen if needed.
