### ISSUE TITLE
Error for debug report generation for report name containing "_" 

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/kimchi#686]
Error happened when I tried to generate debug report containing "_" in it's name. It's working fine with hyphen,digits.
![debug](https://cloud.githubusercontent.com/assets/13199397/8521530/2d3e7080-2402-11e5-959a-2a0d7d5486a3.png)
![debug generate](https://cloud.githubusercontent.com/assets/13199397/8521543/450556e8-2402-11e5-9ad5-380015cb4987.png)

**Comment by alinefm** [comment]
Debug reports feature is now part of Ginger Base.
And this issue is already reported there: https://github.com/kimchi-project/gingerbase/issues/7

So I am closing this issue.
