### ISSUE TITLE
Getting error for software update

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/kimchi#687]
Got the below error when tried 'Update All' functionality in Host tab from UI.

---> Package perl-version.s390x 3:0.99.07-2.el7 will be installed
--> Processing Dependency: perl(:MODULE_COMPAT_5.16.3) for package: 3:perl-version-0.99.07-2.el7.s390x
---> Package php-process.s390x 0:5.5.12-1.fc20 will be installed
---> Package php-xml.s390x 0:5.5.12-1.fc20 will be installed
---> Package polkit.s390 0:0.112-5.el7 will be installed
--> Processing Dependency: libsystemd-login.so.0 for package: polkit-0.112-5.el7.s390
--> Processing Dependency: libsystemd-login.so.0(LIBSYSTEMD_LOGIN_31) for package: polkit-0.112-5.el7.s390
---> Package python3-libs.s390x 0:3.3.2-19.fc20 will be installed
---> Package xz-libs.s390x 0:5.1.2-8alpha.fc20 will be updated
--> Processing Dependency: xz-libs(s390-64) = 5.1.2-8alpha.fc20 for package: xz-devel-5.1.2-8alpha.fc20.s390x
---> Package xz-libs.s390x 0:5.1.2-8alpha.fc20 will be updated
--> Processing Dependency: xz-libs(s390-64) = 5.1.2-8alpha.fc20 for package: xz-devel-5.1.2-8alpha.fc20.s390x
--> Processing Conflict: generic-logos-17.0.0-5.fc20.noarch conflicts fedora-logos
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: Package: 3:perl-version-0.99.07-2.el7.s390x (rhel7)
           Requires: perl(:MODULE_COMPAT_5.16.3)
           Removing: 4:perl-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               perl(:MODULE_COMPAT_5.16.3)
           Updated By: 4:perl-5.18.2-289.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.2)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
           Available: 4:perl-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               perl(:MODULE_COMPAT_5.16.3)
           Available: 4:perl-5.18.1-288.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
Error: Package: libuser-python-0.60-5.el7.s390x (@rhel7)
           Requires: libuser(s390-64) = 0.60-5.el7
           Removing: libuser-0.60-5.el7.s390x (@RHEL7.0-Server/$releasever)
               libuser(s390-64) = 0.60-5.el7
           Updated By: libuser-0.60-5.el7_0.ibm.1.s390x (frobisher-base)
               libuser(s390-64) = 0.60-5.el7_0.ibm.1
           Available: libuser-0.60-3.fc20.s390x (fc20-base)
               libuser(s390-64) = 0.60-3.fc20
Error: Package: 1:net-snmp-5.7.2-18.el7_0.ibm.1.s390x (frobisher-base)
           Requires: libperl.so()(64bit)
           Removing: 4:perl-libs-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               libperl.so()(64bit)
           Updated By: 4:perl-libs-5.18.2-289.fc20.s390x (fc20-base)
               Not found
           Available: 4:perl-libs-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               libperl.so()(64bit)
           Available: 4:perl-libs-5.18.1-288.fc20.s390 (fc20-base)
               Not found
Error: Package: 1:numpy-1.8.0-4.fc20.s390x (fc20-base)
           Requires: libatlas.so.3()(64bit)
           Available: atlas-3.8.4-10.fc20.s390x (fc20-base)
               libatlas.so.3()(64bit)
           Available: atlas-3.8.4-11.fc20.s390x (fc20-base)
               libatlas.so.3()(64bit)
           Available: atlas-z10-3.8.4-10.fc20.s390x (fc20-base)
               libatlas.so.3()(64bit)
           Available: atlas-z10-3.8.4-11.fc20.s390x (fc20-base)
               libatlas.so.3()(64bit)
           Available: atlas-z196-3.8.4-10.fc20.s390x (fc20-base)
               libatlas.so.3()(64bit)
           Available: atlas-z196-3.8.4-11.fc20.s390x (fc20-base)
               libatlas.so.3()(64bit)
           Removing: atlas-3.10.1-7.el7.s390x (@RHEL7.0-Server/$releasever)
               Not found
           Updated By: atlas-3.10.1-7.el7_0.ibm.1.s390x (frobisher-base)
               Not found
Error: Package: perf-3.10.0-123.13.2.el7_0.ibm.10.s390x (frobisher-base)
           Requires: libperl.so()(64bit)
           Removing: 4:perl-libs-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               libperl.so()(64bit)
           Updated By: 4:perl-libs-5.18.2-289.fc20.s390x (fc20-base)
               Not found
           Available: 4:perl-libs-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               libperl.so()(64bit)
           Available: 4:perl-libs-5.18.1-288.fc20.s390 (fc20-base)
               Not found
Error: Package: udisks2-2.1.2-2.fc19.s390x (installed)
           Requires: libudisks2 = 2.1.2-2.fc19
           Removing: libudisks2-2.1.2-2.fc19.s390x (installed)
               libudisks2 = 2.1.2-2.fc19
           Updated By: libudisks2-2.1.2-5.el7.s390x (rhel7)
               libudisks2 = 2.1.2-5.el7
           Available: libudisks2-2.1.1-1.fc20.s390 (fc20-base)
               libudisks2 = 2.1.1-1.fc20
           Installing: libudisks2-2.1.2-2.fc20.s390 (fc20-base)
               libudisks2 = 2.1.2-2.fc20
Error: Package: 1:numpy-1.8.0-4.fc20.s390x (fc20-base)
           Requires: libptcblas.so.3()(64bit)
           Available: atlas-3.8.4-10.fc20.s390x (fc20-base)
               libptcblas.so.3()(64bit)
           Available: atlas-3.8.4-11.fc20.s390x (fc20-base)
               libptcblas.so.3()(64bit)
           Available: atlas-z10-3.8.4-10.fc20.s390x (fc20-base)
               libptcblas.so.3()(64bit)
           Available: atlas-z10-3.8.4-11.fc20.s390x (fc20-base)
               libptcblas.so.3()(64bit)
           Available: atlas-z196-3.8.4-10.fc20.s390x (fc20-base)
               libptcblas.so.3()(64bit)
           Available: atlas-z196-3.8.4-11.fc20.s390x (fc20-base)
               libptcblas.so.3()(64bit)
           Removing: atlas-3.10.1-7.el7.s390x (@RHEL7.0-Server/$releasever)
               Not found
           Updated By: atlas-3.10.1-7.el7_0.ibm.1.s390x (frobisher-base)
               Not found
Error: Package: perl-Storable-2.45-3.el7_0.ibm.1.s390x (frobisher-base)
           Requires: perl(:MODULE_COMPAT_5.16.3)
           Removing: 4:perl-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               perl(:MODULE_COMPAT_5.16.3)
           Updated By: 4:perl-5.18.2-289.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.2)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
           Available: 4:perl-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               perl(:MODULE_COMPAT_5.16.3)
           Available: 4:perl-5.18.1-288.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
Error: Package: libcom_err-devel-1.42.9-4.el7.s390x (@frobisher-base)
           Requires: libcom_err(s390-64) = 1.42.9-4.el7
           Removing: libcom_err-1.42.9-4.el7.s390x (@RHEL7.0-Server/$releasever)
               libcom_err(s390-64) = 1.42.9-4.el7
           Updated By: libcom_err-1.42.9-4.el7_0.ibm.1.s390x (frobisher-base)
               libcom_err(s390-64) = 1.42.9-4.el7_0.ibm.1
           Available: libcom_err-1.42.8-3.fc20.s390x (fc20-base)
               libcom_err(s390-64) = 1.42.8-3.fc20
Error: Package: 1:perl-Compress-Raw-Zlib-2.061-4.el7_0.ibm.1.s390x (frobisher-base)
           Requires: perl(:MODULE_COMPAT_5.16.3)
           Removing: 4:perl-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               perl(:MODULE_COMPAT_5.16.3)
           Updated By: 4:perl-5.18.2-289.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.2)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
           Available: 4:perl-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               perl(:MODULE_COMPAT_5.16.3)
           Available: 4:perl-5.18.1-288.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
Error: Package: polkit-0.112-5.el7.s390 (rhel7)
           Requires: libsystemd-login.so.0(LIBSYSTEMD_LOGIN_31)
Error: Package: perl-IO-Compress-2.062-2.fc20.noarch (fc20-base)
           Requires: perl(Compress::Raw::Zlib) >= 2.062
           Removing: 1:perl-Compress-Raw-Zlib-2.061-4.el7.s390x (@frobisher-base)
               perl(Compress::Raw::Zlib) = 2.061
           Updated By: 1:perl-Compress-Raw-Zlib-2.061-4.el7_0.ibm.1.s390x (frobisher-base)
               perl(Compress::Raw::Zlib) = 2.061
           Available: perl-Compress-Raw-Zlib-2.062-2.fc20.s390x (fc20-base)
               perl(Compress::Raw::Zlib) = 2.062
Error: Package: brltty-4.5-9.fc20.s390x (fc20-base)
           Requires: libicui18n.so.50()(64bit)
           Removing: libicu-50.1.2-11.el7.s390x (@RHEL7.0-Server/$releasever)
               libicui18n.so.50()(64bit)
           Updated By: libicu-54.1-11.el7_0.ibm.1.s390x (frobisher-base)
              ~libicui18n.so.54()(64bit)
           Available: libicu-50.1.2-10.fc20.s390x (fc20-base)
               libicui18n.so.50()(64bit)
Error: Package: 1:numpy-1.8.0-4.fc20.s390x (fc20-base)
           Requires: libptf77blas.so.3()(64bit)
           Available: atlas-3.8.4-10.fc20.s390x (fc20-base)
               libptf77blas.so.3()(64bit)
           Available: atlas-3.8.4-11.fc20.s390x (fc20-base)
               libptf77blas.so.3()(64bit)
           Available: atlas-z10-3.8.4-10.fc20.s390x (fc20-base)
               libptf77blas.so.3()(64bit)
           Available: atlas-z10-3.8.4-11.fc20.s390x (fc20-base)
               libptf77blas.so.3()(64bit)
           Available: atlas-z196-3.8.4-10.fc20.s390x (fc20-base)
               libptf77blas.so.3()(64bit)
           Available: atlas-z196-3.8.4-11.fc20.s390x (fc20-base)
               libptf77blas.so.3()(64bit)
           Removing: atlas-3.10.1-7.el7.s390x (@RHEL7.0-Server/$releasever)
               Not found
           Updated By: atlas-3.10.1-7.el7_0.ibm.1.s390x (frobisher-base)
               Not found
Error: Package: libverto-devel-0.2.5-4.el7.s390x (@frobisher-base)
           Requires: libverto(s390-64) = 0.2.5-4.el7
           Removing: libverto-0.2.5-4.el7.s390x (@RHEL7.0-Server/$releasever)
               libverto(s390-64) = 0.2.5-4.el7
           Updated By: libverto-0.2.5-4.el7_0.ibm.1.s390x (frobisher-base)
               libverto(s390-64) = 0.2.5-4.el7_0.ibm.1
           Available: libverto-0.2.5-3.fc20.s390x (fc20-base)
               libverto(s390-64) = 0.2.5-3.fc20
Error: Package: 1:net-snmp-agent-libs-5.7.2-18.el7_0.ibm.1.s390x (frobisher-base)
           Requires: libperl.so()(64bit)
           Removing: 4:perl-libs-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               libperl.so()(64bit)
           Updated By: 4:perl-libs-5.18.2-289.fc20.s390x (fc20-base)
               Not found
           Available: 4:perl-libs-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               libperl.so()(64bit)
           Available: 4:perl-libs-5.18.1-288.fc20.s390 (fc20-base)
               Not found
Error: Package: 1:net-snmp-agent-libs-5.7.2-18.el7_0.ibm.1.s390x (frobisher-base)
           Requires: perl(:MODULE_COMPAT_5.16.3)
           Removing: 4:perl-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               perl(:MODULE_COMPAT_5.16.3)
           Updated By: 4:perl-5.18.2-289.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.2)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
           Available: 4:perl-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               perl(:MODULE_COMPAT_5.16.3)
           Available: 4:perl-5.18.1-288.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
Error: Package: ncurses-devel-5.9-13.20130511.el7.s390x (@rhel7)
           Requires: ncurses-libs(s390-64) = 5.9-13.20130511.el7
           Removing: ncurses-libs-5.9-13.20130511.el7.s390x (@RHEL7.0-Server/$releasever)
               ncurses-libs(s390-64) = 5.9-13.20130511.el7
           Updated By: ncurses-libs-5.9-13.20130511.el7_0.ibm.1.s390x (frobisher-base)
               ncurses-libs(s390-64) = 5.9-13.20130511.el7_0.ibm.1
           Available: ncurses-libs-5.9-12.20130511.fc20.s390x (fc20-base)
               ncurses-libs(s390-64) = 5.9-12.20130511.fc20
Error: Package: 4:perl-Time-HiRes-1.9725-3.el7.s390x (rhel7)
           Requires: perl(:MODULE_COMPAT_5.16.3)
           Removing: 4:perl-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               perl(:MODULE_COMPAT_5.16.3)
           Updated By: 4:perl-5.18.2-289.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.2)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
           Available: 4:perl-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               perl(:MODULE_COMPAT_5.16.3)
           Available: 4:perl-5.18.1-288.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
Error: Package: brltty-4.5-9.fc20.s390x (fc20-base)
           Requires: libicudata.so.50()(64bit)
           Removing: libicu-50.1.2-11.el7.s390x (@RHEL7.0-Server/$releasever)
               libicudata.so.50()(64bit)
           Updated By: libicu-54.1-11.el7_0.ibm.1.s390x (frobisher-base)
              ~libicudata.so.54()(64bit)
           Available: libicu-50.1.2-10.fc20.s390x (fc20-base)
               libicudata.so.50()(64bit)
Error: Package: brltty-4.5-9.fc20.s390x (fc20-base)
           Requires: libicuuc.so.50()(64bit)
           Removing: libicu-50.1.2-11.el7.s390x (@RHEL7.0-Server/$releasever)
               libicuuc.so.50()(64bit)
           Updated By: libicu-54.1-11.el7_0.ibm.1.s390x (frobisher-base)
              ~libicuuc.so.54()(64bit)
           Available: libicu-50.1.2-10.fc20.s390x (fc20-base)
               libicuuc.so.50()(64bit)
Error: Package: ncurses-libs-5.9-13.20130511.el7.s390 (rhel7)
           Requires: ncurses-base = 5.9-13.20130511.el7
           Removing: ncurses-base-5.9-13.20130511.el7.noarch (@RHEL7.0-Server/$releasever)
               ncurses-base = 5.9-13.20130511.el7
           Updated By: ncurses-base-5.9-13.20130511.el7_0.ibm.1.noarch (frobisher-base)
               ncurses-base = 5.9-13.20130511.el7_0.ibm.1
           Available: ncurses-base-5.9-12.20130511.fc20.noarch (fc20-base)
               ncurses-base = 5.9-12.20130511.fc20
Error: Package: libgudev1-208-26.fc20.s390x (fc20-base)
           Requires: systemd-libs = 208-26.fc20
           Installed: systemd-libs-208-11.el7_0.6.s390x (@RHEL7.0-Update/$releasever)
               systemd-libs = 208-11.el7_0.6
Error: Package: polkit-0.112-5.el7.s390 (rhel7)
           Requires: libsystemd-login.so.0
Error: Package: perl-Text-ParseWords-3.29-4.el7_0.ibm.1.noarch (frobisher-base)
           Requires: perl(:MODULE_COMPAT_5.16.3)
           Removing: 4:perl-5.16.3-283.el7.s390x (@RHEL7.0-Server/$releasever)
               perl(:MODULE_COMPAT_5.16.3)
           Updated By: 4:perl-5.18.2-289.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.2)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
           Available: 4:perl-5.16.3-283.el7_0.ibm.1.s390x (frobisher-base)
               perl(:MODULE_COMPAT_5.16.3)
           Available: 4:perl-5.18.1-288.fc20.s390x (fc20-base)
              ~perl(:MODULE_COMPAT_5.18.1)
              ~perl(:MODULE_COMPAT_5.18.0)
Error: Package: xz-devel-5.1.2-8alpha.fc20.s390x (@fc20-base)
           Requires: xz-libs(s390-64) = 5.1.2-8alpha.fc20
           Removing: xz-libs-5.1.2-8alpha.fc20.s390x (@fc20-base)
               xz-libs(s390-64) = 5.1.2-8alpha.fc20
           Updated By: xz-libs-5.1.2-9alpha.el7_0.ibm.1.s390x (frobisher-base)
               xz-libs(s390-64) = 5.1.2-9alpha.el7_0.ibm.1
           Available: xz-libs-5.1.2-6alpha.fc20.s390x (fc20-base)
               xz-libs(s390-64) = 5.1.2-6alpha.fc20
           Available: xz-libs-5.1.2-8alpha.el7.s390x (frobisher-beta4.3)
               xz-libs(s390-64) = 5.1.2-8alpha.el7
Error: generic-logos conflicts with fedora-logos-21.0.1-1.fc20.s390x
Error: Package: udisks2-2.1.2-2.fc19.s390x (installed)
           Requires: libudisks2 = 2.1.2-2.fc19
           Removing: libudisks2-2.1.2-2.fc19.s390x (installed)
               libudisks2 = 2.1.2-2.fc19
           Updated By: libudisks2-2.1.2-5.el7.s390x (rhel7)
               libudisks2 = 2.1.2-5.el7
           Available: libudisks2-2.1.1-1.fc20.s390 (fc20-base)
               libudisks2 = 2.1.1-1.fc20
           Available: libudisks2-2.1.2-2.fc20.s390 (fc20-base)
               libudisks2 = 2.1.2-2.fc20

**Comment by laggarcia** [comment]
This is a yum error. You might get the same error if you run "yum update" from command line. You need to check your RPM database and yum configuration as they are probably in an inconsistent state.

**Comment by atreyeemukhopadhyay** [comment]
Thanks for the update. Closing the issue as it's working as expected.
