### ISSUE TITLE
Libervirt errors on kimchi console

### ISSUE THREAD

**Issue by harche** [kimchi-project/kimchi#688]
Hi,

Seeing following errors coming from kimchi while trying to start a VM.

libvirt: XML-RPC error : packet 536903810 bytes received from server too large, want 16777216
libvirt: XML-RPC error : internal error: client socket is closed
libvirt: XML-RPC error : internal error: client socket is closed

**Comment by ramonmedeiros** [comment]
Please, add more details:

- the host your are running
- the vm os 
- kimchi version
- the vm was started from libvirt or web interface?

**Comment by alinefm** [comment]
I will close this issue due inactivity. Please, reopen if the problem persists.
