### ISSUE TITLE
Provide an api to retrieve all host pci devices that is not attached to a VM (running or not)

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#690]
Currently KIMCHI UI displays the host PCI devices which are already 'in-use' by other active domains in 'Host PCI Device' panel under edit guest window. Also it allows users to assign these 'in-use' PCI devices to other guest VMs.

Recreation steps:
==================
1. Assign a pci device to a VM
2. Edit another guest VM and navigate to 'Host PCI Device' -> we can add same PCI adapter to this guest as well.

3. Start the VM in #1.  This is when user will realize that specified PCI device is already in use by other active domain in which Kimchi will display an error msg.

Expected result:
=================
KIMCHI UI should not display 'in-use' host PCI devices on 'Host PCI Device' panel under guest edit window .

In order to achieve this, we need an API to retrieve all host pci devices that is not attached to a VM (running or not).  This is currently not available in the backend.

**Comment by danielhb** [comment]
I'll have a look

**Comment by sstoppler** [comment]
This was fixed a while back.
