### ISSUE TITLE
Unable to login with newly created kimchi user

### ISSUE THREAD

**Issue by papusagar83** [kimchi-project/kimchi#691]
When i try to login with  created kimchi user,its throwing message that username and password is incorrect.
 
I am running kimchi  https://9.152.151.63:8001/#tabs/host     "mozilla firefox ESR 31.8.0 ESR".

How to reproduce

1)Install and launch the kimchi.
2)Login with an admin user.(root).
3)Switch to administrator tab
4)Go to User management and create a kimchi user.
5)Logout from admin user root
6)Login with created kimchi user

Actual behavior 

1)Login fail with message "Username and password in incorrect."

Expected behavior 

1)Login should be successful with created kimchi user.  

Snaps

i) Created a kimchi user as "test"
![nuew_kimchi_user_test](https://cloud.githubusercontent.com/assets/13309902/8649108/7e94bcfa-2984-11e5-9c5d-e9e2f9775b16.PNG)

ii)Login fail with kimchi user "test"
![login_with_kimchi_user_test](https://cloud.githubusercontent.com/assets/13309902/8649164/0da6a386-2985-11e5-92f8-7c85581b5ace.PNG)

**Comment by cd1** [comment]
I believe this issue is related to the [project Ginger](http://github.com/kimchi-project/ginger), not Kimchi.
