### ISSUE TITLE
Unable to perform different actions(post) on storage volume  from UI

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/kimchi#693]
Following Post actions resize,clone,wipe are mentioned  for storage volume in  https://github.com/kimchi-project/kimchi/blob/master/docs/API.md . But from UI , no option is there to perform these operations.

I am running kimchi https://9.152.151.63:8001/#tabs/host "mozilla firefox ESR 31.8.0 ESR".

Steps to reproduce
1)Install and launch the kimchi. Login with admin user.
2)Navigate to 'Storage' tab.
3)Expand a storage pool having storage volume added to it.

we should be able to resize,clone,wipe storage volumes. 
currently there is no option to perform these actions on storage volumes.

![postaction](https://cloud.githubusercontent.com/assets/13199397/8718977/f9d7c626-2bc5-11e5-949a-aea64ba9436e.png)

**Comment by alinefm** [comment]
It is the same of #833
