### ISSUE TITLE
Start guest is failing, when post action to attach storage for an vm is passed with url as path.

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#696]
I have written unit test cases to cover storage attached scenarios to guest.,
1)create a guest with storage pool of dir type attached. (guest :- vm_test, storage_pool_name = dir_storage
2)delete the storage pool dir_storage attached to guest 
3)attach the storage pool dir_storage to guest using post action
    storage_info = {'type': 'disk', 'path': 'http://fedora.mirrors.tds.net:80/pub/fedora/releases/20/Live/x86_64/Fedora-Live-Desktop-x86_64-20-1.iso', 'pool': dir_storage}  //the body that is passed to post
    /vmsstorages/vm_test/storages/  
step 3 succeeds without any issues

4)start the guest vm_test.
it fails with error
libvirt: QEMU Driver error : internal error: process exited while connecting to monitor: 2015-07-16T18:21:36.442828Z qemu-system-x86_64: -drive file=http://fedora.mirrors.tds.net:80/pub/fedora/releases/20/Live/x86_64/Fedora-Live-Desktop-x86_64-20-1.iso,if=none,id=drive-virtio-disk0,format=raw,cache=none: could not open disk image http://fedora.mirrors.tds.net:80/pub/fedora/releases/20/Live/x86_64/Fedora-Live-Desktop-x86_64-20-1.iso: curl block device does not support writes

So issue here probably is i cannot pass url to path for disk type.
But still the api accepts its and passes in attaching the storage to vm_test in step 3.
The same operation i cannot perform from UI..

If the url is passed as cdrom type and attached to guest, start guest works smoothly.

Expected behaviour :- Step 3 should not succeed if the path provided is invalid

**Comment by alinefm** [comment]
This issue is duplicated of https://github.com/kimchi-project/kimchi/issues/355
