### ISSUE TITLE
Attach storage pool of type cdrom to guest is inconsistent in UI when guest is in running state

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#697]
1)Create guest with cdrom type of storage
2)delete the cdrom type of storage from guest
3)start guest, it fails as nothing is there to boot for but guest is in start state
4)go to edit of guest, switch to storage tab, try adding cdrom type of storage.

![screenshot from 2015-07-17 01 11 08](https://cloud.githubusercontent.com/assets/12495213/8733327/0ff0f6c0-2c21-11e5-9c42-b81842169958.png)

There is no way we can add cdrom type when guest is in running state but message shows cdrom is supported.

Try to attach the cdrom storage using api it fails with below message
Request ended with status 500-KCHVMSTOR0008E: Error while creating new storage device: operation failed: open disk image file failed (500 Internal Server Error)

Expected :- When guest is in running state, cdrom type of storage should not be displayed to user.

**Comment by sstoppler** [comment]
@abhiramkulkarni -- would you mind retrying this scenario?  With the new UI, when editing a guest that is in running state, 'cdrom' device type is no longer a storage device option.  Thanks!
