### ISSUE TITLE
Task return by API call to add volume to logical storage pool fails. However vgdisplay list the volume.

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#699]
API call to add volume under logical storage pool return task and this task fails.

1) Task Response :{u'status': u'failed', u'message': u'Unexpected exception: KCHVOL0007E: Unable to create storage volume test_default in storage pool <libvirt.virStoragePool object at 0x7f764c1c24d0>. Details: key in virGetStorageVol must not be NULL', u'id': u'430', u'target_uri': u'/storagepools/test_default/storagevolumes/test_default'})

However the vgdisplay list the created volume test_default.

2) But API call to delete the volume it gets 404.
KCHVOL0002E: Storage volume test_default does not exist in storage pool test_default (404 Not Found)

3) After that another API request to add volume fails saying already exists.
Task Response:, 'finished', {u'status': u'failed', u'message': u'Unexpected exception: KCHVOL0007E: Unable to create storage volume test_default in storage pool <libvirt.virStoragePool object at 0x7f764c22fc10>. Details: internal error: Child process (/usr/sbin/lvcreate --name test_default -L 1K --virtualsize 1K test_default) unexpected exit status 5:   Logical volume "test_default" already exists in volume group "test_default"\n', u'id': u'431', u'target_uri': u'/storagepools/test_default/storagevolumes/test_default'})

4) But again get API request say not found:
Storage volume test_default does not exist in storage pool test_default (404 Not Found)

**Comment by pvital** [comment]
@archu-s, please provide the full API command line used to test this scenario.

**Comment by alinefm** [comment]
I will close this issue due inactivity. Please, reopen if the problem persists.
