### ISSUE TITLE
Task to add storage volume with any one of the format bochs, cloop, dmg fails

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#701]
Task to add storage volume with name, capacity, type, and format fails for below formats:

URI: /storagepools/test_default/storagevolumes

1) bochs

data = {'name': 'test_default', 'type': 'file', 'format': 'bochs', 'capacity': '1024'}

Task Response: {u'status': u'failed', u'message': u"Unexpected exception: KCHVOL0007E: Unable to create storage volume test_default in storage pool <libvirt.virStoragePool object at 0x7fd31849ed50>. Details: internal error: Child process (/usr/bin/qemu-img create -f bochs /var/lib/kimchi/test_default 1K) unexpected exit status 1: qemu-img: /var/lib/kimchi/test_default: Format driver 'bochs' does not support image creation\n", u'id': u'8', u'target_uri': u'/storagepools/test_default/storagevolumes/test_default'}

2) cloop 
data = {'name': 'test_default', 'type': 'file', 'format': 'cloop', 'capacity': '1024'}

Task Response: {u'status': u'failed', u'message': u"Unexpected exception: KCHVOL0007E: Unable to create storage volume test_default in storage pool <libvirt.virStoragePool object at 0x7f765a703950>. Details: internal error: Child process (/usr/bin/qemu-img create -f cloop /var/lib/kimchi/test_default 1K) unexpected exit status 1: qemu-img: /var/lib/kimchi/test_default: Format driver 'cloop' does not support image creation\n", u'id': u'451', u'target_uri': u'/storagepools/test_default/storagevolumes/test_default'})

3) dmg
data = {'name': 'test_default', 'type': 'file', 'format': 'dmg', 'capacity': '1024'}

Task Response: {u'status': u'failed', u'message': u"Unexpected exception: KCHVOL0007E: Unable to create storage volume test_default in storage pool <libvirt.virStoragePool object at 0x7f764d4fb350>. Details: internal error: Child process (/usr/bin/qemu-img create -f dmg /var/lib/kimchi/test_default 1K) unexpected exit status 1: qemu-img: /var/lib/kimchi/test_default: Format driver 'dmg' does not support image creation\n", u'id': u'455', u'target_uri': u'/storagepools/test_default/storagevolumes/test_default'})

**Comment by pvital** [comment]
@archu-s, as similar to Issue #703 all errors are provided by libvirt (actually by qemu but addressed by libvirt). Kimchi uses libvirt API to realize this kind of operation and only raises the errors provided by libvirt.

To confirm if the errors are provided by libvirt, please, try the same operation using virsh command. If it confirms, update this issue to be documented.

Regards.

**Comment by alinefm** [comment]
I will close this issue due inactivity. Please, reopen if the problem persists.
