### ISSUE TITLE
Resize storage volume with format cow, qcow, qcow2, qed, vmdk, vpc fails

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#703]
1) Resize storage volume with format cow, qcow, qcow2, qed, vmdk fails with error, even size for resize mentioned was more than it was before.

URI: GET /storagepools/test_default/storagevolumes/test_default
response; {u'capacity': 1057, u'name': u'test_default', u'format': u'cow', u'used_by': [], u'allocation': 4096, u'path': u'/var/lib/kimchi/test_default', u'type': u'file'}

URI: POST /storagepools/test_default/storagevolumes/test_default/resize
resize_data:{'size': 2114}
error: KCHVOL0011E: Unable to resize storage volume test_default. Details: invalid argument: can't shrink capacity below existing allocation (500 Internal Server Error)

2) stoarge volume with fomat vpc fails with below error:
KCHVOL0011E: Unable to resize storage volume test_default. Details: internal error: Child process (/usr/bin/qemu-img resize /var/lib/kimchi/test_default 69632) unexpected exit status 1: qemu-img: This image does not support resize
 (500 Internal Server Error)

**Comment by pvital** [comment]
Hello @archu-s 

The first error is provided by libvirt and the second by qemu. Kimchi uses libvirt API to realize this kind of operation and only raises the errors provided by libvirt. 

To confirm if the errors are provided by libvirt, please, try the same operation using virsh command. If it confirms, update this issue to be documented.

Regards.

**Comment by alinefm** [comment]
I will close this issue due inactivity. Please, reopen if the problem persists.
