### ISSUE TITLE
WOK: After log into the wok  page, web page refreshing continuously..

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#704]
Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed

Issue: WOK web refreshing continuously
           Screen URL toggling between following two -
           https://127.0.0.1:8001/#
           https://127.0.0.1:8001#Undefined
Here are the screen shots:
![1b13da17c8c00fb](https://cloud.githubusercontent.com/assets/12508158/8746204/9f9b9c84-2ca4-11e5-844d-98d142df0ac5.jpg)

![364b4e76d5b57354](https://cloud.githubusercontent.com/assets/12508158/8746205/9f9f5a40-2ca4-11e5-81f4-1a0c16b9d93e.jpg)

**Comment by pvital** [comment]
Resent Atreyee <atreyee@linux.vnet.ibm.com>'s patch to ML.
[Kimchi-devel] [PATCH] Issue #704: page refreshing in Wok when no plugins installed
