### ISSUE TITLE
WOK: "About" pop up window's close icon is not aligned properly 

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#706]
Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed
7. Clicked on "About" button.
Problem: "About" pop up window's close icon is not aligned properly 

![41cef0245f70dfd0](https://cloud.githubusercontent.com/assets/12508158/8746320/bb0676a0-2ca5-11e5-8811-a99bef5374a2.jpg)

**Comment by alinefm** [comment]
This issue was moved to Wok repository https://github.com/kimchi-project/wok/issues/5
