### ISSUE TITLE
WOK: Kimchi logo still displaying on the main page

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#707]
Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed

Problem: Kimchi logo still displaying on the main page

![c464ec05fd47ac1](https://cloud.githubusercontent.com/assets/12508158/8746389/475c2262-2ca6-11e5-8ec4-da0f3c4283f4.jpg)

**Comment by alinefm** [comment]
This issue was moved to Wok repository https://github.com/kimchi-project/wok/issues/4
