### ISSUE TITLE
WOK: After restart wokd daemon, browser still shows previous main page instead of log in screen

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#708]
Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed
7. Restared wokd daemon
8. Refreshed the url https://127.0.0.1:8001 on browser
Problem: browser still shows previous main page instead of log in screen

**Comment by alinefm** [comment]
This issue was moved to Wok repository: https://github.com/kimchi-project/wok/issues/3
