### ISSUE TITLE
Spice Screen not refreshing

### ISSUE THREAD

**Issue by emtie** [kimchi-project/kimchi#710]
I am on Ubuntu 14.04.2 and installed kimchi. It looks great but when I open a console window I got the following Errormessages:

Connected to wss://hostname.domain:64667/?token=bWFpbDAx
Channel type 9 unknown.
Channel type 9 unknown.
Channel type 9 unknown.
Channel type 9 unknown.
9: No message handlers for this channel; message 101
Unimplemented function 108(Inval All Palettes) [ further notices suppressed ]
Unimplemented function 102(Display Mark) [ further notices suppressed ]
FIXME: Unable to interpret bitmap of format: 2
2: Unknown message type 304!
FIXME: Unable to interpret bitmap of format: 2
2: Unknown message type 304!
FIXME: Unable to interpret bitmap of format: 2
2: Unknown message type 304!
keyboard channel is insecure
FIXME: Unable to interpret bitmap of format: 2
2: Unknown message type 304!

What can I do??? The screen is not refreshing

**Comment by alinefm** [comment]
Hi @emtie!
Kimchi uses spice-html5 project to handle the SPICE console. Maybe you need to update it on your server.

I can say it works on Ubuntu 15.04 with the following spice-html5 package:
alinefm@alinefm-Standard-PC-i440FX-PIIX-1996:~$ dpkg -s spice-html5
Package: spice-html5
Status: install ok installed
Priority: extra
Section: web
Installed-Size: 304
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 0.1.4-1
Pre-Depends: dpkg (>= 1.15.6~)
Recommends: websockify

**Comment by alinefm** [comment]
I am closing this issue due inactivity.
Please, reopen if the problem persists.
