### ISSUE TITLE
google chrome browser gets hung with base frarmework (wok) without any plugins

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/kimchi#711]
Environment: x86
Operating system: Fedora
Browser: Google Chrome
Steps performed:
1. Installed WOK without any plugins (https://github.com/kimchi-project/kimchi/tree/wok)
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed and browser is hung 
Problem: google chrome browser gets hung with base frarmework (wok) without any plugins

**Comment by lcorreia** [comment]
This seems to be a dup of #708 .

**Comment by alinefm** [comment]
Closing based on last comment.
