### ISSUE TITLE
can't start wokd in ubuntu using service 

### ISSUE THREAD

**Issue by harche** [kimchi-project/kimchi#713]
```
service wokd start
/etc/init.d/wokd: 32: .: Can't open /etc/rc.status
```

**Comment by lcorreia** [comment]
I could reproducible this with kimchid from master branch (log below), thus I believe it's not specific to wok.

**Comment by liucougar** [comment]
this is because the ubuntu is not using systemd (it's using upstart probably)

**Comment by alinefm** [comment]
@liucougar Ubuntu 15.04 (the version tested by the Kimchi community) already uses systemd.

@harche On which Ubuntu version did you get this problem?

I am running wokd on Ubuntu 15.04 without problems.

**Comment by harche** [comment]
@alinefm Ubuntu 14.04

**Comment by alinefm** [comment]
@harche Kimchi community usually tests Kimchi in the latest version, ie, Ubuntu 15.04
But any patch is more than welcome to have Kimchi working as expected on Ubuntu 14.04
