### ISSUE TITLE
WOK: Session timeout url shows username and password on browser's address bar

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#714]
Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Installed kimchi-wok plugin
3. Installed ginger-wok plugin
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed with Kimchi and Ginger tabs
7. Leave the session for 33+ minutes ( as session time is 2000 )
8. Click on any tab
9. Login POP up window displayed
10. Entered  userid and password

Issue:
1. Got the error as shown in below screen shot
2. URL  has username and password

![41a5d9ef06d62034](https://cloud.githubusercontent.com/assets/12508158/8938857/b420db14-357e-11e5-8bce-da8a19e0ad46.jpg)

**Comment by alinefm** [comment]
Fixed by e2c6b8c8d8927f95c901119a7b0307d2fcb1d7e4
