### ISSUE TITLE
500 status code returned when not valid action is perform on a VM. Is this expected to return 500 status code?Isn't it should be 400 instead?

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#716]
Is 500 status code for REST API call is expected to be returned for below cases. Isn't it should be 400 instead.
1) Shutdown on Powered off VM
2) Reset on Powered off VM
3) Power off on Powered off VM
4) Start on suspended VM
5) Reset on created VM
6) Power off on created VM
7) Shutdown on created VM
8) Start on Resumed VM
9) Start on Started VM

**Comment by alinefm** [comment]
It is already fixed and it is also duplicated of #682 #684 #685
