### ISSUE TITLE
libvirt: error : Unable to create bridge virbr0: File exists - for wok

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/kimchi#717]
Hi, I see the issue #556 with wok branch..
Steps followed -
Environment: x86
Operating system: Fedora
Browser: Google Chrome
Steps performed:
1. Installed WOK without any plugins (https://github.com/kimchi-project/kimchi/tree/wok)
2. Started wokd daemon
3. Installed kimchi-wok plugin
4. Restarted wokd daemon. It fails with the below error
systemctl status wokd

● wokd.service - Wok - Webserver Originated from Kimchi
Loaded: loaded (/usr/lib/systemd/system/wokd.service; disabled)
Active: failed (Result: exit-code) since Wed 2015-07-22 12:31:36 IST; 1min 41s ago
Process: 13062 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=1/FAILURE)
Process: 13051 ExecStart=/usr/bin/wokd (code=exited, status=1/FAILURE)
Main PID: 13051 (code=exited, status=1/FAILURE)

Jul 22 12:31:36 localhost.localdomain wokd[13051]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
Jul 22 12:31:36 localhost.localdomain wokd[13051]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Jul 22 12:31:36 localhost.localdomain wokd[13051]: nginx: [emerg] still could not bind()
Jul 22 12:31:36 localhost.localdomain wokd[13051]: libvirt: error : Unable to create bridge virbr0: File exists
Jul 22 12:31:36 localhost.localdomain wokd[13051]: WARNING: no 'numpy' module, HyBi protocol will be slower
Jul 22 12:31:36 localhost.localdomain systemd[1]: wokd.service: main process exited, code=exited, status=1/FAILURE
Jul 22 12:31:36 localhost.localdomain kill[13062]: kill: not enough arguments
Jul 22 12:31:36 localhost.localdomain systemd[1]: wokd.service: control process exited, code=exited status=1
Jul 22 12:31:36 localhost.localdomain systemd[1]: Unit wokd.service entered failed state.
Jul 22 12:31:36 localhost.localdomain systemd[1]: wokd.service failed.

output from brctl -
brctl show

bridge name bridge id STP enabled interfaces
virbr0 8000.000000000000 yes

**Comment by alinefm** [comment]
Hi @sureshab!

As you said, it is the same issue reported on #556 
Please, reuse/update existing issues instead of open a duplicated one.
