### ISSUE TITLE
[WOK] Replace Helvetica Neue font for an open-source font

### ISSUE THREAD

**Issue by samhenri** [kimchi-project/kimchi#719]
Following the mailing list, I'm submitting this issue so we can have a record here until the new-ui guide is updated.

Helvetica Neue font suggested by the new-ui guide is a commercial font that is bundled in Mac OS X and iOS. We could keep the equivalent system fonts like Arial for Windows, Cantarell for GNOME, etc, or we can use an open source font that covers all Helvetica Neue different styles/weights.

A nice unicode font that covers almost all languages and styles is Open Sans, licensed under Apache 2.0. Another font we could use is TeXGyreHeros (GUST license).

For Chinese Simplified, Chinese Traditional, Korean and Japanese we can use default system fonts or Noto Sans CJK, but we would have some extra work to optimize it in the front-end (these font files are heavy, ~13MB each file, ~88MB total)

**Comment by alinefm** [comment]
The build process and README files were updated to depend on open-sans-fonts package.
The font files are being exposed by the web server. 
I don't think the UI specification must be done to reflect it, so I am closing this bug.

Commit that expose openSans font files to web server: 5389b7152e49371d32a59c0fca50ce35a4862c8b
