### ISSUE TITLE
Introducing new plug-in ginger-base out of kimchi host tab functionality

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#720]
**Introducing new plug-in ginger-base out of kimchi host tab functionality.**
     Moving the host functionality from Kimchi plug-in and create new plug-in with host tab functionality.

`Background on new plug-in` 
http://lists.ovirt.org/pipermail/kimchi-devel/2015-August/011196.html
http://lists.ovirt.org/pipermail/kimchi-devel/2015-August/011220.html

**Comment by chandrureddy** [comment]
I am started working on it.

**Comment by alinefm** [comment]
There are a lot of commits associated to this feature.
I will refer the last most important commit: 379ccff0815bf9842eb5aa47979ecc980e4a8b5c
