### ISSUE TITLE
Paths for isos, debugreports and screenshots are pointing to /var/lib/kimchi in wok

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#721]
Paths for isos, debugreports and screenshots are pointing to /var/lib/kimchi in wok.

	mkdir -p $(DESTDIR)/var/lib/kimchi/debugreports
	mkdir -p $(DESTDIR)/var/lib/kimchi/screenshots
	mkdir -p $(DESTDIR)/var/lib/kimchi/isos

Do we want the path to be changed to /var/lib/wok  to make the structure consistent or keep them as it is ?

Thanks in advance.

**Comment by lcorreia** [comment]
While doing wok work, I left them as kimchi since for me it is kimchi-specific stuff. Let's see what the community says about it.

**Comment by lcorreia** [comment]
I've noticed the debugreports and screenshots files were being saved under wok directory instead of kimchi and sent a patch to fix that.

**Comment by alinefm** [comment]
Duplicated of #738
