### ISSUE TITLE
Page not found when clicked on links "Wok Login Screen", "Kimchi Guest View", "Kimchi Template View"  of README.md

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#722]
Page not found when clicked on links "Wok Login Screen", "Kimchi Guest View", "Kimchi Template View"  of README.md

Go to:
https://github.com/kimchi-project/kimchi/tree/wok/plugins/kimchi

Try clicking any of  links ("Wok Login Screen", "Kimchi Guest View", "Kimchi Template View") from the page content.

You will see: 

![filenotfound](https://cloud.githubusercontent.com/assets/10830725/9486794/727b597e-4be9-11e5-92ab-08bd9743f30b.jpg)

**Comment by chandrureddy** [comment]
Please assign the ticket to me as I found solution and I will releasing it part of ginger-base plung in code check ins.

**Comment by alinefm** [comment]
I am closing this issue as the images are now being displayed correctly.
I could not find the commit which fixed it.
