### ISSUE TITLE
wok - plugins - kimchi - test_config.py fails

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/kimchi#724]
Steps followed -
Downloaded source code from - https://github.com/kimchi-project/kimchi/tree/wok
installed wok
installed kimchi
from root user, executed test_config.py in plugins.kimchi.tests folder.
It fails with following error -

Traceback (most recent call last):
  File "/home/suresh/git/kimchi-wok/plugins/kimchi/tests/test_config.py", line 195, in test_kimchi_config
    self.assertEquals(kimchi_config, configObj)
AssertionError: {'/help': {'tools.nocache.on': True, 'tools.staticdir.dir': '/usr/share/wok/plug [truncated]... != {'/libs': {'tools.expires.on': True, 'tools.nocache.on': False, 'tools.expires.s [truncated]...
Diff is 3623 characters long. Set self.maxDiff to None to see it.

**Comment by lcorreia** [comment]
I'm working on fixing this.

**Comment by lcorreia** [comment]
Patch submitted to mailing list.

**Comment by alinefm** [comment]
Fixed by 729bd5789945ba092e1aeac1df63414e69ab6804
