### ISSUE TITLE
Support for template images

### ISSUE THREAD

**Issue by NuxRo** [kimchi-project/kimchi#725]
Hello,

Is there any plan to support deploying templates based on OS images, similar to how e.g. Xenserver can do or perhaps OpenNebula would be an even better example?
Deploying from ISO seems like a waste of time.

**Comment by pvital** [comment]
Hello @NuxRo. I don't know how Xenserver or OpenNebula works, so could you explain a little bit more about it?

From what you wrote, I could understand that you have an OS image from a previous VM and you can create a template based on that image. Am I right?

**Comment by laggarcia** [comment]
@NuxRo, if what you are looking for is what @pvital described above, I think this is already available in Kimchi today.

**Comment by NuxRo** [comment]
Hello,

Precisely. You could use either a qcow or a lvm as a backing file for the new VM.
In doing so you ease the deployment of new machines as well as optimizing disk usage.

I have only looked over the most recent videos/presentations I could find and have not seen anything remotely close to this, but if it exists in Kimchi today, then that's pretty sweet and thanks for letting me know.

**Comment by pvital** [comment]
@NuxRo you can do that selecting the option 'Local Image File' (the second one) in the 'Add Template' screen. 

![screenshot from 2015-09-01 09-29-25](https://cloud.githubusercontent.com/assets/699330/9604196/6ca5fee4-508c-11e5-9941-eb1f25b37151.png)

Then, you only need to input the path of the image you want to use as base to the template and click on 'Create' button.

![screenshot from 2015-09-01 09-32-07](https://cloud.githubusercontent.com/assets/699330/9604214/87203884-508c-11e5-909b-eea41ef61af4.png)

I think this is what you are looking for.

**Comment by NuxRo** [comment]
Yes indeed, thanks!
