### ISSUE TITLE
Repository doesn't accept $variable in URL

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#727]
When editing or adding a YUM repo, it could be important to fill the URL path with a variable, to make it flexible according to the current version for example. YUM accepts variable starting with $ but Kimchi doesn't understand this character as valid, for example: http://my.repo.url/$releasever/

**Comment by alinefm** [comment]
Fixed by 7d40ff42248e6352343eb703f5d054596afca3cb
