### ISSUE TITLE
After logging in - Error Code 404, Reason Nothing matches the given URI

### ISSUE THREAD

**Issue by kgolic** [kimchi-project/kimchi#730]
Installed Kimchi 1.5.0 on a newly installed Ubuntu 14.04.3 LTS server following the Readme.  

Navigating to https://server_ip:8001, the login screen appears.  

After successfully logging in, there are no tabs to select, only Error Code 404, Reason Nothing matches the given URI

**Comment by pvital** [comment]
@kgolic How did you downloaded the source code? git clone or deb package?

**Comment by liucougar** [comment]
this probably caused by #729?

**Comment by kgolic** [comment]
I downloaded the source code from github and built it by doing the following: 

1. wget https://github.com/kimchi-project/kimchi/archive/master.zip
2. unzip master.zip
3. cd kimchi-master/
4. ./autogen.sh --system
5. sudo make install
6. sudo kimchid --host=0.0.0.0

**Comment by alinefm** [comment]
Hi @kgolic 

Could you update your source code and verify if this problem was fixed by 4f4c4fc81e266bdab98e907d2be90b6f1d190307 ?

**Comment by kgolic** [comment]
@alinefm: this issue appears to be fixed after updating my source code to your recommendation.  thanks!

**Comment by alinefm** [comment]
Duplicated of #729
