### ISSUE TITLE
Installation of kimchi failed in wok latest code.

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/kimchi#735]
I downloaded the kimchi-wok today and tried to install the same. Ended up with failure.

Steps followed
1)make uninstall
2)make clean
3)./autogen.sh --system
4)make
5)make insall fails

[root@abhiram kimchi]# make install
Making install in src
make[1]: Entering directory '/root/PycharmProjects/kimchi/src'
make  install-recursive
make[2]: Entering directory '/root/PycharmProjects/kimchi/src'
Making install in wok
make[3]: Entering directory '/root/PycharmProjects/kimchi/src/wok'
make  install-recursive
make[4]: Entering directory '/root/PycharmProjects/kimchi/src/wok'
Making install in control
make[5]: Entering directory '/root/PycharmProjects/kimchi/src/wok/control'
make[6]: Entering directory '/root/PycharmProjects/kimchi/src/wok/control'
make[6]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/lib/python2.7/site-packages/wok/control'
 /usr/bin/install -c -m 644 base.py __init__.py plugins.py utils.py '/usr/lib/python2.7/site-packages/wok/control'
Byte-compiling python modules...
base.py__init__.pyplugins.pyutils.py
Byte-compiling python modules (optimized versions) ...
base.py__init__.pyplugins.pyutils.py
/usr/bin/mkdir -p /usr/lib/python2.7/site-packages/wok/control
make[6]: Leaving directory '/root/PycharmProjects/kimchi/src/wok/control'
make[5]: Leaving directory '/root/PycharmProjects/kimchi/src/wok/control'
Making install in model
make[5]: Entering directory '/root/PycharmProjects/kimchi/src/wok/model'
make[6]: Entering directory '/root/PycharmProjects/kimchi/src/wok/model'
make[6]: Nothing to be done for 'install-exec-am'.
/usr/bin/mkdir -p /usr/lib/python2.7/site-packages/wok/model
 /usr/bin/mkdir -p '/usr/lib/python2.7/site-packages/wok/model'
 /usr/bin/install -c -m 644 __init__.py model.py plugins.py '/usr/lib/python2.7/site-packages/wok/model'
Byte-compiling python modules...
__init__.pymodel.pyplugins.py
Byte-compiling python modules (optimized versions) ...
__init__.pymodel.pyplugins.py
make[6]: Leaving directory '/root/PycharmProjects/kimchi/src/wok/model'
make[5]: Leaving directory '/root/PycharmProjects/kimchi/src/wok/model'
Making install in xmlutils
make[5]: Entering directory '/root/PycharmProjects/kimchi/src/wok/xmlutils'
make[6]: Entering directory '/root/PycharmProjects/kimchi/src/wok/xmlutils'
make[6]: Nothing to be done for 'install-exec-am'.
/usr/bin/mkdir -p /usr/lib/python2.7/site-packages/wok/xmlutils
 /usr/bin/mkdir -p '/usr/lib/python2.7/site-packages/wok/xmlutils'
 /usr/bin/install -c -m 644 __init__.py utils.py '/usr/lib/python2.7/site-packages/wok/xmlutils'
Byte-compiling python modules...
__init__.pyutils.py
Byte-compiling python modules (optimized versions) ...
__init__.pyutils.py
make[6]: Leaving directory '/root/PycharmProjects/kimchi/src/wok/xmlutils'
make[5]: Leaving directory '/root/PycharmProjects/kimchi/src/wok/xmlutils'
make[5]: Entering directory '/root/PycharmProjects/kimchi/src/wok'
make[6]: Entering directory '/root/PycharmProjects/kimchi/src/wok'
make[6]: Nothing to be done for 'install-exec-am'.
/usr/bin/mkdir -p /usr/lib/python2.7/site-packages/wok
/usr/bin/install -c -m 644 API.json /usr/lib/python2.7/site-packages/wok/API.json
 /usr/bin/mkdir -p '/usr/lib/python2.7/site-packages/wok'
 /usr/bin/install -c -m 644 config.py '/usr/lib/python2.7/site-packages/wok'
Byte-compiling python modules...
config.py
Byte-compiling python modules (optimized versions) ...
config.py
 /usr/bin/mkdir -p '/usr/lib/python2.7/site-packages/wok'
 /usr/bin/install -c -m 644 template.py i18n.py server.py proxy.py rollbackcontext.py utils.py objectstore.py basemodel.py asynctask.py __init__.py sslcert.py exception.py cachebust.py root.py auth.py '/usr/lib/python2.7/site-packages/wok'
Byte-compiling python modules...
template.pyi18n.pyserver.pyproxy.pyrollbackcontext.pyutils.pyobjectstore.pybasemodel.pyasynctask.py__init__.pysslcert.pyexception.pycachebust.pyroot.pyauth.py
Byte-compiling python modules (optimized versions) ...
template.pyi18n.pyserver.pyproxy.pyrollbackcontext.pyutils.pyobjectstore.pybasemodel.pyasynctask.py__init__.pysslcert.pyexception.pycachebust.pyroot.pyauth.py
make[6]: Leaving directory '/root/PycharmProjects/kimchi/src/wok'
make[5]: Leaving directory '/root/PycharmProjects/kimchi/src/wok'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/src/wok'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/src/wok'
Making install in nginx
make[3]: Entering directory '/root/PycharmProjects/kimchi/src/nginx'
make[4]: Entering directory '/root/PycharmProjects/kimchi/src/nginx'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/etc/nginx/conf.d'
 /usr/bin/install -c -m 644 wok.conf.in '/etc/nginx/conf.d'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/src/nginx'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/src/nginx'
make[3]: Entering directory '/root/PycharmProjects/kimchi/src'
make[4]: Entering directory '/root/PycharmProjects/kimchi/src'
 /usr/bin/mkdir -p '/usr/bin'
 /usr/bin/install -c wokd '/usr/bin'
 /usr/bin/mkdir -p '/etc/wok'
 /usr/bin/install -c -m 644 wok.conf '/etc/wok'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/src'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/src'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/src'
make[1]: Leaving directory '/root/PycharmProjects/kimchi/src'
Making install in ui
make[1]: Entering directory '/root/PycharmProjects/kimchi/ui'
Making install in css
make[2]: Entering directory '/root/PycharmProjects/kimchi/ui/css'
Making install in fontawesome
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/css/fontawesome'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/css/fontawesome'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/css/fontawesome'
 /usr/bin/install -c -m 644 fontawesome.css '/usr/share/wok/ui/css/fontawesome'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/css/fontawesome'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/css/fontawesome'
Making install in opensans
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/css/opensans'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/css/opensans'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/css/opensans'
 /usr/bin/install -c -m 644 opensans.css '/usr/share/wok/ui/css/opensans'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/css/opensans'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/css/opensans'
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/css'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/css'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/css'
 /usr/bin/install -c -m 644 theme-default.min.css '/usr/share/wok/ui/css'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/css'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/css'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/ui/css'
Making install in images
make[2]: Entering directory '/root/PycharmProjects/kimchi/ui/images'
Making install in theme-default
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/images/theme-default'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/images/theme-default'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/images/theme-default'
 /usr/bin/install -c -m 644 alert.png arrow-down-black.png arrow-down.png bg-mask.png bg.png check-green.png check-grey.png folder-arrow-down.png folder-arrow-right.png icon-alert.png icon-event.png icon-setting.png icon-tool.png logo-white.png nav-bg.png thumb-guest.png thumb-host.png user-icon.png logo-plain.gif wok-loading.gif '/usr/share/wok/ui/images/theme-default'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/images/theme-default'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/images/theme-default'
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/images'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/images'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/images'
 /usr/bin/install -c -m 644 logo.ico '/usr/share/wok/ui/images'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/images'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/images'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/ui/images'
Making install in js
make[2]: Entering directory '/root/PycharmProjects/kimchi/ui/js'
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/js'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/js'
 /usr/bin/install -c -m 644 wok.min.js '/usr/share/wok/ui/js'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/js'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/ui/js'
Making install in libs
make[2]: Entering directory '/root/PycharmProjects/kimchi/ui/libs'
Making install in themes
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes'
Making install in base
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes/base'
Making install in images
make[5]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes/base/images'
make[6]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes/base/images'
make[6]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/libs/themes/base/images'
 /usr/bin/install -c -m 644 ui-bg_diagonals-thick_18_b81900_40x40.png ui-bg_diagonals-thick_20_666666_40x40.png ui-bg_flat_10_000000_40x100.png ui-bg_glass_100_f6f6f6_1x400.png ui-bg_glass_100_fdf5ce_1x400.png ui-bg_glass_65_ffffff_1x400.png ui-bg_gloss-wave_35_f6a828_500x100.png ui-bg_highlight-soft_100_eeeeee_1x100.png ui-bg_highlight-soft_75_ffe45c_1x100.png ui-icons_222222_256x240.png ui-icons_228ef1_256x240.png ui-icons_ef8c08_256x240.png ui-icons_ffd27a_256x240.png ui-icons_ffffff_256x240.png '/usr/share/wok/ui/libs/themes/base/images'
make[6]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes/base/images'
make[5]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes/base/images'
make[5]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes/base'
make[6]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes/base'
make[6]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/libs/themes/base'
 /usr/bin/install -c -m 644 jquery-ui.min.css '/usr/share/wok/ui/libs/themes/base'
make[6]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes/base'
make[5]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes/base'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes/base'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes'
make[5]: Entering directory '/root/PycharmProjects/kimchi/ui/libs/themes'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs/themes'
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/libs'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/libs'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/libs'
 /usr/bin/install -c -m 644 jquery-ui-i18n.min.js jquery-ui.min.js jquery-1.10.0.min.js '/usr/share/wok/ui/libs'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/ui/libs'
Making install in pages
make[2]: Entering directory '/root/PycharmProjects/kimchi/ui/pages'
Making install in websockify
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/pages/websockify'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/pages/websockify'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/pages/websockify'
 /usr/bin/install -c -m 644 console.html '/usr/share/wok/ui/pages/websockify'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/pages/websockify'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/pages/websockify'
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui/pages'
make[4]: Entering directory '/root/PycharmProjects/kimchi/ui/pages'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui/pages'
 /usr/bin/install -c -m 644 i18n.json.tmpl wok-ui.html.tmpl error.html.tmpl login.html.tmpl '/usr/share/wok/ui/pages'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/ui/pages'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui/pages'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/ui/pages'
make[2]: Entering directory '/root/PycharmProjects/kimchi/ui'
make[3]: Entering directory '/root/PycharmProjects/kimchi/ui'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/ui'
 /usr/bin/install -c -m 644 robots.txt '/usr/share/wok/ui'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/ui'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/ui'
make[1]: Leaving directory '/root/PycharmProjects/kimchi/ui'
Making install in docs
make[1]: Entering directory '/root/PycharmProjects/kimchi/docs'
make[2]: Entering directory '/root/PycharmProjects/kimchi/docs'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/wok/doc'
 /usr/bin/install -c -m 644 API.md README.md wokd.8 '/usr/share/wok/doc'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/docs'
make[1]: Leaving directory '/root/PycharmProjects/kimchi/docs'
Making install in contrib
make[1]: Entering directory '/root/PycharmProjects/kimchi/contrib'
make  install-recursive
make[2]: Entering directory '/root/PycharmProjects/kimchi/contrib'
Making install in DEBIAN
make[3]: Entering directory '/root/PycharmProjects/kimchi/contrib/DEBIAN'
make[4]: Entering directory '/root/PycharmProjects/kimchi/contrib/DEBIAN'
make[4]: Nothing to be done for 'install-exec-am'.
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/root/PycharmProjects/kimchi/contrib/DEBIAN'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/contrib/DEBIAN'
make[3]: Entering directory '/root/PycharmProjects/kimchi/contrib'
make[4]: Entering directory '/root/PycharmProjects/kimchi/contrib'
make[4]: Nothing to be done for 'install-exec-am'.
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/root/PycharmProjects/kimchi/contrib'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/contrib'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/contrib'
make[1]: Leaving directory '/root/PycharmProjects/kimchi/contrib'
Making install in po
make[1]: Entering directory '/root/PycharmProjects/kimchi/po'
installing en_US.gmo as /usr/share/locale/en_US/LC_MESSAGES/wok.mo
installing pt_BR.gmo as /usr/share/locale/pt_BR/LC_MESSAGES/wok.mo
installing zh_CN.gmo as /usr/share/locale/zh_CN/LC_MESSAGES/wok.mo
installing de_DE.gmo as /usr/share/locale/de_DE/LC_MESSAGES/wok.mo
installing es_ES.gmo as /usr/share/locale/es_ES/LC_MESSAGES/wok.mo
installing fr_FR.gmo as /usr/share/locale/fr_FR/LC_MESSAGES/wok.mo
installing it_IT.gmo as /usr/share/locale/it_IT/LC_MESSAGES/wok.mo
installing ja_JP.gmo as /usr/share/locale/ja_JP/LC_MESSAGES/wok.mo
installing ko_KR.gmo as /usr/share/locale/ko_KR/LC_MESSAGES/wok.mo
installing ru_RU.gmo as /usr/share/locale/ru_RU/LC_MESSAGES/wok.mo
installing zh_TW.gmo as /usr/share/locale/zh_TW/LC_MESSAGES/wok.mo
if test "wok" = "gettext-tools"; then \
  /usr/bin/mkdir -p /usr/share/gettext/po; \
  for file in Makefile.in.in    Makevars.template; do \
    /usr/bin/install -c -m 644 ./$file \
	     /usr/share/gettext/po/$file; \
  done; \
  for file in Makevars; do \
    rm -f /usr/share/gettext/po/$file; \
  done; \
else \
  : ; \
fi
make[1]: Leaving directory '/root/PycharmProjects/kimchi/po'
Making install in plugins
make[1]: Entering directory '/root/PycharmProjects/kimchi/plugins'
Making install in sample
make[2]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample'
Making install in ui
make[3]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui'
Making install in config
make[4]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui/config'
make[5]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui/config'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui/config'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui/config'
Making install in js
make[4]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui/js'
make[5]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui/js'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui/js'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui/js'
Making install in pages
make[4]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui/pages'
make[5]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui/pages'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui/pages'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui/pages'
make[4]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui'
make[5]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/ui'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui'
make[4]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/ui'
Making install in po
make[3]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample/po'
make[3]: Nothing to be done for 'install'.
make[3]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample/po'
make[3]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample'
while read L && test -n "$L"; do                      \
	dir=mo/$L/LC_MESSAGES ;                       \
	/usr/bin/mkdir -p $dir ;                             \
	ln -sf ../../../po/$L.gmo $dir/sample.mo ;   \
done < po/LINGUAS
make[4]: Entering directory '/root/PycharmProjects/kimchi/plugins/sample'
make[4]: Nothing to be done for 'install-exec-am'.
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample'
make[3]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/plugins/sample'
make[2]: Entering directory '/root/PycharmProjects/kimchi/plugins'
make[3]: Entering directory '/root/PycharmProjects/kimchi/plugins'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/lib/python2.7/site-packages/wok/plugins'
 /usr/bin/install -c -m 644 __init__.py '/usr/lib/python2.7/site-packages/wok/plugins'
Byte-compiling python modules...
__init__.py
Byte-compiling python modules (optimized versions) ...
__init__.py
make[3]: Leaving directory '/root/PycharmProjects/kimchi/plugins'
make[2]: Leaving directory '/root/PycharmProjects/kimchi/plugins'
make[1]: Leaving directory '/root/PycharmProjects/kimchi/plugins'
make[1]: Entering directory '/root/PycharmProjects/kimchi'
while read L && test -n "$L"; do                  \
	dir=mo/$L/LC_MESSAGES ;                       \
	/usr/bin/mkdir -p $dir ;                             \
	ln -sf ../../../po/$L.gmo $dir/wok.mo ;   \
done < po/LINGUAS
make[2]: Entering directory '/root/PycharmProjects/kimchi'
make[2]: Nothing to be done for 'install-exec-am'.
touch: cannot touch ‘/var/lib/wok/objectstore’: No such file or directory
Makefile:979: recipe for target 'install-data-local' failed
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory '/root/PycharmProjects/kimchi'
Makefile:797: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/root/PycharmProjects/kimchi'
Makefile:495: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
[root@abhiram kimchi]#

**Comment by abhiramkulkarni** [comment]
After making changes to Makefile.am it works fine.

Below are the changes
[root@abhiram kimchi]# git diff Makefile.am
diff --git a/Makefile.am b/Makefile.am
index c7914d0..fb35cd1 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -69,6 +69,7 @@ all-local:
 
 install-deb: install
        cp -R $(top_srcdir)/contrib/DEBIAN $(DESTDIR)/
+       mkdir -p $(DESTDIR)/var/lib/wok
        touch $(DESTDIR)/var/lib/wok/objectstore
        $(MKDIR_P) $(DESTDIR)/etc/init
        $(MKDIR_P) $(DESTDIR)/usr/lib/firewalld/services
@@ -123,6 +124,7 @@ install-data-local:
                mkdir -p $(DESTDIR)/usr/lib/firewalld/services/; \
                $(INSTALL_DATA) src/firewalld.xml $(DESTDIR)/usr/lib/firewalld/services/wokd.xml; \
        fi; \
+       mkdir -p $(DESTDIR)/var/lib/wok/
        touch $(DESTDIR)/var/lib/wok/objectstore
        mkdir -p $(DESTDIR)/var/log/wok/
        touch $(DESTDIR)/var/log/wok/wok-access.log
[root@abhiram kimchi]#

**Comment by abhiramkulkarni** [comment]
Sure Aline,  Will send to mailing list from next time.

Yeah you are right, some changes were made in last week which has induced this problem.
After making changes to Makefile.am it works fine.

Below are the changes
[root@abhiram kimchi]# git diff Makefile.am
diff --git a/Makefile.am b/Makefile.am
index c7914d0..fb35cd1 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -69,6 +69,7 @@ all-local:
 
 install-deb: install
        cp -R $(top_srcdir)/contrib/DEBIAN $(DESTDIR)/
+       mkdir -p $(DESTDIR)/var/lib/wok
        touch $(DESTDIR)/var/lib/wok/objectstore
        $(MKDIR_P) $(DESTDIR)/etc/init
        $(MKDIR_P) $(DESTDIR)/usr/lib/firewalld/services
@@ -123,6 +124,7 @@ install-data-local:
                mkdir -p $(DESTDIR)/usr/lib/firewalld/services/; \
                $(INSTALL_DATA) src/firewalld.xml $(DESTDIR)/usr/lib/firewalld/services/wokd.xml; \
        fi; \
+       mkdir -p $(DESTDIR)/var/lib/wok/
        touch $(DESTDIR)/var/lib/wok/objectstore
        mkdir -p $(DESTDIR)/var/log/wok/
        touch $(DESTDIR)/var/log/wok/wok-access.log
[root@abhiram kimchi]#

**Comment by pvital** [comment]
@abhiramkulkarni please follow the steps in https://github.com/kimchi-project/kimchi/wiki/How-to-Contribute and submit your patch to the mailing list.

Curiosity: what's your host distribution?

**Comment by abhiramkulkarni** [comment]
Sure @pvital  . If these changes are not there in latest master branch , then i will send the patch.

I am on fedora 21
[Abhiram86@abhiram wok]$ uname -a
Linux abhiram 4.0.7-200.fc21.x86_64 #1 SMP Mon Jun 29 22:11:52 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[Abhiram86@abhiram wok]$

**Comment by pvital** [comment]
@abhiramkulkarni make sure you have the new code in master branch. @alinefm merged yesterday the next and wok branches into master and now this one has Wok and Kimchi.

Just to make sure, the default build process now to have Wok and Kimchi working is the following:

# To build Kimchi
You need to repeat those steps for each plugin your have in your  source code

    $ cd plugins/kimchi
    $ sudo ./autogen.sh --system && sudo make

# To build Wok

    $ cd ../../
    $ sudo ./autogen.sh --system && sudo make

After that you can start the wokd service:

    $ sudo src/wrokd

**Comment by abhiramkulkarni** [comment]
Non reproducible with latest release. Closing the defect.
