### ISSUE TITLE
deb package for Ubuntu > 15.04 doesn't work

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#736]
Ubuntu has replaced the init system to systemd, so the current service is not working.

root@ubuntu:~# systemctl status kimchid.service
● kimchid.service - LSB: Start the kimchid daemon
   Loaded: loaded (/etc/init.d/kimchid)
   Active: failed (Result: exit-code) since Tue 2015-09-29 07:07:36 EDT; 6s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 27747 ExecStart=/etc/init.d/kimchid start (code=exited, status=2)

Sep 29 07:07:36 ubuntu systemd[1]: Starting LSB: Start the kimchid daemon...
Sep 29 07:07:36 ubuntu systemd[1]: kimchid.service: control process exited, code=exited status=2
Sep 29 07:07:36 ubuntu systemd[1]: Failed to start LSB: Start the kimchid daemon.
Sep 29 07:07:36 ubuntu systemd[1]: Unit kimchid.service entered failed state.
Sep 29 07:07:36 ubuntu systemd[1]: kimchid.service failed.
Sep 29 07:07:36 ubuntu kimchid[27747]: /etc/init.d/kimchid: 32: .: Can't open /etc/rc.status
root@ubuntu:~#

**Comment by jrziviani** [comment]
I couln't make it works even after creating the package from a 15.04 system. I sent a patch to the list "Configure deb package to use systemd service if needed" to address it.

**Comment by alinefm** [comment]
Fixed by 20fd822d0ebd097ec79c33548debac57ffd88a0c
