### ISSUE TITLE
kimchi/model/storagepools.py pointing to iso directory '/var/lib/kimchi/isos'

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#738]
$ grep -irn "/var/lib/kimchi/isos" *
kimchi/docs/README.md:207:pool (default path is: /var/lib/kimchi/isos).
kimchi/model/storagepools.py:82:            pools['ISO'] = {'path': '/var/lib/kimchi/isos'}

Due to which I guess failing to start wokd:
[root@ bin]# sudo /usr/bin/wokd  --host=0.0.0.0
WARNING: no 'numpy' module, HyBi protocol will be slower
libvirt: Storage Driver error : cannot open path '/var/lib/kimchi/isos': No such file or directory

If I create the folder '/var/lib/kimchi/isos' wokd process starts properly.

1. kimchi/model/storagepools.py still pointing to iso directory '/var/lib/kimchi/isos' but as per the kimchi/Make.am it should be pointing to /var/lib/wok/plugins/kimchi/isos'

2. kimchi/doc/README.md also has similar issue
pool (default path is: /var/lib/kimchi/isos).
should be changed to 
pool (default path is: /var/lib/wok/plugins/kimchi/isos/).

Recent changes I see in the kimchi/Makefile.am :
install-data-local:
	$(MKDIR_P) $(DESTDIR)/$(localstatedir)/lib/wok/
	touch $(DESTDIR)/$(localstatedir)/lib/wok/objectstore
	$(MKDIR_P) $(DESTDIR)$(kimchidir)
	$(INSTALL_DATA) API.json $(DESTDIR)$(kimchidir)/API.json
	mkdir -p $(DESTDIR)/$(localstatedir)/lib/wok/plugins/kimchi/vnc-tokens
	mkdir -p $(DESTDIR)/$(localstatedir)/lib/wok/plugins/kimchi/{isos,screenshots}

**Comment by chandrureddy** [comment]
In my new patch I am trying to accommodate these changes.

**Comment by pvital** [comment]
@chandrureddy actually we will keep this path ('/var/lib/kimchi/isos') due to compatibility with older Kimchi versions. This issue was introduced when the code was split between Wok and Kimchi.

I sent a RFC to create a script to update all necessary paths when a user tries to upgrade from Kimchi to Wok+Kimchi.

**Comment by chandrureddy** [comment]
On the other hand we have to make sure storagepool.py should not crib in case of fresh installation where we do not create path '/var/lib/kimchi/isos' (If I am correct here).

To summarize:
With the fresh installation considering folder '/var/lib/kimchi/isos' not exists/created during the installation,  storagepool.py should not throw error similar to below.
Fatal: Unable to craete storage pool ISO. Please, check the configuration in /etc/wok/plugins.d/template.conf to ensure it has a valid storage pool.
or
ERROR: Storage Pool get vol count: cannot open path '/var/lib/kimchi/isos': No such file or directory
ERROR: Storage Pool get vol count: cannot open path '/var/lib/kimchi/isos': No such file or directory
ERROR: Storage Pool get vol count error no: 38
ERROR: Storage Pool get vol count error no: 38

**Comment by pvital** [comment]
@chandrureddy you are right regarding fresh installation. The point is that, for what I remember, we decided to maintain the path '/var/lib/kimchi/isos' even for fresh installations. @alinefm, can  you confirm this?

My suggestion is do not change the path  '/var/lib/kimchi/isos' to  '/var/lib/wok/plugins/kimchi/isos', but create a patch that guarantee we are keeping the value '/var/lib/kimchi/isos'.

**Comment by alinefm** [comment]
Hi @chandrureddy! Hi @pvital!
As commented on ML, it is better to keep using "/var/lib/kimchi" path to keep compatibility with older Kimchi versions.
So if there is any code that points to a different path than "/var/lib/kimchi" we need to fix it.

**Comment by chandrureddy** [comment]
In this case src/wok/plugins/kimchi/Makefile.am has to be fixed which been changed recently.

**Comment by lcorreia** [comment]
@alinefm @pvital @chandrureddy I'm working on this.

**Comment by lcorreia** [comment]
@alinefm @pvital @chandrureddy I'm working on this.

**Comment by lcorreia** [comment]
Sent 2 patches today to move files back to kimchi tree, including an object store split between Wok and Kimchi.
