### ISSUE TITLE
./autogen.sh --system fails: configure: error: cannot run /bin/sh build-aux/config.sub

### ISSUE THREAD

**Issue by ellie-gar** [kimchi-project/kimchi#741]
When running ./autogen.sh --system, its fails and displays the following error:
**configure: error: cannot run /bin/sh build-aux/config.sub**

**System: CentOS 7  kernel 3.10.0-229.11.1.el7**

 ./autogen.sh --system
configure.ac:44: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:45: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
configure.ac:44: error: required file 'build-aux/config.guess' not found
configure.ac:44:   'automake --add-missing' can install 'config.guess'
configure.ac:44: error: required file 'build-aux/config.sub' not found
configure.ac:44:   'automake --add-missing' can install 'config.sub'
autoreconf: automake failed with exit status: 1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a Python interpreter with version >= 2.6... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python2.7/site-packages
checking for pep8... /usr/bin/pep8
checking python module: unittest... yes
checking python module: cython... yes
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... none
**configure: error: cannot run /bin/sh build-aux/config.sub**

**Comment by pvital** [comment]
I'm going to download CentOS 7 and see what's going on.

**Comment by ellie-gar** [comment]
Silly me, the answer was right there.

**configure.ac:44: 'automake --add-missing' can install 'config.guess'**
**configure.ac:44: 'automake --add-missing' can install 'config.sub'**

automake --add-missing resolves the issue

**Comment by digitalformula** [comment]
> Silly me, the answer was right there.
> 
> **configure.ac:44: 'automake --add-missing' can install 'config.guess'**
> **configure.ac:44: 'automake --add-missing' can install 'config.sub'**
> 
> automake --add-missing resolves the issue

Fixed for me just now, 5 years later.  Thanks!
