### ISSUE TITLE
Wokd service failing to start

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/kimchi#742]
Wokd service is failing to start after installation of wok framework, kimchi and ginger plugins. Steps followed:
1. Clone kimchi code
2. Install wok, kimchi and ginger plugins
3. Start wokd service using either `service wokd start` or `systemctl start wokd.service`

The following output is observed:
```
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] still could not bind()
Traceback (most recent call last):
  File "/usr/bin/wokd", line 101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 98, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 205, in main
    srv = Server(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 73, in __init__
    self.configObj = WokConfig()
  File "/usr/lib/python2.7/site-packages/wok/config.py", line 210, in __init__
    self.update(UIConfig(paths))
  File "/usr/lib/python2.7/site-packages/wok/config.py", line 159, in __init__
    font_dir = getattr(paths, "%s_dir" % font)
AttributeError: 'Paths' object has no attribute 'opensans_dir'
```

**Comment by alinefm** [comment]
Hi @pkulkark! Please, make sure you have OpenSans fonts installed in your system and also do a fresh build before starting the service (make clean && ./autogen --system && make)

**Comment by RockoPB** [comment]
Why did i need this opensans_dir with dependencies of 1,7 GB on ubuntu 15.10? thats not so cool, only for a font. :(

**Comment by gbulfon** [comment]
Hi, I'm porting your wokd/kimchi to our XStreamOS / illumos.
Where do I get these fonts? How can I install them? I need to package them in my distro.

**Comment by pvital** [comment]
@gbulfon the source code are here at GitHub. Just clone the projects and you'll have the source code available to you.

Take a look at the README.md file of https://github.com/kimchi-project/wok to know how to build it, and take a look at the wiki page https://github.com/kimchi-project/wok/wiki/How-to-Work-with-Wok-Submodules to understand how wok and its plugins are connected.

**Comment by gbulfon** [comment]
Hi Paulo,

I already built and packaged the software in my OS, but on startup now it fails looking for OpenSans, same problem as RockoPB, but I don't have that package on my OS, I need to build it too.
Can you provide me a link to the OpenSans package source to be built and packaged?
Or, is there any way to change that requirement to another font I already have?
Thanks!

**Comment by gbulfon** [comment]
I got it ;) downloaded and packeged to install under /usr/share/fonts/... and it works as an illumos service now :)
time for the kimchi now
