### ISSUE TITLE
New navigation bar

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#746]
As we have agreed in the ML, a new navigation bar will be implemented for Kimchi 2.0
It consists in 2 level tabs: one tab represents the plugin (plugin tab) and the 2nd level tabs for the plugin tabs (functional tabs).

![1716678b41c402ea](https://cloud.githubusercontent.com/assets/4921718/10848292/63dd7a68-7f02-11e5-9e9e-8994700c3eb4.jpg)

To do that, we need to change the configuration in the tab-ext.xml file to:
- Add configuration for the plugin tab name
- Change the colour configuration as the colour tab will be for the plugin instead of by functional tab.
(We can also discuss if each functional tab will have a different shade of the plugin tab. For example, 1) if the plugin tab is blue, the functional tabs will have different shades of blue (?) or 2) keep one colour for all the functional tabs (?).
I'd suggest to work with 1) as it may the simpler.)

Once tab-ext.xml is properly configured, we need to edit how Wok loads the plugin (ui/js/src/kimchi.main.js) to create the plugin tab + functional tabs. 
The function buildTabs() must read the plugin tab name from the tab-ext.xml file and the function genTabs() must create one more tab level.

As that modification affects Wok, a patch must be sent to update tab-ext.xml for each plugin: Kimchi, Ginger and Ginger Base.
For Kimchi and Ginger Base, please, send the patch to the Kimchi ML. For Ginger, use the Ginger ML to send the patch for review.

PLEASE, work on top of Samuel's branch: https://github.com/samhenri/kimchi/tree/master

**Comment by walterniklaus** [comment]
Aline, 
based on your proposal above and our discussion on the color coding, here a short summary on what Atreyee will implement:
- use the same basic color for all functionalities of the plugin/1st level Tab
    - Host:              blue
    - Virtualization:  green 
- have the active 2nd level Tab being marked by using a darker shade of blue for host and  a darker shade of green for Virtualization.
The mockup above is showing quite precisely the color coding on the Host Tab.
