### ISSUE TITLE
sosreport generation does not allow underscore in name

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#748]
URI: /plugins/gingerbase/model/debugreports
Action: Post
Post data: {"name": "debugreport_1"}
Output: Error "underscore not allowed in the debug report name."

Investigation:
#sosreport command generate report tar.gz by removing _
And existing upstream code search for file with pattern "sosreport-<name>*" at  /tmp or /var/tmp

Solution:
Parsed the output of sosreport to get the path and name of sosreport generated. instead of searching the pattern "sosreport-<name>*" in /tmp or /var/tmp.

**Comment by ramonmedeiros** [comment]
Hi,

i just opened a bug to take a look at this issue. RH says that RHEL 7.1 fixed this issue. Please, test it

**Comment by alinefm** [comment]
This issue was moved to Ginger Base repository: https://github.com/kimchi-project/gingerbase/issues/7
