### ISSUE TITLE
Debug reports to support s390x platform

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/kimchi#749]
Current upstream code just collects sosreport and tar is moved to /var/lib/kimchi/debugreports.
For s390x platform, dbginfo also need to be collected by running dbginfo.sh along with sosreport.
And final tar of sosreport and dbginfo should get collected and moved to /var/lib/kimchi/debugreports.

**Comment by laggarcia** [comment]
I know this is not related to Kimchi/Ginger, but ideally I think dbginfo call should be included as a plugin to sosreport.

**Comment by alinefm** [comment]
This issue was moved to Ginger Base repository: https://github.com/kimchi-project/gingerbase/issues/6
