### ISSUE TITLE
Unable to get guest memory utilization

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#751]
Kimchi is not able to get the right memory utilization for a running guest.
After a lot of testing on Ubuntu 15.04 and Fedora 22, Kimchi always returns 0%.

After some investigation I noticed Kimchi uses dom.memoryStats() API which does not return the expected values: available and unused.
On my tests it only returns, actual, swap and rss.
```
        memStats = dom.memoryStats()                                                             
        if memStats:                                                            
            memUsed = memStats.get('available') - memStats.get('unused')        
        else:                                                                   
            wok_log.debug('Failed to measure memory usage of the guest.')       
```

Seems the values for available and unused is only supported on newer libvirt versions. But we need to make sure we have it working on Fedora 22, Ubuntu 15.04, openSUSE 13.2 and RHEL 7.1

**Comment by pvital** [comment]
Fix submitted to ML.
