### ISSUE TITLE
[Ginger Base] Debug report is not getting generated using new UI

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#754]
Debug report is not getting generated using new UI.
Click on "Generate" button is not triggering the Debug report or SoS report. Nothing is happenning.

**Comment by alinefm** [comment]
It is working as indeed with the current code (last commit 299832ed895b532dec0847debeac4dfe354b1d5d)

I am closing this issue by now.
Feel free to one a new issue against Ginger Base repository if the problem persists to you.
