### ISSUE TITLE
Host tab information not loading

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/kimchi#759]
On clicking Host tab in gingerbase plugin,it display a blank page. No information is displayed. Browser console displayed error.
![host issue](https://cloud.githubusercontent.com/assets/13199397/11219810/9f239894-8d82-11e5-8e72-559a654f976b.png)

**Comment by alinefm** [comment]
I've just verified and it is working properly on Ubuntu 15.10 and Fedora 23.
I am closing this issue by now.
Feel free to open a new one against Ginger Base if the problem persists to you (as the former Host tab is part of Ginger Base plugin)
