### ISSUE TITLE
Cannot create NFS storage pool by UI

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#761]
How to reproduce:

Try to create a NFS storage by UI. An error will be displayed.

Try to create the same by curl commands:

curl -u root  -H "Content-Type: application/json" -H "Accept: application/json" "http://localhost:8010/plugins/kimchi/storagepools" -X POST -d '{"name":"ramon, "type":"netfs", "source": {"host":"127.0.0.1", "path": "/mnt"}}'

It will run succesfull

**Comment by sstoppler** [comment]
Working on it.

**Comment by ramonmedeiros** [comment]
Hi,

i did a test in a dirty git tree. NFS is working correct.
