### ISSUE TITLE
GingerBase : Repositories section fail to load on Fedora 23

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#765]
GingerBase : Repositories section fail to load on Fedora 23

Environment:
[cpotula@localhost ~]$ uname -a
Linux localhost.localdomain 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
1. install Kimchi WOK and install gingerbase
2. start wokd via 'systemctl start wokd'
3. Browse 'https://localhost:8001/#plugins/gingerbase/host' . Observer no repositories shown.

Logs:
[24/Nov/2015:11:30:40] ENGINE Started monitor thread 'Session cleanup'.
[24/Nov/2015:11:30:40] ENGINE Started monitor thread 'Session cleanup'.
GGBREPOS0014E: Repository management tool was not recognized for your system.

**Comment by lcorreia** [comment]
as requested by @danielhb I am closing this issue and recreating it at gingerbase repo to work on it.
