### ISSUE TITLE
Kimchi : 'Add a Storage' in Storage tab looks odd

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#767]
Kimchi : 'Add a Storage' in Storage tab looks odd compared to other tabs where text is given White but in this case it is black.
![virtualbox_fedora 22_26_11_2015_00_00_43](https://cloud.githubusercontent.com/assets/10830725/11405928/eeed6d1a-93d0-11e5-9130-267a2c30d44b.png)

**Comment by samhenri** [comment]
Patch sent to ML. It was fixed with the new _navbar-flat.scss and new set of _wok-variables.scss in the Media Queries. I'm creating a v2 once I'm able to test Templates (Issue #792).

**Comment by Truja** [comment]
Just tested upstream version and I don't see the problem.
We can close this bug.
