### ISSUE TITLE
Develop support to Live Migration in Kimchi

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#768]
Live migration needs to be implemented on Kimchi UI.

Initial patch was sent to ML with subject:  [Kimchi-devel] [PATCH] Live Migration UI Support.

TODO:  
- Error-handling
- Text not in i18n
- Getting data from user input in UI to be passed in to backend

**Comment by samhenri** [comment]
Applied on master.

**Comment by alinefm** [comment]
Fixed by 74fab9e91cddbfa6b037d29d0c3fe58e5f84c2c1
