### ISSUE TITLE
kimchi dependancy update to gingerbase instead wok

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#769]
kimchi dependancy correction to gingerbase instead wok

Since now the gingerbase is default plugin and plugin kimchi have dependency on gingerbase (like on disks.py) , kimchi should point to gingerbase rather wok.

**Comment by laggarcia** [comment]
Is there a default plug-in now? I thought that wok could run without any plug-ins if needed. Not that wok alone would be very much useful, but maybe someone wants to create an application on top of it that doesn't have anything to do with Kimchi or Ginger, and that should be possible AFAIU.

**Comment by alinefm** [comment]
Hi @laggarcia! You are correct! There is no default plugin linked to wok.

**Comment by alinefm** [comment]
Fixed by 5ea174588ad08134706c5f39edcb03e379b51dab
