### ISSUE TITLE
Kimchi: [New UI] New template is not shown right after creation

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#770]
Run WOK with Kimchi
Go to Template tab and create a new one.
The "Create window" closes and the new template is note shown in the list.
User must click in another tab and back in order to see it.

**Comment by Truja** [comment]
Same happens if you delete a template.
In other words, the template screen is not being updated

**Comment by samhenri** [comment]
Patch sent to the ML.

**Comment by alinefm** [comment]
Fixed by aa51e17bf09284828b564b7857073151513bbb8f
