### ISSUE TITLE
Change name of  Guest or Template returns error "Nothing matches the given URI"

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#771]
There is problem when you update the name of a given Guest or Template.

The name is changed, bu the UI returns the error: Nothing matches the given URI
Also, the window does not close.

**Comment by samhenri** [comment]
Working on it.

**Comment by samhenri** [comment]
I think this might be a back-end issue. The window does close if you edit any other field and succeed the form validation, The expected behavior is to close the window after the name edit but somehow when I click the save button, it returns a 404 on an AJAX request to the new name.

**Comment by Truja** [comment]
Working on this, checking backend/frontend interaction

**Comment by Truja** [comment]
I investigated a little bit more and this is a problem in the backend indeed.
cherrypy.HTTPRedirect is sending a different URL , and UI cannot open it.
This redirect error is seen when you update Guest or Template names. Backend should send the new resource name url and this is not done.

**Comment by samhenri** [comment]
Hi @Truja have you done any other investigation for this? I've tried to create a work-around but I'm out of ideas here.

**Comment by alinefm** [comment]
Hi @samhenri!

As @Truja said, it was a backend issue. I've just removed the UI label.

**Comment by Truja** [comment]
@alinefm  you can close this issue. It if already fixed.

**Comment by alinefm** [comment]
Fixed by 4d7b0a0a10ff13f5a9c3ec5b5cc3c054b15a26f6
