### ISSUE TITLE
Kimchi: [New UI] Template tab and Template edit window - Some problems

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#772]
Problem 1:
If you edit a Template and navegate thought tab you will notice that the "Graphics dropdown" has a different appearance comparing with other dropdown.

Problem 2:
When you go to Storage tab and click on the Format dropdown or Pool dropdown, the list is cut because of the size of the window. Window should be bigger or auto adjust itself.

Problem 3:
Yet in Storages tab, the "Storage Pool" sentence is not being translated, at least to Portuguese

Problem 4:
In Template tab, headers "Template Name (ID)| OS | Version | CPUs | Memory "  are not being translated.

**Comment by samhenri** [comment]
Patch sent to the ML. I've added Pt-BR i18n strings but I haven't checked other languages.

**Comment by alinefm** [comment]
Fixed by 417b042e9092b7a371723c4d7de171e4e3561aa4
