### ISSUE TITLE
Kimchi: [New UI] Snapshot error message showed behind edit window

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#773]
1- Create a Guest with a disk in format RAW (not supported to create snapshot)
2- Edit the guest, go to snapshot tab, click on "Include"

The error message is showed in the Guest window, instead of the "Guest Edit window". It is not possible to read the message, except if you close the window really quickly.

**Comment by samhenri** [comment]
Working on it.

**Comment by samhenri** [comment]
Patch sent to the ML

**Comment by alinefm** [comment]
Fixed by 7507b22c5860b7e099c3fa3cec10f1d7dc89fdcb
