### ISSUE TITLE
Kimchi: [New UI] There is not "Filter" field in Guests and Templates tabs

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#776]
I only see the filter in Storage Pools and Network.
By the way, is works very well, we need it in other tabs

**Comment by andreteodoro** [comment]
I',m working on it.

**Comment by samhenri** [comment]
Patch sent to the ML (Templates tab for now)

**Comment by alinefm** [comment]
Template issue fixed by cbce1ad7807623820a6765c71dc407be3de17cb3

I will close it when get the fix for guests tabs.

**Comment by alinefm** [comment]
Guest fix: 611d9e80e9c28054d79bf73350f2ecc2d9eceba5
