### ISSUE TITLE
Kimchi: [New UI] Storage - "Add Volume" freezes screen

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#778]
Go to Storage Tab, choose a pool and click on Actions -> Add Volume
Click on "Upload a File" and choose any file in your file system.
Click on Add.

Browser screen is going to become whitish and frozen. 

(I did not dig enough, but it is possible to have some problem in backend too)

**Comment by sstoppler** [comment]
Working on it.

**Comment by sstoppler** [comment]
Patch sent to ML for review.

**Comment by alinefm** [comment]
Fixed by 2d525f814b64c47b078db2652637a2a7273a277e
