### ISSUE TITLE
Ginger Base : rpm creation failed on Fedora 22

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/kimchi#779]
Ginger Base : rpm creation faileda on Fedora 22

chmod +x run_tests.sh
make[4]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/tests'
make[3]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/tests'
Making all in ui
make[3]: Entering directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui'
Making all in config
make[4]: Entering directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui/config'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui/config'
Making all in css
make[4]: Entering directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui/css'
make[4]: *** No rule to make target 'src/gingerbase.scss', needed by 'gingerbase.css'.  Stop.
make[4]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui/css'
Makefile:372: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0/ui'
Makefile:606: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0'
Makefile:443: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/chandra/kimchi/src/wok/plugins/gingerbase/rpm/BUILD/ginger-base-2.0.0'
error: Bad exit status from /var/tmp/rpm-tmp.RRMRzq (%build)

**Comment by alinefm** [comment]
This issue was properly moved to Ginger Base repository: https://github.com/kimchi-project/gingerbase/issues/4
