### ISSUE TITLE
Error to create a dir type storage pool

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#782]
I'm not able to create a storage pool using a local directory. The error says "KCHPOOL0026E: Specify name and type to create a storage pool", but it's clearly specified according to the screenshot bellow:

![image](https://cloud.githubusercontent.com/assets/670087/11510025/a4db5346-9848-11e5-92c0-1e010f777917.png)

**Comment by jrziviani** [comment]
I'm working on it.

**Comment by jrziviani** [comment]
I'm working on it.

**Comment by alinefm** [comment]
Fixed by 34c70ca24d8075cf2e5bd383bf30a51b5e7dd859
