### ISSUE TITLE
Error message hidden by the modal window

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#783]
It is not possible to read the whole error message because a modal window is covering up the message.

![image](https://cloud.githubusercontent.com/assets/670087/11510108/15c0fe9e-9849-11e5-83f2-1a60f60e5901.png)

**Comment by samhenri** [comment]
Working on it.

**Comment by samhenri** [comment]
Patch sent to ML.

**Comment by alinefm** [comment]
Fixed by da9e6661f77088fa5a5ffb8eac385e64f89d5ab7
