### ISSUE TITLE
Display a 'loading gif' when waiting for data

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#784]
I found a minor issue when running Kimchi remotely. Sometime it takes time to retrieve and render the content, during this time the content is displayed without any style, as the image shows:

![image](https://cloud.githubusercontent.com/assets/670087/11510516/3a53ac50-984b-11e5-8ba7-bae1a65d04e2.png)

My suggestion is to have a loading gif to display while the content is not ready yet.

**Comment by samhenri** [comment]
Working on it. I'm going to add the "wok loading SVG" for now but for the next release I think we can try some sort of progress bar.

**Comment by samhenri** [comment]
Patch sent to ML.

**Comment by alinefm** [comment]
Fixed by 0d7e872d1db7384bb68f6a3dc8c993a5bf072433
