### ISSUE TITLE
Impossible to create a template from an existing image

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#785]
The **Create** button is always disabled, thus I cannot create a new template based on an existing image.

![image](https://cloud.githubusercontent.com/assets/670087/11512140/e52b7290-9853-11e5-8e27-57024dbd1761.png)

**Comment by sstoppler** [comment]
I am working on this.

**Comment by alinefm** [comment]
Fixed by d1a951160456f9f03da538a5707910881d52f0d9
