### ISSUE TITLE
Kimchi: [New UI] Undefine button is enabled for active Storage pools

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#786]
Go to Storage Pool tab and click on Action button of some active pool.
Button UNDEFINE  will be enabled and is possible to click on it, which will return an error from backend: "Unable to delete active storage pool"

Old UI disables this button if the pool is active, avoiding a request that will always return an error.

Undefine should be enabled (or displayed) only if pool is deactivated.

**Comment by sstoppler** [comment]
I'm working on this.

**Comment by sstoppler** [comment]
Spec states it to be disabled when pool is active.  Is there a preference to disable the button or just hide it when pool is active and show it when pool is inactive?  Thanks.

**Comment by sstoppler** [comment]
Went ahead and implemented according to spec.  Samuel also had to make some adjustments in css to make sure the background for disabled link is according to spec.  That patch has already been applied upstream.

**Comment by sstoppler** [comment]
Patch sent out yesterday to ML for review.

**Comment by alinefm** [comment]
Fixed by e8dce5adc2064ef227e951fce2839a4ece114322
