### ISSUE TITLE
Cannot add remote ISO

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#787]
How to reproduce:

1) Open template tab
2) Try to add new template
3) You won't be able to click em remote image

**Comment by samhenri** [comment]
Hi,

Can you please specify the browser and distro?

I'm able to select it just fine. I'm running on Fedora 20, tested on Google Chrome 47, IE11 and Firefox 44a (Windows) and Firefox 38 (Linux).

![Remote ISO](http://imageshack.com/a/img905/3042/1Fx99Q.png)

I did found one bug with the form validation (clicking on "Provide a URL for a specific ISO image" should unselect all Images) and I'm going to fix that with the other bugfixes for this window (Issue #772)

**Comment by sstoppler** [comment]
I have latest src as of today, running on older version of Ubuntu (14.04), using FF42, Chrome 45.0.2454.101 and I do not see the problem either.

**Comment by alinefm** [comment]
The issue was caused during the wok repository creation when control/config.py was missed.
