### ISSUE TITLE
Include option to specify max_vcpu and current_vcpu separately per guest in kimchi UI

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#790]
The idea is to allow user to change max cpu and current cpu.
Need to decide if allow in template edit window,  in guest edit window , or both.

**Comment by Truja** [comment]
How is the development of this feature ?? Backend is ready.

**Comment by sstoppler** [comment]
Currently working on it.

**Comment by alinefm** [comment]
Fixed by 7128507684cf8fdc66c4ba006688a94b5378104c
