### ISSUE TITLE
New UI for adding network bridges

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#791]
UI changes to reflect the new API options for Kimchi's "add network" scenario.

Network tab -> User clicks on add (+) button

Currently, there are 3 options in "Network Type": Isolated, NAT, Bridged (which as of now sets macvtap or bridges according to the destination chosen by user).

The API is changing for Kimchi 2.0: Bridged option will be split into
2 options:
- "Bridged" option will now be used for creating networks tied to Linux bridges or OVS bridges
- "macvtap" option will be added for creating macvtap networks.

Bridged option new behaviour:
1) Change description of "Bridged" option to refer to Linux bridges and OVS bridges (no more direct connections)
2) When "Bridged" is selected, "Destination" will show all the interfaces it currently shows plus OVS bridges
3) "Enable VLAN" will only be showed if user selects a NIC or bonding from "Destination" pop-up (alternatively, we can show it always and block the usage of VLAN with NIC or bonding selected)
4) "Bridged" option will call network_create API with "bridge" as value for "connection" parameter

New macvtap option:
5) Add a new option "macvtap" to Network Type, with same current description of today's Bridged option
6) When macvtap option is selected, "Destination" will show only NICs and bondings. It will NOT show any kind of bridges anymore.
7) "Enable VLAN" option is NOT showed
8) macvtap option will call network create API with "macvtap" as "connection" parameter value.

**Comment by peterpennings** [comment]
Is kimchi.getInterfaces() already configured to show NIC and bondings in case of macvtap option? Or is there a specific endpoint to get the Destination values for macvtap?
![screenshot](https://cloud.githubusercontent.com/assets/15019111/12579882/72f3c05c-c412-11e5-9ad6-7a49a90a6a69.png)

**Comment by sstoppler** [comment]
Fixed by https://github.com/kimchi-project/kimchi/commit/9aca4d7e2334a623f9c3a040a992845934af9c1e
