### ISSUE TITLE
./autogen.sh with No package 'systemd' found

### ISSUE THREAD

**Issue by mutty** [kimchi-project/kimchi#794]
I am using ubuntu1404 for kimchi. 

it showes below when execute `./autogen.sh --system`. 

``` bash
Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found
```

**After `make` and `make install`, kimchid command can not be found.**

It makes me confused about how to install Wok in ubuntu, `wokd` command cannot be found. 

``` bash
hello@ubuntu:~/workspace/kimchi-master$ wok
WARNING:root:Textile not enabled.
CRITICAL:root:This doesn't look like a wok site. Aborting.
hello@ubuntu:~/workspace/kimchi-master$ wokd
wokd: command not found
hello@ubuntu:~/workspace/kimchi-master$ 
```

Would you please give me a hand?

**Comment by d0lph1n98** [comment]
Same problem on ubuntu 16.04.1, do i need to install wok separately? https://github.com/kimchi-project/wok/

**Comment by gabriellluz** [comment]
Same for me.

**Comment by alinefm** [comment]
Closing this issue as it is fixed now.
