### ISSUE TITLE
Jquery-bootgrid plugin library js file is having syntax error

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/kimchi#795]
While page is loaded Jquery-bootgrid plugin library js file jquery.bootgrid.min.js is showing sysntax error. 
As a result bootgrid components in ginger storage and networking tab are not working.

![jb issue](https://cloud.githubusercontent.com/assets/13199397/11779361/7fc47654-a280-11e5-9039-1edc0d65c2e0.png)
I will send a patch to replace the file with correct jquery.bootgrid.min.js

**Comment by alinefm** [comment]
It is related to WOK! Please, open an issue against WOK repository.
