### ISSUE TITLE
Cannot build kimchi out of wok structure

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#798]
Distro: Ubuntu 15.10 x86_64
Tried to clone kimchi separately from wok and could not build it due to error below. The same problem occurs trying to build kimchi in wok tree before building wok itself.

Compiling .scss file src/kimchi.scss
sassc -s expanded src/kimchi.scss kimchi.css
sassc: error: Error: File to import not found or unreadable: ../../../../../../../ui/css/src/modules/wok-variables
       Parent style sheet: /home/dev/kimchi/ui/css/src/kimchi.scss
        on line 20 of src/kimchi.scss
>> @import "../../../../../../../ui/css/src/modules/wok-variables";
   ^

Makefile:521: recipe for target 'kimchi.css' failed
make[3]: *** [kimchi.css] Error 1
make[3]: Leaving directory '/home/dev/kimchi/ui/css'
Makefile:377: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/dev/kimchi/ui'
Makefile:607: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dev/kimchi'
Makefile:446: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pvital** [comment]
This happens because the Kimchi code is importing a file that needs Wok source code cloned before. In Ginger and Ginger Base projects was decided to explain in README file that if you are building the projects by their source code, you need Wok (and other projects if necessary) source code clone before.

**Comment by danielhb** [comment]
Kimchi README already mention WoK and Gingebase dependencies.
