### ISSUE TITLE
Gallery/List view: Remember user selection when switching tabs

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#799]
How to reproduce:

1. Go to Templates tab
2. Select Gallery view
3. Switch to another tab
4. Go back to Templates tab

Expected behavior:
Gallery view is displayed on Templates tab

Actual behavior:
List view is displayed on Templates tab

We should remember the user selection (probably by a browser cookie) to load the right view when going back to a tab.

I am not sure it is specific for Kimchi (as it is the first plugin adding different views for a tab) or it should be part of Wok to enable that on all plugins.
But we can discuss that and move the issue to Wok if needed.

**Comment by sstoppler** [comment]
Patch sent to ML for review.

**Comment by alinefm** [comment]
Fixed by b5c291bd803dcfaa5103b3a383810831d39c40d5 0a0f5d4e6d716c2a4222d68e09cc69a2d00b673f
