### ISSUE TITLE
Kimchi shows opensuse Leap 42.1 image as "unknown" OS

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/kimchi#800]
When creating a template/guest from opensuse Leap 42.1, Kimchi does not recognize it as opensuse and labels it as unknown OS.

**Comment by ramonmedeiros** [comment]
I will take it

**Comment by ramonmedeiros** [comment]
Patch sent

**Comment by alinefm** [comment]
Fixed by 96f1c491
