### ISSUE TITLE
Update list of remote templates

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#802]
The list of remote templates does not show the newest distros available such as Fedora 23 or Ubuntu 15-10. It is a good idea to replace those older distros.

![image](https://cloud.githubusercontent.com/assets/670087/12022490/4f64ee10-ad77-11e5-8ff6-127d338f8a97.png)

Thanks

**Comment by cd1** [comment]
Related to #611.

**Comment by alinefm** [comment]
The remote ISOs were updated recently (from cd2707a4f7a7f9252d47d3f93ec26bcfb40a34d7 to e6f21dbd5a0b0dcb9251ec8349c795722167a8ac)

But as commented by @cd1, the real solution should query automatically the remote ISOs - #611.
