### ISSUE TITLE
Change guest name throws "Nothing matches the given URI" error

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#803]
After login, go to **Virtualization** tab, select **Guests**,  then select **Edit** under **Actions** menu of any VM available - which must be stopped.

The editor window will pop up, then change the name like the screenshot bellow:

* ***from***:
![image](https://cloud.githubusercontent.com/assets/670087/12022635/bfe46980-ad78-11e5-9773-67b77811a2f2.png)

* ***to***:
![image](https://cloud.githubusercontent.com/assets/670087/12022682/3e89593a-ad79-11e5-8773-2d068daa15b5.png)

Clieck **Save** button and you will get the error described in the issue "Nothing matches the given URI".
![image](https://cloud.githubusercontent.com/assets/670087/12022695/6fd1de68-ad79-11e5-8b42-c72b5fcca1f1.png)

* Note 1: VM was updated, it's displayed in the list of VMs.
* Note 2: The editor window won't close until you click **Cancel**
* Note 3: If you click **Save** again you will get: *KCHVM0002E: Virtual machine testes2 does not exist*

**Comment by alinefm** [comment]
Fixed by https://github.com/kimchi-project/wok/commit/4d7b0a0a10ff13f5a9c3ec5b5cc3c054b15a26f6
