### ISSUE TITLE
Disable "Connect VNC" when the VM is stopped

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#804]
There is no need to open a VNC to a stopped VM. If we do this we will get an error, I think we could either:

* disable the **Connect VNC*** option from the **Actions** menu when the VM is stopped - **OR**
* make **Connect VNC** starts the VM selected and then opens a VNC to it.

**Comment by laggarcia** [comment]
I think it should be disabled if the VM is not running.

**Comment by jrziviani** [comment]
Patch sent to review

**Comment by alinefm** [comment]
Fixed by 28261d4cc545c900b086427b2e7fb2fa958f1de6
