### ISSUE TITLE
[feature] Use an input file to select storage

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#805]
IMHO it would be easier if we have a input file (already opening the default /var/lib/libvirt/images folder) to select the disk we want to attach instead of a simple input text. If we could have an editable input file would be awesome.

Look at the screenshot bellow, it's (almost) impossible to remember the full path every time you need to attach something. Users certainly have to open the terminal to list the valid options... 
![image](https://cloud.githubusercontent.com/assets/670087/12022946/a38258f8-ad7b-11e5-890a-5c16b0c3796c.png)

Thanks

**Comment by jrziviani** [comment]
I was thinking a bit more about it and realize that an input file will display the files locally. To display files remotely it would require more work. Anyway I'll let this issue opened to see if I have a better idea on how to improve it.

**Comment by cd1** [comment]
This issue seems to be a duplicate of #170.

**Comment by jrziviani** [comment]
Duplicate of #170
