### ISSUE TITLE
Cannot hot-plug a disk from my storage pool

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#807]
I created a new image directly in /var/lib/libvirt/images:
![image](https://cloud.githubusercontent.com/assets/670087/12023541/a4ec74e8-ad81-11e5-9206-7e1bfd18af93.png)

Now I want to hot-plug such image to my running VM, but there is nothing to select:
![image](https://cloud.githubusercontent.com/assets/670087/12023565/db483400-ad81-11e5-97ff-dfe983cd5fd5.png)

* Note: I'm able to attach a cdrom

**Comment by alinefm** [comment]
Fixed by 3557365fbc43275dadc0acb0aad3eef5a8192d8d
