### ISSUE TITLE
Cannot 'cold-plug' a disk into my VM

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#808]
I tried to attach a new disk to my VM (it is stopped) but I get the error in the screenshot bellow:

![image](https://cloud.githubusercontent.com/assets/670087/12023610/48ac0350-ad82-11e5-81e5-8a3d7871cdd1.png)

**Comment by alinefm** [comment]
Fixed by 3557365fbc43275dadc0acb0aad3eef5a8192d8d
