### ISSUE TITLE
PCI filter does not seem to work

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#809]
Open the **Edit** window for any VM and navigate to **Pci** tab. Try to use the filter, I was not able to filter anything by typing values in the text field.

![image](https://cloud.githubusercontent.com/assets/670087/12023678/e7e9bb74-ad82-11e5-97cb-cf6a09b7124e.png)

![image](https://cloud.githubusercontent.com/assets/670087/12023716/4a5fbe2a-ad83-11e5-910e-4c8ed7fd62a8.png)

* Note: the drop-down menu (***ALL***, ***To Add***, and ***Added***) seems to work fine.

**Comment by samhenri** [comment]
Patch sent to the mailing list. Library necessary to fix the filter was applied in Wok.
