### ISSUE TITLE
[UI] [Kimchi] UI just show exported NFS path when clicked twice at field

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#814]
How to reproduce:

1) Setup a nfs server and export a directory:
echo "/mnt      0.0.0.0/255.255.255.0(rw,no_root_squash)" >> /etc/exports

2) Input IP and name for the storage pool at Kimchi UI

3) When you first click at exported directoy, nothing will appear, then, if you click out and click again, the UI will show you the directory exported.

**Comment by ramonmedeiros** [comment]
Hi,

instead of using 0.0.0.0, i used 127.0.0.1. Nfs is mounting correctly. But UI still got trouble to show the exported path at first click

**Comment by samhenri** [comment]
Not sure if I "fixed" this issue yet, can you apply the patch I've sent to the ML and try again? I've exported two different directories in a NFS server and noticed some bugs with the IP address and NFS path dropdowns when the list is empty and sent a patch to fix them.

**Comment by alinefm** [comment]
Fixed by 919de4fd40a5e9cf089c2c509d2f167952c980b0
