### ISSUE TITLE
[Storage] Cannot add detached disk to VM

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#815]
How to reproduce:

1) Create a new guest from a CD template 
2) Detach the empty disk 
3) Try to attach it (An error will be displayed)

About this bug, it's designed to avoid adding blank disks?

**Comment by alinefm** [comment]
Hi @ramonmedeiros 

Which error is displayed?

**Comment by alinefm** [comment]
Seems it is duplicated of #808

**Comment by alinefm** [comment]
Please, feel free to reopen if the problem persists.
