### ISSUE TITLE
Frontend doesn't update the PCI tab after a PCI attachment

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#818]
Navigate to **Virtualization** → **Guests**. Click on **Actions** of any *stopped* guest and **Edit**. The **Edit Guest** window will pop up, then navigate to **Pci**.

Click to attach a device to that guest, you won't get any feedback unless you close the **Edit Guest** window and reopen it back. Then, if you choose to detach the device will click on the de device, like the image bellow:
![image](https://cloud.githubusercontent.com/assets/670087/12150659/2a83d63e-b492-11e5-9146-1980561f3ef4.png)

This time will you get a feedback (the button at right has changed), but the green signal doesn't:
![image](https://cloud.githubusercontent.com/assets/670087/12150745/a701c4be-b492-11e5-9cc1-10682ce9bca6.png)

A similar behavior can be seen if the guest is running.

**Comment by samhenri** [comment]
Patch sent to the mailing list.
