### ISSUE TITLE
template creation fails if there is no storagepool named "default"

### ISSUE THREAD

**Issue by pwuestef** [kimchi-project/kimchi#819]
As already stated in the subject, this happens if a storage pool named "default" does not exist while trying to define a new template:

KCHTMPL0004E: Storage pool /plugins/kimchi/storagepools/default specified for template debian8.2.1452173843118 does not exist

This is although multiple valid and active storage pools exist.

After definition of a storage pool named "default" the error message changes to:

KCHTMPL0005E: Storage pool default specified for template debian8.2.1452173793108 is not active

 wok                                 2.0.0 
kimchi                              2.0.0 
ginger-base                     2.0.0

cat /etc/os-release 
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"

Linux xxx20 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

After activation of storage pool "default" creation of a new template is possible. This template contains "default" as the storage pool. Therefore, to be usable the template has to be edited.

FEATURE REQUEST:
Allow selection of storage pool at template creation time

Thanks,
Peter

**Comment by alinefm** [comment]
Hi @pwuestef !

The default values for a template are defined in a configuration file (/etc/kimchi/templates.conf)
If you don't want to use the 'default' pool as default in your templates, please, update the configuration file accordingly.

**Comment by pwuestef** [comment]
Hi @alinefm !

That would seem natural to me, but the kimchi package 2.0.0.0 for ubuntu did not contain that templates file. Within that package there were these files:

/etc/kimchi
/etc/kimchi/distros.d
/etc/kimchi/distros.d/debian.json
/etc/kimchi/distros.d/fedora.json
/etc/kimchi/distros.d/ubuntu.json
/etc/kimchi/distros.d/opensuse.json
/etc/kimchi/distros.d/gentoo.json

Instead, I found a template.conf in /etc/wok/plugins.d/template.conf and this file contained the lines
........................................
[storage]

# Specify multiple [[disk.X]] sub-sections to add multiples disks to guest
# Each disk files will be created in respective storage pool set
[[disk.0]]
# Disk size in GB
#size = 10

# Disk format
#format = qcow2

# Storage pool used to handle the guest disk
#pool = default
........................................
I assume that I could modify the storage pool to pick here (didn't test it though). 

But what I would like to point out is that it seems more natural to me to search through the existing storage pools and present them in the template dialog to pick from. At least that would elimitate the error message I encountered, and after the template is initially created obviously the list of storage pools is read. It is just that when creating the template this is a very possible stone to stumble over.

Thanks!
Peter
