### ISSUE TITLE
Kimchi won't install on Kubuntu 15.10; it hangs

### ISSUE THREAD

**Issue by JesseTG** [kimchi-project/kimchi#821]
When I try to install Kimchi from the official repos on Kubuntu 15.10 64-bit, `apt-get` starts to install it...then nothing.  No output, it just hangs.  I think the installer might have hit an infinite loop or a deadlock or something.  I had to stop installation, but now even `dpkg` can't uninstall it, so I can't install or remove any packages from my system until this is fixed!

**Comment by RockoPB** [comment]
I've the same problem here. Found out, that this process was hanging: /bin/sh /var/lib/dpkg/info/kimchi.postinst configure
After some research i saw, that the /lib/systemd/system/kimchi.service file is wrong in the ubuntu package.
This entry in the file is right:
Requires=libvirt-bin.service
After=libvirt-bin.service

instead of this wrong configuration:
Requires=libvirtd.service
After=libvirtd.service

After changing this and restart the kimchi service with 
service kimchi restart

the package installation in another window finished the installation

**Comment by RockoPB** [comment]
And: /etc/pam.d/kichmi is wrong. instead of libvirt the group should be libvirtd
auth     sufficient  pam_succeed_if.so user ingroup libvirtd
instead of
auth     sufficient  pam_succeed_if.so user ingroup libvirt

**Comment by computergeek125** [comment]
I can confirm that @RockoPB 's workaround with the systemd script works in Ubuntu 15.10 Desktop (Linux 4.2.0-27-generic).  Thanks for the tip!

**Comment by alinefm** [comment]
Closing based on last comments.

**Comment by alinefm** [comment]
The  /lib/systemd/system/kimchi.service file was already ficed by 2.1 release according to #816

**Comment by computergeek125** [comment]
So that would explain it: Ubuntu is using a version of 1.5.0 in their repo (1.5.0-0ubuntu1)

**Comment by philled** [comment]
I installed using "sudo apt-get install kimchi" and made the changes to /lib/systemd/system/kimchi.service and /etc/pam.d/kichmi as recommended. But when I try to browse to kimchi from a remote PC no page comes up. I'm trying these URLs:

http://192.168.0.102:8000/
http://192.168.0.102:8001/
http://192.168.0.102:8010/
http2://192.168.0.102:8000/
http2://192.168.0.102:8001/
http2://192.168.0.102:8010/

I can get a telnet connection on the localhost:
telnet localhost 8010
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

But not when I do it try it from another machine.

In /etc/kimich.conf I have:
[server]
# Start the proxy service?
#run_proxy = off

# Hostname or IP address to listen on
###host = 0.0.0.0
host = 192.168.0.102

# Port to listen on
###port = 8000
port = 8000

# If present, start an SSL-enabled server on the given port
###ssl_port = 8001
ssl_port = 8001

# Cherrypy server port
###cherrypy_port = 8010
cherrypy_port = 8010

etc...

Any suggestions as to what may be wrong? Do I have to do something to nginx conf?

**Comment by vmorris** [comment]
This is still a problem in Xenial 16.04.1 -- please get this up into the ubuntu repos :+1:

**Comment by davidzengxhsh** [comment]
The last step is still hang with Ubuntu 16.10.  I even can NOT get out with Ctrl-C.

**Comment by Trolldemorted** [comment]
@alinefm we are running a brand-new ubuntu 16.10 `apt-get install kimchi` freezes. could you re-open this issue?

**Comment by Raven283** [comment]
Also tried to install on a fresh ubuntu server 16.04 install. First did an update/upgrade cycle followed by `sudo apt-get install kimchi`, hangs on `Setting up kimchi (1.5.0-0ubuntu1) ...`, I can see the command `/bin/sh /var/lib/dpkg/info/kimchi.postinst configure` running with ps

**Comment by alinefm** [comment]
Hi @Raven283 

Please, do not install Kimchi using apt. The package available there is too old (it is 1.5.0 version and latest Kimchi release is 2.4.0) and does not work due several issues.

To install Kimchi, get the packages available at http://kimchi-project.github.io/kimchi/downloads/

**Comment by Trolldemorted** [comment]
You probably should remove that package, if possible.

**Comment by alinefm** [comment]
@Trolldemorted There is an open request against Ubuntu community to do that.
