### ISSUE TITLE
Clone one VM multiple times at the same time.

### ISSUE THREAD

**Issue by pvital** [kimchi-project/kimchi#837]
As a user, I want to clone one specific VM into multiple VMs at the same time so that I can have multiple VMs at the same datecenter.

This is supported by backend, since create clone is an asynchronous job. Need only change UI to get from user how many clones is expected and then create the same number of requests to backend.

**Comment by alinefm** [comment]
Fixed by 13dc7a32cffafc3e86241934c2235c2a78241b52
