### ISSUE TITLE
RHEL 7.2: Unable to start virtual machine due memory hotplug issue

### ISSUE THREAD

**Issue by nrigaud** [kimchi-project/kimchi#838]
Hello,

I am actually trying to use Kimchi on Centos 7 (1511). (On a recent IBM X86 Server with a xeon processor).
It has been installed from git source. Kimchi version is 2.0.0-0

I tried to create some virtual machines (a debian 8 one, and a Win7).
But i can't start any of them, Kimchi gives me the following message:

> "KCHVM0019E: Unable to start virtual machine Test. Details: unsupported configuration: memory hotplug isn't supported by this QEMU binary"

I then have a look at journalctl which gives me the same message:
> janv. 15 13:34:51 localhost.localdomain libvirtd[32631]: unsupported configuration: memory hotplug isn't supported by this QEMU binary

Well, i then go to virsh to verify the qemu version, it gives me : 
> virsh # version
> Compiled against library: libvirt 1.2.17
> Using library: libvirt 1.2.17
> Utilisation de l'API : QEMU 1.2.17
> Exécution de l'hyperviseur : QEMU 1.5.3

But as far as i know, QEMU supports memory hotplug since version 2.1.

RHEL 7.2 is using the same binary.

Is this a normal behaviour?

Thank you!

**Comment by laggarcia** [comment]
It seems from your "virsh version" output that you have QEMU 1.5.3 installed in CentOS 7. As you said QEMU memory hotplug is supported since versoin 2.1, that's probably why you are getting this error message.

**Comment by nrigaud** [comment]
Thank you for your answer.
I agree that it seems to be the reason why i have this message.

But i am wondering if this is wanted.
Centos or RHEL 7.2 are recent distributions, i thought it would work because RHEL is documented in the README.

If there is a minimal QEMU version required, there may be a warning somewhere in the documentation.

Best regards.

**Comment by nrigaud** [comment]
I discovered that Red Hat Enterprise Virtualization provides a more recent version of QEMU.
So, i did the following:
I took the SRPMS from: http://ftp.redhat.com/pub/redhat/linux/enterprise/7Server/en/RHEV/SRPMS/
Il compiled and installed them on my CENTOS server.

QEMU is now in version 2.3.0.
Now it is possible to start the virtual machines.

Thanks
