### ISSUE TITLE
Make Kimchi distinguish between local ISO Image from disk Image Files

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#841]
We had some discussion in Kimchi mailing list about this bug in thread:
"[Kimchi-devel] [RFC] Change template creation media input"

According to RFC, there is not need to have 2 tabs in Kimchi, one to provide a local ISO and another to provide .img disk files. We can have one screen  with one input field.

**Comment by ramonmedeiros** [comment]
This issue is for backend or frontend? I sent a patch about this last year:

http://lists.ovirt.org/pipermail/kimchi-devel/2015-December/013253.html

**Comment by sstoppler** [comment]
This issue is for UI

**Comment by alinefm** [comment]
Fixed by fc9ecd519624cba85e0e92ecec4245555bcc9dbc
