### ISSUE TITLE
Add //# sourceURL=kimchi.min.js when creating kimchi.min.js

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#843]
In order to debug dynamically loaded javascript code it's necessary to add
```javascript
//# sourceURL=kimchi.min.js
```
at the end of the source file.

Source: https://developer.chrome.com/devtools/docs/javascript-debugging
Breakpoints in Dynamic JavaScript

**Comment by jrziviani** [comment]
Sent patch to implement it upstream.

![image](https://cloud.githubusercontent.com/assets/670087/13056280/946447cc-d3fb-11e5-875e-573e7cd4474b.png)

**Comment by alinefm** [comment]
Fixed by 3de4eed7ef7685dd03c1b74fae38fe229c15a16c
