### ISSUE TITLE
Kimchi won't recognize existing VGs

### ISSUE THREAD

**Issue by impo** [kimchi-project/kimchi#853]
Discussed over IRC with @alinefm 

I am unable to add logical storage to existing VGs. The web interface returns "No LVM found in the system."

System: CentOS 7 x86_64 Minimal

`vgs --units b --nosuffix --noheading --unbuffered --options vg_name,vg_size,vg_free` returns:
  centos-main 127506841600 67108864
  DummyVG 320067338240 320067338240

Opening up a Python interpreter in the root of the source tree, importing `disks`, and running `disks.vgs()` returns:
[{'vgname': 'centos-main', 'free': 67108864L, 'size': 127506841600L}, {'vgname': 'DummyVG', 'free': 320067338240L, 'size': 320067338240L}]

However, the web interface asserts that there is no existing LVM on the system.

Logging into Kimchi with Firebug, the request for the existing VGs on the system goes through successfully, but returns empty JSON data: []. 

Manually querying the API over /plugins/kimchi/host/vgs also returns empty JSON. Querying other URIs in the API, however, returns the correct JSON data.

**Comment by alinefm** [comment]
Hi @jrziviani!

Do you know there is some filter while listing the VGs?

**Comment by jrziviani** [comment]
@alinefm Hi! it seems this commit (https://github.com/kimchi-project/kimchi/commit/ded9d91ac364df691ff4927675ec6b864e12dfd3) broke this feature when it changed 
```
-from wok.plugins.kimchi import disks
 +from wok.plugins.gingerbase import disks
```
I'm working on it

**Comment by alinefm** [comment]
Fixed by https://github.com/kimchi-project/gingerbase/commit/10d4ec5737a860e8afa4a7714dd7a3be93a329b4

**Comment by alinefm** [comment]
Hi @impo!

To get the fix, you will need to get the gingerbase upstream code or wait for 2.1 release (Mar 25th)
