### ISSUE TITLE
[CentOS7] Kimchid.service not present

### ISSUE THREAD

**Issue by OnigamiSama** [kimchi-project/kimchi#854]
I installed ginger-base and wok with the package on the website as well as kimchi but when I do "sudo systemctl enable kimchid.service" I get "failed to execute operation: acces denied" and when I do "sudo systemctl start kimchid.service" I get "Failed to start kimchid.service: unit kimchid.service failed to load: No such file or directory."

On a fresh CentOS7 install in virtualbox

**Comment by laggarcia** [comment]
In Kimchi 2.0 the service has been renamed to wokd.

**Comment by OnigamiSama** [comment]
Ok so as long as workd is running it should be good ? because https://localhost:8001 doesn't display anything, but it's an other kind of issue so we can close that one, thanks
