### ISSUE TITLE
Unable to create bridged network if iwith NetworkManager disabled

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#858]
When I tried to create a bridged network, a warning message was displayed asking to disable NetworkManager. Even after disabling this service, the warning message keeps showing and I was not able to created the bridged network.
I needed to restart the wokd service to make it works.

IMO the user should not need to restart wokd after disabling NetworkManager.

Verified on Fedora 23.

**Comment by alinefm** [comment]
Still applies to CentOS 7

**Comment by ramonmedeiros** [comment]
I can't reproduce this bug in upstream. Thanks
