### ISSUE TITLE
CentOS 7 image not recognized

### ISSUE THREAD

**Issue by scrat14** [kimchi-project/kimchi#861]
CentOS 7 x86_64 minimal ISO is labeld "CentOS 7 x86_64", so operating system is not recognized by Kimchi.

**Comment by Truja** [comment]
I have just sent a new patch to fix this:
[PATCH][Kimchi] Add support to recognize latest	CentOS version

**Comment by alinefm** [comment]
Fixed by 283468560b68731a7f2a7e82f438d52bcd887e19
