### ISSUE TITLE
Incomplete (wrong) information displayed for existing template when adding new Guest

### ISSUE THREAD

**Issue by pvital** [kimchi-project/kimchi#862]
Virtualization -> Guests -> Add a Guest" panel currently shows incomplete information on the defined templates available. 

Number of CPUs and Memory is not correct/displayed.

![screenshot from 2016-03-16 09-24-46](https://cloud.githubusercontent.com/assets/699330/13812114/f5b3fbd4-eb58-11e5-9429-e03d94fed98f.png)

**Comment by alinefm** [comment]
Fixed by 38d71862669bc3bd6f3dc51cfea61cbe5e7c84fd
