### ISSUE TITLE
Kimchi is not listed on libvirt.org

### ISSUE THREAD

**Issue by lxp** [kimchi-project/kimchi#863]
Kimchi should be listed on this page: https://libvirt.org/apps.html

**Comment by ramonmedeiros** [comment]
Please assign this to me. Just sent the patch:

https://www.redhat.com/archives/libvir-list/2016-July/msg00510.html

**Comment by ramonmedeiros** [comment]
Patch merged and kimchi is listed now:

http://libvirt.org/apps.html#web

**Comment by danielhb** [comment]
Gratz!
