### ISSUE TITLE
[UI] Error message KCHISO0008E (and possibly others) fade-out timer

### ISSUE THREAD

**Issue by ghidasy** [kimchi-project/kimchi#875]
The red box with the text for error message KCHISO0008E disappears in 5 seconds, even if the user tries to stop it by mouse click or hover.

Its a large message, this fade out is too fast to be read and understood, requiring the user to cause the error multiple times, copy the content of the message and paste it in an editor or screenshot it to react accordingly.

**Comment by alinefm** [comment]
Solved on Wok (https://github.com/kimchi-project/wok/commit/e2c50250617ede4192ba8c25e70a6ac7de4f4948)
