### ISSUE TITLE
could i use http://localhost:8001 to get all pages and data

### ISSUE THREAD

**Issue by hanjiabao** [kimchi-project/kimchi#922]
how to change https to http to get webpage?$.ajax() may use http receive data from fedora or ubuntu,if couldn't use http,what for the reason.

**Comment by ramonmedeiros** [comment]
I did not understand your question, but, when i run curl, usually point to localhost:8010, where the server runs in plain text. To get all templates, for example, you can run:

curl -u root -H "Content-Type: application/json" -H "Accept: application/json" -k http://localhost:8010/plugins/kimchi/templates -X GET

For mor REST API commands, see API.md

**Comment by hanjiabao** [comment]
thanks,ramonmedeiros
my OS:Fedora release 22 (Twenty Two), kimchi version:1.5.1,
web url:when i input "{ip}:8000",nginx proxy this url to "https://{ip}:8001",every time i open the web web url is https:{ip}:8001,so i think if i can do some changes in order that nginx proxy url "{ip}:8000" to http://{ip}:8001,not https://{ip}:8001.this web view
what you said is to use curl cmd to display result, and no nginx server.if i don't use nginx how  "{ip}:port" in web url succeed as "https://{ip}:8001" show to us.

**Comment by alinefm** [comment]
Hi @hanjiabao 

Do you want to disabled HTTPS? And only access Kimchi using HTTP?
Why do you want to do that? HTTPS is properly configured for security matters.

**Comment by hanjiabao** [comment]
boos ask to do this，and it has been done already

**Comment by pvital** [comment]
@hanjiabao would be nice if you share with us how did you do that.

**Comment by hanjiabao** [comment]
@pvital,
ok,i think it would be nice to share with you,i  just see there,and i should be ready for sharing for a while

**Comment by alinefm** [comment]
Anything to do on this issue or can it be closed?
