### ISSUE TITLE
Windows Versions 8+ BSOD system_thread_exception on Install and Boot

### ISSUE THREAD

**Issue by abarlam** [kimchi-project/kimchi#926]
When trying to boot any Windows iso > v 8, I would get a BSOD and constant reboot saying Windows will 
"Restart to repair drive errors".  

I ended up having to use virsh edit "vm-name" command and then adding the following:

`<features>
  <kvm>
      <hidden state='on'/>
    </kvm>
  </features>
  <cpu mode='custom' match='exact'>
    <model fallback='allow'>core2duo</model>
    <feature policy='require' name='nx'/>
    <numa>
      <cell id='0' cpus='0' memory='1048576' unit='KiB'/>
    </numa>
  </cpu>`

This allowed me to boot and continue install and subsequent reboot into vm.  I don't have a core2duo, i actually have an i7 sandy bridge, but when I tried removing some of the statements after successful install, it would still receive the BSOD.

System Information:

Intel i7 2600+ 3.4GHz (sandy bridge)
Ubuntu 15.10
Linux kernel 4.2.0-16-generic #19-Ubuntu SMP x86_64
Gingerbase 2.1.0-0
Kimchi 2.1.0-0

**Comment by jonathonwiebe** [comment]
This would be a KVM/QEMU issue and not a problem with Kimchi. See this thread dated 2015: https://ubuntuforums.org/showthread.php?t=2289210

**Comment by alinefm** [comment]
Closing based on last comment. Please, reopen if necessary.
