### ISSUE TITLE
Feature-Request: Show the VM size on the host

### ISSUE THREAD

**Issue by romu70** [kimchi-project/kimchi#927]
Hi,
Kimchi is great, really, thanks to the team!

It could be even better. Problem with KVM ans QCOW is the files on the host storage can get very big and will need some shrinking procedure. So it would be nice if we could see the VM size on the physical storage in the Kimchi interface.

**Comment by pvital** [comment]
@romu70 interesting.

So, only to confirm if I understood well. You want to know on guests tab, the total amount of all disks allocated to a specific VM, right?

**Comment by romu70** [comment]
Exactly.

**Comment by alinefm** [comment]
Hi @romu70 

We are currently working on Storage volume management interface.
It will be under Storage tab. When selecting a given storage pool it will list all the storage volumes.
Maybe you can get there the information you want as the storage volume API already returns which VMs use which disks.
Do you think it will be enough?

**Comment by romu70** [comment]
Yes, perfect @alinefm , thanks.

**Comment by alinefm** [comment]
Patches related to storage volume management applied upstream: c9ea5072bff5f87fd35c95d8e55c55d3e2a394d2

@romu70 any feedback is more than welcome.

I will close this issue by now as the solution available should fit your needs.

**Comment by romu70** [comment]
Perfect, thanks a lot.
