### ISSUE TITLE
Disabled button triggers actions on storage tab

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/kimchi#928]
Navigate to **Storage** tab, click on **Actions** and select a disabled button, like the screenshot bellow:

![image](https://cloud.githubusercontent.com/assets/670087/14535487/7e902a8e-0244-11e6-8504-25b91704f062.png)

The button will work like enabled:

![image](https://cloud.githubusercontent.com/assets/670087/14535533/b7000d9e-0244-11e6-9236-819659ce9bb9.png)

**Comment by alinefm** [comment]
Fixed by 2be8daa352715fc51e16a37aac04ce956f397486
