### ISSUE TITLE
Invalid image path not marking template as "invalid" (back-end)

### ISSUE THREAD

**Issue by samhenri** [kimchi-project/kimchi#933]
Steps to reproduce:

1- Create a new template pointing to an image in file path (ex: /var/lib/libvirt/images/c8fd16b3-fd9b-452f-b4bb-4be9ebe8a011-0-0.img)
2- Rename or remove this file
3- Reload page. Inspecting the templates response in Chrome Dev Tools returns this:
```
{
  "cpu_info":{
    "maxvcpus":1,
    "vcpus":1,
    "topology":{}
  },
  "graphics":{
    "type":"vnc",
    "listen":"127.0.0.1"
  },
  "cdrom":null,
  "networks":[
    "default"
  ],
  "icon":"plugins/kimchi/images/icon-vm.png",
  "os_distro":"unknown",
  "name":"fedora-disk",
  "disks":[
    {
      "index":0,
      "format":"qcow2",
      "base":"/var/lib/libvirt/images/c8fd16b3-fd9b-452f-b4bb-4be9ebe8a011-0-0.img",
      "pool":{
        "type":"dir",
        "name":"/plugins/kimchi/storagepools/default"
      },
      "size":10
    }
  ],
  "invalid":{},
  "os_version":"unknown",
  "memory":{
    "current":1024,
    "maxmemory":1024
  },
  "folder":[]
}
```

Expected output:
```
{
  "cpu_info":{
    "maxvcpus":1,
    "vcpus":1,
    "topology":{}
  },
  "graphics":{
    "type":"vnc",
    "listen":"127.0.0.1"
  },
  "cdrom":null,
  "networks":[
    "default"
  ],
  "icon":"plugins/kimchi/images/icon-vm.png",
  "os_distro":"unknown",
  "name":"fedora-disk",
  "disks":[
    {
      "index":0,
      "format":"qcow2",
      "base":"/var/lib/libvirt/images/c8fd16b3-fd9b-452f-b4bb-4be9ebe8a011-0-0.img",
      "pool":{
        "type":"dir",
        "name":"/plugins/kimchi/storagepools/default"
      },
      "size":10
    }
  ],
  "invalid":{
    "vm-image":[
      "/var/lib/libvirt/images/c8fd16b3-fd9b-452f-b4bb-4be9ebe8a011-0-0.img"
    ]
  },
  "os_version":"unknown",
  "memory":{
    "current":1024,
    "maxmemory":1024
  },
  "folder":[]
}
```

(i'm suggesting "vm-image" but it could be anything else, I'm looking for the object keys to map the invalid fields and the current input name is vm-image)

4- If you try to save the Template then it will enable the vm-image field and display an error message:
![invalid-disk](https://cloud.githubusercontent.com/assets/326107/14898026/17f8c4da-0d5b-11e6-89f2-7473ac81cb11.png)

**Comment by samhenri** [comment]
Sent a working v2 for invalid Storage Volume and ISO. I'm unable to check via front-end if the vm-image path is invalid, but if the user attempts to save it the back-end returns an error and enables this input.
As fot the storage volume, I was able to append in the Storage volumes combobox the inactive/wrong storage volume. If the user selects a different storage volume, he won't be able to select the old invalid storage volume again because the option will be disabled and if he tries to save it without choosing a new storage volume, it will return an error.

Right now the back-end is not preventing the user from saving a Template with an invalid Storage Volume path.

**Comment by ramonmedeiros** [comment]
@samhenri please, take a look if the issue described in comment 1 is fixed
