### ISSUE TITLE
[UI] Guest tab is not rendered correctly if guests are not in 'running' or ''shutoff' state

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#939]
If you pause a guest and refresh the UI, guests tab will show the paused guest line with buttons in different places, without the 'actions' and will show the synchronization icon.

**Comment by sstoppler** [comment]
@Truja This is what I see when a VM is paused (with the last icon for aaatest1 'spinning').   I don't see the behavior you've described or am I misundertanding what you saw?

![image](https://cloud.githubusercontent.com/assets/11432111/17148913/d6e28a40-531d-11e6-9867-e36604f67ebe.png)

**Comment by samhenri** [comment]
I was able to fix this and I will send a patch soon. Can you confirm if the problem happens with one of these other states?

```{0: 'nostate',
                 1: 'running',
                 2: 'blocked',
                 3: 'paused',
                 4: 'shutdown',
                 5: 'shutoff',
                 6: 'crashed',
                 7: 'pmsuspended'}```
