### ISSUE TITLE
Maximum memory should increase when memory is increased

### ISSUE THREAD

**Issue by overcookedTOFU** [kimchi-project/kimchi#941]
When adding more memory to a guest, Kimchi should either automatically increase the maximum memory value or show the max memory value by default.

Currently, when a user tries to increase the memory available to a guest, it will report an error, as seen below:
![memory-bug2](https://cloud.githubusercontent.com/assets/591536/15055777/552175d8-12dc-11e6-9e73-233edcc94599.PNG)

The user must fix the error by clicking "More" and increasing the maximum memory value:
![memory-bug1](https://cloud.githubusercontent.com/assets/591536/15055763/488177e2-12dc-11e6-8c48-e4b2d7a2df11.PNG)

When the "More" dropdown is closed and the user increases the memory available to the system, Kimchi should automatically match the maximum memory to the "memory" field.

**Comment by sstoppler** [comment]
Patch has been applied upstream:  https://github.com/kimchi-project/kimchi/commit/5fe4a228b01b327ac30db72256341bc7c29e1572
