### ISSUE TITLE
When opening console, kimchi stops responding to user input

### ISSUE THREAD

**Issue by overcookedTOFU** [kimchi-project/kimchi#942]
On Ubuntu 16.04 when I open the console for any guest, the console hangs and the wokd error log spits out the error below.  While the console loads, it is extremely slow and occasionally does not respond to input.  The tab with the Kimchi-UI must be reloaded and login is requested once again.

```
[05/May/2016:22:09:59] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cptools.py", line 175, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for keyword argument 'filename'
```

**Comment by alinefm** [comment]
Hi @overcookedTOFU 

Are you trying VNC or Spice console? Or serial console?

**Comment by overcookedTOFU** [comment]
This is using VNC console.  For some reason it has stopped happening quite so frequently.  I now only occasionally encounter this issue.  If I am able to find any additional information, I'll let you know.

**Comment by overcookedTOFU** [comment]
I have not encountered this issue for many months. It may just have been a temporary issue with chrome.
