### ISSUE TITLE
Feature request: Change templates values at guest deployment time

### ISSUE THREAD

**Issue by Styx13** [kimchi-project/kimchi#946]
Hello,

I have been using Kimchi a lot those last 2 weeks, and for my current use case, I found out that even though templates are great, they do take more time and steps to get the guests created and running.

In my use case, I need to deploy 20 VMs which are using the same disk image (and the same CPU/Memory)
Each of those VMs need to be on a different network (VLAN and subnet).

Because of that, I had to create 20 templates, 1 for each of the VMs, and the only difference between those templates is the network.

It would be great if I could create only one template, and then, at the time of deploying a guest, I would be offered to modify parameters of the template (such as networks, storage, CPU, memory, ...) if I wanted, or just go with what's defined in the template.

Also, when I will get a new disk image for my VMs (because a new version will be available soon), I will need to create again 20 new templates, instead of just 1. (ending with 20 templates per version of my disk image).

I agree that this request is specific to this use case, but I believe that a lot of users who are deploying VMs would actually be in a very similar use case.

I think this idea has already been brought up in the following issue: #394

**Comment by alinefm** [comment]
Hi @Styx13 

Thanks for your feedback! As you pointed it was already discussed in #349 
My idea is to have a "Customize" section when creating a VM. So after selecting a Template, the user can change any other configuration before creating the VM.

Will that fits your matters?

I'd say to we keep only one issue open to track this only to centralize the information.
So close #349 or this one.

**Comment by Styx13** [comment]
Hi @alinefm, I believe you meant #394.
I am closing this issue then and will follow up in #394
