### ISSUE TITLE
Allow an option to disable HTTPS

### ISSUE THREAD

**Issue by dikshant** [kimchi-project/kimchi#950]
I would be nice to have an option to completely disable ssl so that we could implement our own certificates using a separate reverse proxy.

**Comment by ramonmedeiros** [comment]
Can't you add your certificates in nginx?

**Comment by alinefm** [comment]
Hi @dikshantad 

You can specify your own certificate on wok.conf file (/etc/wok/wok.conf).

**Comment by dumol** [comment]
There is also the scenario in which you don't need HTTPS, eg. Kimchi is used in a virtual private network where access is secured already (our setup).  Why bother with certificates for every host?

**Comment by tobiashochguertel** [comment]
Is there any news about this feature?
I want to manage certifications by my own (reverse proxy server  an let's encrypt). I can also not access the web ui via the self generated certifications from wok in Google Chrome Browser because more restrict rules in Chrome as in Firefox.

**Comment by dikshant** [comment]
@tobiashochguertel, I opened this PR a long time ago when I didn't know as much about nginx and its reverse proxying capabilities. In Chrome you can type `thisisunsafe` on the page you see the cert error and it will let you bypass it.

As for reverse proxying via something like nginx you can front the server with your own cert. Make sure in your location block for the reverse proxy add the directive `proxy_ssl_verify   off;`. Of course this has the caveat of blindly trusting whatever cert the backend has but that is a risk for you to decide on if you are comfortable with.
