### ISSUE TITLE
Text box in migrate a guest dialog window is not sensitive to keyboard clicks 

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#953]
In Kimchi when Actions button is clicked and Migrate option is selected for a particular guest, dialog box window opens for getting migration input.

Text box that gets input for Remote server, user and password are not sensitive to take the keyboard clicks at one time.

I have tried and observed many times that some text are missed when we type fast and we have to click 2 or 3 times for a letter to be entered.

But the text box in login window is good enough to take input at one shot, it would be good even if textbox in the migration input window works with sensitivity same as text box in login window.

**Comment by samhenri** [comment]
Sent patch to mailing list with #948, let me know if it works.

**Comment by samhenri** [comment]
Can somebody confirm it this issue is still happening? I saw that the error messages issue #948 is still open but I'm not sure if it is a front-end error.
