### ISSUE TITLE
Disable ISOs with wrong permission and add mouse hover message

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#954]
Kimchi will not change any permission in the filesystem as it is so invasive.
You should go through the instructions reported by the error message to fix the file permissions.

Kimchi will not filter out those files because it may get the user confused.
("I know there is a ISO under /tmp why Kimchi is not displaying it")

The idea is always display all ISOs found but disable those with wrong permission and add mouse hover message "qemu does not have enough permission to work with this file" to improve usability.

**Comment by samhenri** [comment]
Is there a mechanism to know if the ISO has wrong permission?

**Comment by alinefm** [comment]
HI @samhenri 

Yeap! You can check the storage volume information:

{
    "allocation":536875008,
    "isvalid":true,
    "capacity":536870912,
    "name":"test-volume-clone-3",
    "format":"raw",
    "has_permission":false,
    "path":"/home/alinefm/images/test-volume-clone-3",
    "used_by":[],
    "type":"file"
  }

The 'has_permission' parameter.

**Comment by alinefm** [comment]
Fixed by c5d83e632f28db3429c950c89c027f17a14b1012

**Comment by nexusguy59** [comment]
I am having the same issue, in the gui. I have added my NFS Share for ISOs and made sure permissions on the NAS side were correct, I can't find the permission perimeter to change it. Can some help me with that please. So this happens when I try to add templates from the NAS Share.

Thanks,
Michael

**Comment by alinefm** [comment]
Hi @nexusguy59 
Have you followed the instructions on how to configure a NSF storage pool https://github.com/kimchi-project/kimchi/blob/master/docs/README.md#nfs-storage-pool ?
