### ISSUE TITLE
Ubuntu - No Virtualization Tab or Kimchi displayed in Wok

### ISSUE THREAD

**Issue by jamesrascal** [kimchi-project/kimchi#958]
I have followed all the docs but can't seem to get Kimchi to load into Wok. Wok runs just fine but I don't get a tab for virtualization.

**Comment by pvital** [comment]
Hello @jamesrascal 
What's your Ubuntu version? Can you paste the output of /var/log/wok/wok-error.log to try to see what's going on?

**Comment by jamesrascal** [comment]
I am attempting to replicate this on a new build now. I will post results once its done.

**Comment by jamesrascal** [comment]
I am closing this issue as problems are resolved after complete rebuild and following the install script https://github.com/kimchi-project/kimchi/wiki/Setup-script-for-Ubuntu-15.10
