### ISSUE TITLE
build proces of Kimchi fails on clean Debian Jessie

### ISSUE THREAD

**Issue by derdigge** [kimchi-project/kimchi#960]
Followed instructions from here:

https://github.com/kimchi-project/kimchi/blob/master/docs/ubuntu-deps.md

It dies during make:
xsltproc -o ja_JP/guests.html dita-help.xsl ja_JP/guests.dita
ja_JP/guests.dita:4: warning: failed to load external entity "-//IBM//DTD DITA CSHelp//EN"
 "..\dtd\cshelp.dtd">

My full console log:
http://pastebin.com/gve86Ayi

as you can see wok and other stuff is installed correctly.

**Comment by pvital** [comment]
Hi @derdigge. One curiosity, why didn't you downloaded the kimchi deb file as you for wok and gingerbase? You can get the same version at http://bit.ly/get_kimchi

**Comment by derdigge** [comment]
Thanks for your reply!

i didnt know that site :) just cloned from github and read the doc.
installing as deb works for debian 8 but not for linux mint 17
anyway this solved my issue. 

Thanks.
