### ISSUE TITLE
Debian 8, installation from deb systemd cant start kimchi

### ISSUE THREAD

**Issue by derdigge** [kimchi-project/kimchi#961]
Hello!

After solving my brain error, i was able to install kimchi onto my Debian8 Testbox. 
I am not able to start with following (helpful) error. (i hate systemd by the way :)

I fixed allready that "wrong service bug" in
/etc/systemd/system/wokd.service.d/kimchi.conf

`[Unit]
Requires=libvirtd.service wokd.service
After=libvirtd.service wokd.service

[Service]
Nice=0
PrivateTmp=yes`

service libvirtd restart
--> works

service wokd restart
--> works

But:
service kimchi restart
--> Failed to restart kimchi.service: Unit kimchi.service failed to load: No such file or directory.

debs from here:
http://kimchi-project.github.io/kimchi/downloads/
`root@gunter:~# ls
ginger-base-2.1.0-0.noarch.deb  kimchi-2.1.0-0.noarch.deb  wok-2.1.0-0.noarch.deb`

I´ll be happy to provide more information.

Thanks

**Comment by pvital** [comment]
@derdigge the problem is because the name of libvirt service in Ubuntu, that is libvirt-bin.service instead of libvirtd.service, and we officially release the package only to Ubuntu, not Debian.

Regarding the service, since version 2.0.0 Kimchi is a plugin of Wok, and we must start **only** wokd.service to get all plugins (Kimchi, GingerBase and Ginger) running:

```
$ sudo systemctl start wokd.service
$ sudo systemctl -l status wokd.service
```

**Comment by derdigge** [comment]
Thanks for Your reply. I allready googled that. But anyway there is still no connection aviable with my browser. Check this out please:

`root@gunter:~# sudo systemctl stop wokd.service

root@gunter:~# sudo systemctl start wokd.service

root@gunter:~# sudo systemctl -l status wokd.service

● wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/lib/systemd/system/wokd.service; enabled)
  Drop-In: /etc/systemd/system/wokd.service.d
           └─kimchi.conf
   Active: active (running) since Thu 2016-06-16 11:31:12 EDT; 2s ago
  Process: 20963 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 20971 (python2)
   CGroup: /system.slice/wokd.service
           ├─20971 python2 /usr/bin/wokd
           ├─20974 nginx -c /etc/nginx/conf.d/wok.conf
           ├─32180 nginx: master process nginx -c /etc/nginx/conf.d/wok.con
           └─32181 nginx: worker process`

As this is only a testserver , look hiere(BadGateway)
https://31.24.34.117:8001/

Nginx log says:
2016/06/16 11:34:31 [error] 32181#0: *38 connect() failed (111: Connection refused) while connecting to upstream, client: 5.9.81.44, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8010/", host: "31.24.34.117:8001"

so i asumed that kimchi isnt running.....
any thoughts ?

**Comment by pvital** [comment]
The "502 Bad Gateway" error happens when nginx was started but cherrypy was not fully loaded yet.

Please, pastebin the output of /var/log/wok/wok-error.log or the output of the following command:

```
/usr/bin/wokd --environment=dev
```

You know that everything is OK when using the above command you see the message "ENGINE Bus STARTED" outputted.

**Comment by pvital** [comment]
One more thing, did you checked the firewall and selinux?

https://github.com/kimchi-project/wok/blob/master/docs/troubleshooting.md

**Comment by derdigge** [comment]
That pointed it out :)

i need to stop wok, restart libvirt and then start WOK in this order it worked now....(see the interface)

**Comment by pvital** [comment]
@derdigge wonderful :-D
