### ISSUE TITLE
Exception in thread KimchiLibvirtEventLoop

### ISSUE THREAD

**Issue by rafaelsoaresbr** [kimchi-project/kimchi#963]
Trying to get kimchi running on Arch Linux (VBox Machine):
```
uname -a
```
>
Linux arch-vbox 4.6.2-1-ARCH #1 SMP PREEMPT Wed Jun 8 08:40:59 CEST 2016 x86_64 GNU/Linux

I'm geting the following errors when starting wok up:

```
# systemctl start wokd
# systemctl status wokd
```
>
● wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/usr/lib/systemd/system/wokd.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/wokd.service.d
           └─ginger.conf, kimchi.conf
   Active: failed (Result: exit-code) since Dom 2016-06-19 11:15:00 AMT; 1min 31s ago
  Process: 857 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=1/FAILURE)
  Process: 618 ExecStart=/usr/bin/wokd (code=exited, status=1/FAILURE)
 Main PID: 618 (code=exited, status=1/FAILURE)
    Tasks: 2 (limit: 512)
   CGroup: /system.slice/wokd.service
           ├─701 nginx: master process nginx -c /etc/nginx/conf.d/wok.con
           └─702 nginx: worker process              
>
Jun 19 11:14:59 arch-vbox wokd[618]: Exception in thread KimchiLibvirtEventLoop (most likely raised during interpreter shutdown):
Jun 19 11:14:59 arch-vbox wokd[618]: Traceback (most recent call last):
Jun 19 11:14:59 arch-vbox wokd[618]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Jun 19 11:14:59 arch-vbox wokd[618]:   File "/usr/lib/python2.7/site-packages/cherrypy/process/plugins.py", line 519, in run
Jun 19 11:14:59 arch-vbox wokd[618]: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'
Jun 19 11:15:00 arch-vbox systemd[1]: wokd.service: Main process exited, code=exited, status=1/FAILURE
Jun 19 11:15:00 arch-vbox kill[857]: kill: argumentos insuficientes
Jun 19 11:15:00 arch-vbox systemd[1]: wokd.service: Control process exited, code=exited status=1
Jun 19 11:15:00 arch-vbox systemd[1]: wokd.service: Unit entered failed state.
Jun 19 11:15:00 arch-vbox systemd[1]: wokd.service: Failed with result 'exit-code'.

**Comment by pvital** [comment]
Hi @rafaelsoaresbr 

Nice you are trying to run Wok and Kimchi in Arch Linux. I have never saw any try on this distro. Could you provide us more info about your environment: distro version, libvirt version, wok and kimchi version, how did you installed wok and kimchi. 

Also, can you pastebin the output of the command "/usr/bin/wokd --environment=dev" or the content of the /var/log/wok/wok-error.log file ? This command will prompt any error on console (the same content you'll find on error log).

**Comment by pvital** [comment]
@rafaelsoaresbr looks like you are facing the same issue reported in #813. Can you check the solution provided there and reply here with a solution for ArchLinux?

**Comment by rafaelsoaresbr** [comment]
@pvital Ok, I've been installing kimchi on a real machine, if necessary I'll be back here. Please take a look at #964
