### ISSUE TITLE
Installing from source on Arch Linux gives 'Nothing matches the given URI'

### ISSUE THREAD

**Issue by rafaelsoaresbr** [kimchi-project/kimchi#964]
Hello guys, I'm trying to install/run kimchi on Arch Linux.

I've compiled wok, ginger-base, ginger and kimchi from source with the following:

```
PYTHON=/usr/bin/python2 ./autogen.sh --system && make
make DESTDIR=$pkgdir install
```

```
systemctl status wokd
```

>● wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/usr/lib/systemd/system/wokd.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/wokd.service.d
           └─ginger.conf, kimchi.conf
   Active: active (running) since Tue 2016-06-21 03:28:44 AMT; 14min ago
 Main PID: 626 (python2)
    Tasks: 17 (limit: 512)
   CGroup: /system.slice/wokd.service
           ├─626 python2 /usr/bin/wokd
           ├─677 nginx: master process nginx -c /etc/nginx/conf.d/wok.con
           └─678 nginx: worker process              
>
Jun 21 03:28:44 boss-desktop systemd[1]: Started Wok - Webserver Originated from Kimchi.

Trying to access the address https://<server_ip>:8001 I've got the following error:

![wok](https://cloud.githubusercontent.com/assets/13059863/16228491/649fdaae-3785-11e6-81ff-b75ad5d04c2d.png)

I've uploaded the resulting packages:

[kimchi-project.zip](https://github.com/kimchi-project/kimchi/files/325462/kimchi-project.zip)

Thanks.

**Comment by pvital** [comment]
Hi @rafaelsoaresbr 

Can you pastebin the content of /var/log/wok/wok-error.log, please? 
Have you got this error, just after enter the URL, or you could see (and logged in) the login page?

**Comment by rafaelsoaresbr** [comment]
Hum, seens like I'm missing some dependencies:
This error appear just after hitting enter on the address bar.
http://pastebin.com/ZXa1Aapg

**Comment by rafaelsoaresbr** [comment]
Ok, it's running now, I had to start virtlogd.service.
But the same error appear on browser, any clues?

wok-error.log:
http://pastebin.com/YxHYcQrR

**Comment by pvital** [comment]
Let's do two things. First, please check firewall and selinux blocks - https://github.com/kimchi-project/wok/blob/master/docs/troubleshooting.md

Then, let's try to capture the exactly URI you are trying to access. Start the server in development mode and then pastebin the output of the console after you try to access https://<ip>:8001

```
$ sudo /usr/bin/wokd --environment=dev
```

**Comment by rafaelsoaresbr** [comment]
```
sudo /usr/bin/wokd --environment=dev
```
>libvirt: QEMU Driver error : Domain not found: no domain with matching name 'FEATURETEST_VM'
libvirt: Storage Driver error : Storage pool not found: no storage pool with matching name 'FEATURETEST_POOL'
>
*** Kimchi: Running feature tests ***
Service Libvirtd running ...: True
libvirt:  error : Cannot find '' in path: No such file or directory
Cannot find '' in path: No such file or directory
NFS Target Probe support ...: False
Fibre Channel Host support .: True
Kernel VFIO support ........: True
Network Manager running ....: False
Memory Hotplug support .....: True
*** Kimchi: Feature tests completed ***
>
rc: 1 error: Too few arguments: you must specify one drive, at least.
 returned from cmd: hddtemp
*** Ginger Base: Running capabilities tests ***
System Report Tool ...: False
System Update Tool ...: False
GGBREPOS0014E: GGBREPOS0014E
Repo Management Tool .: None
*** Ginger Base: Capabilities tests completed ***
GGBREPOS0014E: GGBREPOS0014E
GGBREPOS0014E: GGBREPOS0014E
[21/Jun/2016:10:12:45] ENGINE Listening for SIGHUP.
[21/Jun/2016:10:12:45] ENGINE Listening for SIGTERM.
[21/Jun/2016:10:12:45] ENGINE Listening for SIGUSR1.
[21/Jun/2016:10:12:45] ENGINE Bus STARTING
[21/Jun/2016:10:12:46] ENGINE Started monitor thread 'Autoreloader'.
[21/Jun/2016:10:12:46] ENGINE Serving on http://127.0.0.1:8010
>
*** Kimchi: Running dependable feature tests ***
127.0.0.1 - - [21/Jun/2016:10:12:46] "HEAD /plugins/kimchi/images/icon-fedora.png HTTP/1.1" 200 4449 "" ""
127.0.0.1 - - [21/Jun/2016:10:12:46] "GET /plugins/kimchi/images/icon-fedora.png HTTP/1.1" 206 4449 "" ""
QEMU stream support .......: True
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***
>
[21/Jun/2016:10:12:46] ENGINE Bus STARTED
[21/Jun/2016:10:12:54] ENGINE Started monitor thread 'Session cleanup'.
192.168.1.3 - - [21/Jun/2016:10:12:54] "GET / HTTP/1.0" 303 114 "" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.1.3 - - [21/Jun/2016:10:13:11] "GET / HTTP/1.0" 404 2234 "" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.1.3 - - [21/Jun/2016:10:13:11] "GET /images/theme-default/logo-white.png HTTP/1.0" 304 - "https://192.168.1.6:8001/" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"

**Comment by alinefm** [comment]
Seems it is duplicated of https://github.com/kimchi-project/wok/issues/138

Please, update it to the current master branch which includes https://github.com/kimchi-project/wok/commit/0e57dfe9ebfdad518bb86c464f620b0de942e51d
