### ISSUE TITLE
Error message showing up in parent panel rather than modal window in Add Storage

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#969]
How to reproduce:
1.  Click on Add a Storage, enter any invalid info and click on Create button.

Outcome:    
Error shows on parent panel, not add storage panel although the error does not disappear on its own which is now the intent.

**Comment by samhenri** [comment]
Patch sent to ML

**Comment by sstoppler** [comment]
Reviewed and tested; awaiting for patch to be applied upstream.
