### ISSUE TITLE
ISOs that do not have proper permission is still being allowed to be used when creating a template

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#970]
In testing patch from Peter - Disable ISOs templates with wrong permission, I came across the problem.  Regardless of the patch being applied, I was able to create a template in the UI.

Steps:
1. Click on Add Template.
2. Click on Search more ISOs button - this shows ISOs on my HD
3. Without the patch, I am able to create a template and create a guest based on that template.
    With the patch, the UI prevents me from selecting the ISO as it does not have the proper  
    permission.

Here's an example of the output from backend for a particular ISO:
"os_distro":"ubuntu",
    "capacity":1162936320,
    "name":"ubuntu-14.10-desktop-amd64.e884814a42cce93fb655100b83e9ad31.iso",
    "format":"iso",
    "bootable":true,
    "isvalid":true,
    "used_by":[],
    "allocation":1162940416,
    "os_version":"14.10",
    "has_permission":false,
    "path":"/home/socorro/Downloads/DownloadsOld/ubuntu-14.10-desktop-amd64.iso",
    "type":"file"

Problem:
Before the patch is applied, the user should get an error from backend in creating the template since it does not have the proper permission to do so.

**Comment by jrziviani** [comment]
Actually it's expected, my commit 6e983c4 returns that new field indicating whether an iso has (or not) the right permission. Backend is not blocking it.

**Comment by sstoppler** [comment]
@jrziviani - I see that the backend is returning the new field regarding the permission.  Per discussion with @alinefm, prior to applying UI patch from Peter, if the user chooses an iso that the permission is set to false, there should be an error from the backend stating the improper permission (since as of now, UI prevents the ISO from being selected).  Does that make sense?  We can discuss offline if needed.  Thanks!

**Comment by jrziviani** [comment]
Hello @sstoppler 

Makes sense to me! Let's got that way then 👍

**Comment by ramonmedeiros** [comment]
Hi @sstoppler, just tested with upstream and got an error when trying to add a ISO without permissions:

KCHISO0008E: The hypervisor doesn't have permission to use this ISO /home/ramonn/Downloads/Fedora-Server-DVD-x86_64-23.iso. Consider moving it under /var/lib/libvirt, or set the search permission to file access control lists for 'qemu' user if possible, or add the 'qemu' to the ISO path group, or (not recommended) 'chmod -R o+x 'path_to_iso'.Details: [Errno 13] Permission denied: '/home/ramonn/Downloads/Fedora-Server-DVD-x86_64-23.iso'

Seems that commit 2d1a0e70381ff3bf13d94b0393c4d4afe739f900 solved it. I will close.
