### ISSUE TITLE
openSUSE LEAP - Wok 2.2/Kimchi 2.2 SPICE didn't Work

### ISSUE THREAD

**Issue by lihaso** [kimchi-project/kimchi#972]
I have used the default rpm's from: http://kimchi-project.github.io/kimchi/downloads/

Everything installed as described, everything worked except SPICE Viewer.

Everything who is included by the spice_auto.html gives a HTTP 404 error.

Currently to solve i have copyed the full folder from `/usr/share/wok/plugins/kimchi/ui/spice-html5` to `/usr/share/wok/ui/spice-html5`

Now everything works fine.

**Comment by danielhb** [comment]
Hi @lihaso thanks for opening this bug. I'll send a patch fixing it in our current master code.

I'll talk with @alinefm about the possibility of adding another Opensuse package with this problem fixed.

**Comment by danielhb** [comment]
@lihaso we've updated the Opensuse package in github.io with a version containing the patch. If possible can you try it out?  You will need to remove the folder '/usr/share/wok/ui/spice-html5' to see if the fix is working properly.

**Comment by lihaso** [comment]
Thanks for the fast fixing, now it works.
