### ISSUE TITLE
Display the resource name in the confirmation dialog

### ISSUE THREAD

**Issue by qmfrederik** [kimchi-project/kimchi#973]
When deleting a guest, Kimchi currently shows the current confirmation dialog:

> ##### Virtual Machine delete Confirmation
> This will delete the virtual machine and its virtual disks. This operation cannot be undone. Would you like to continue?
> [ OK ] [ Cancel ]

It would be great if the machine name was also displayed in the confirmation dialog.

**Comment by alinefm** [comment]
Yeap! Completely agree.

I'd go deeper and ask to add the resource name on every confirmation box so user make sure on which resource he/she is performing the action.

**Comment by samhenri** [comment]
This can be easily done by adding a %1 into the i18n string and using wok.replace() to put the guest name. Is this issue just for guest deletion or other Kimchi confirmation windows?

**Comment by peterpennings** [comment]
@alinefm @danielhb any updates on this issue?

**Comment by danielhb** [comment]
@peterpennings @samhenri showing the guest name is desirable not only for guest delete but also for every dialog that refers to a specific guest/element.

**Comment by sstoppler** [comment]
Patch sent to ML for review

**Comment by sstoppler** [comment]
v2 of patch sent to ML for review - addressed having the resource name to be displayed in bold.

**Comment by sstoppler** [comment]
v3 of patch sent to ML for review.  In some distros, the resource name is not being displayed in bold due
a problem with Open Sans per Samuel.  There are some cases, mainly with Firefox in that some style with font weight set to 600 does not work and 700 is usually too bold to set as a fallback.  Therefore, just use the style as <abbr> and <acronynm> tags which creates a dotted bottom.

**Comment by sstoppler** [comment]
Patch applied upstream:  https://github.com/kimchi-project/kimchi/commit/4a3612020b2168d64385da5b9cd343d0e3fca9ad
