### ISSUE TITLE
qemu-system-ppc64: warning: CPU(s) not present in any NUMA nodes

### ISSUE THREAD

**Issue by flips** [kimchi-project/kimchi#974]
Ubuntu 16.04 ppc64le, installed latest Wok, Ginger and Kimchi 2.2.

Adding a guess with memory 4096, max mem 8192 and 3 CPU cores:
``KCHVM0019E: Unable to start virtual machine SLES12. Details: internal error: process exited while connecting to monitor: 2016-07-05T13:33:27.920731Z qemu-system-ppc64: warning: CPU(s) not present in any NUMA nodes: 1 2 2016-07-05T13:33:27.920761Z qemu-system-ppc64: warning: All CPU(s) up to maxcpus should be described in NUMA config 2016-07-05T13:33:27.932925Z qemu-system-ppc64: Specified number of memory slots 256 exceeds max supported 32``

Adding a plainer 4096/4096 mem and 1 CPU core didn't cause the same issue.

(Hopefully you'll be able to reproduce. I only have access to this Power8 machine for another day or two.)

**Comment by flips** [comment]
A new test: Added a RHEL VM, set memory to 4096 and Max 8192. Same error.
Then adjusted memory max to 4096. Saved, started it, and it worked.
I would guess there's some issue with balooning or something?

**Comment by alinefm** [comment]
Fixed by cf788ac3a8e7f79e3254d5e554e32f0d4946e9d3
