### ISSUE TITLE
Inform user that his operation succeed in Edit guest modal

### ISSUE THREAD

**Issue by laggarcia** [kimchi-project/kimchi#975]
In the Edit guest modal, in a number of tabs, the Save button is disabled (e.g. Storage and Interface).

When we detach a storage device, for instance, the operation is atomic and saved automatically. Hence, there is no need for the user to click on the Save button. Actually that is why it is disabled. But there is a Save button there asking to be clicked! OK, I know we have discussed before why the button is there... However, as a user, I always click on the Save button, and, then, remember that action is not needed.

It would be good to have an informative message on the screen saying that the action performed was successful. That way a user will (hopefully) not even think about clicking on the Save button.

**Comment by samhenri** [comment]
I'm already putting the success message calls when attaching or detaching a PCI device while I'm fixing issue #956

**Comment by samhenri** [comment]
Patch sent to ML. For now I'm just addressing the PCI actions but I'll work on this issue later to address other tabs.
