### ISSUE TITLE
Create UI to change boot order 

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/kimchi#979]
Follow the issue Change boot order #828

**Comment by sstoppler** [comment]
UI patch is ready to be sent out to ML for review.  However, found a bug in the backend.
@alinefm @ramonmedeiros - should I go ahead and send patch for review or wait for backend bug to be addressed.  I only sent backend issue via email but I can write a new issue as well.  Please advise.  Thanks!

**Comment by sstoppler** [comment]
Patch sent to ML for review.  Issue written to address backend problem:  
https://github.com/kimchi-project/kimchi/issues/1012
