### ISSUE TITLE
Creating a Snapshot w/wok-Kimchi

### ISSUE THREAD

**Issue by nexusguy59** [kimchi-project/kimchi#983]
Hello Guys,

Very new to Wok/Kimchi. I have a server that is an intel core i7 w/16gb and 8 tb of drive space it is an octocore processor. Everything is running fine except I couldn't create a snapshot of the VMs, I got the following error when I tried to do this. Any help would be greatly appreciated.

Unexpected exception: KCHSNAP0002E: Unable to create snapshot '1471523678' on virtual machine 'cfbup01'. Details: internal error: Child process (/usr/bin/qemu-img snapshot -c 1471523678 /mnt/VMs/a435abee-5b29-441b-96e8-a4baf3095b5d-0.img) unexpected exit status 1: qemu-img: Could not open '/mnt/VMs/a435abee-5b29-441b-96e8-a4baf3095b5d-0.img': Could not open '/mnt/VMs/a435abee-5b29-441b-96e8-a4baf3095b5d-0.img': No such file or directory 

Here is what I get when I look on the server itself:
root@cfkvm04:~# ls -al /mnt/VMs
total 32807344
drwx--x--x 3 root         root        4096 Aug 17 10:39 .
drwxr-xr-x 6 root         root        4096 Aug 10 07:46 ..
-rw------- 1 libvirt-qemu kvm   3461152768 Aug 18 08:43 0d1b15e9-3ed1-47fe-a164-96ec79525744-0.img
-rw------- 1 libvirt-qemu kvm   5292359680 Aug 18 08:43 74c6eb23-579a-4087-8330-89bf98994f91-0.img
-rw------- 1 root         root  2620391424 Aug  9 17:42 afa433b4-bb04-43da-98fd-d1518651c9f4-0.img
-rw------- 1 root         root 64434601984 Aug  7 20:15 cfbup01.qcow2

The last one is the actual file I believe. How do I correct this?

Thanks in Advance
Michael

**Comment by pvital** [comment]
Hello Michale (@nexusguy59) 

What is the version of wok and kimchi are you running? Also, which distro and version is your host? I could create snapshots using Kimchi in my Fedora 24 using the latest HEAD of github. 

Is /mnt/VMs a valid storage pool?  I think so, because I can see the image of your VM cfbup01 there. Something interesting I noticed, is that qemu-img could not open the file it should create. Probably is some missing/wrong  permission in this pool.

**Comment by nexusguy59** [comment]
Kimchi version is: 2.2.0-0
WOK version: 2.2.0-0
Gingerbase: 2.2.0-0

Sorry guys I answered my own question with trial and error, I was able to detach a435abee-5b29-441b-96e8-a4baf3095b5d-0.img (not sure where it came from) and then reattached the correct disk file name cfbup01.qcow2 and booted the VM, Everything is fine. Really numbskull move on my part.

Thanks again,
Michael
