### ISSUE TITLE
VM Creation Issue

### ISSUE THREAD

**Issue by nexusguy59** [kimchi-project/kimchi#985]
Hello Guys,

I am on Ubuntu Server
root@cfkvm04:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

root@cfkvm04:~# dpkg -s qemu-kvm | grep Version
Version: 1:2.5+dfsg-5ubuntu10.4
root@cfkvm04:~# kvm --version
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.4), Copyright (c) 2003-2008 Fabrice Bellard

Wok 2.2.0-0
Gingerbase 2.2.0-0
Kimchi 2.2.0-0

I ran in to this error this morning when creating a guest, I already have 4 created by the way:

So I create the guest from a template (Ubuntu Server 16.04 iso) then I try to start the guest and I get the following:

KCHVM0019E: Unable to start virtual machine _myVM_. Details: error from service: ListActivatableNames: Failed to query AppArmor policy: No such file or directory

This is the contents of the VM directory
root@cfkvm04:/# ls -al /mnt/VMs
total 42260768
drwx--x--x 3 root         root        4096 Aug 21 09:17 .
drwxr-xr-x 6 root         root        4096 Aug 19 04:45 ..
-rw------- 1 libvirt-qemu kvm   3523674112 Aug 21 09:27 0d1b15e9-3ed1-47fe-a164-96ec79525744-0.img
-rw------- 1 libvirt-qemu kvm   3447783424 Aug 21 09:17 68eb294a-f5d4-444b-984d-1295208a060c-0.img
-rw------- 1 libvirt-qemu kvm  11257380864 Aug 21 09:25 74c6eb23-579a-4087-8330-89bf98994f91-0.img
-rw------- 1 root         root  2620391424 Aug 19 04:53 afa433b4-bb04-43da-98fd-d1518651c9f4-0.img
-rw------- 1 root         root      198656 Aug 21 09:17 caa0d4c0-e8c3-47a3-bf8d-bcc7210ebb93-0.img
-rw------- 1 libvirt-qemu kvm  64434601984 Aug 21 09:27 cfbup01.qcow2

Not sure what to look for here and I am very confused because I was able to start 4 others with no problem.

Thanks,
Michael

**Comment by alinefm** [comment]
Hi @nexusguy59 

I am not very familiar with Ubuntu, but seems AppArmor is blocking the guest start operation.
Is the ISO (Ubuntu Server 16.04) inside a libvirt pool? Maybe some permission issue or something.
It is the single thing I can think right now.

**Comment by nexusguy59** [comment]
I figured it out, I got it working by creating a template with the iso and
then creating a VM from there

Michael A Cooper
Linux & Zerto Certified Professional

**Comment by alinefm** [comment]
Glad to know that, @nexusguy59 !
I am closing this issue by now.
