### ISSUE TITLE
Error message while starting Kimchi from source code

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#986]
When starting Wok with Kimchi enabled I got the following error message:

CherryPy Checker:
'/home/alinefm/wok/src/wok/plugins/kimchi/data/virtviewerfiles' (root + dir) is not an existing filesystem path.
section: [/data/virtviewerfiles]
root: None
dir: '/home/alinefm/wok/src/wok/plugins/kimchi/data/virtviewerfiles'

Seems the directory is not being automatically created.

**Comment by danielhb** [comment]
Patch sent to ML for review
