### ISSUE TITLE
Details: unsupported configuration: Memory cgroup is not available on this host

### ISSUE THREAD

**Issue by buschco** [kimchi-project/kimchi#990]
On a physical Debian server I got this message on starting a guest
`Details: unsupported configuration: Memory cgroup is not available on this host`
Do I have to install some cgroup packages and create a new cgroup config?
Is this problem only with Debian systems?

**Comment by pvital** [comment]
@buschco, are you using Debian Wheezy?

I remember something related to cgroups memory limits, specially when using containers. A fix to this is edit /etc/default/grub in Debian/Ubuntu (or use the grub config tool in other distros) and add or append the following:

```
GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"
```

In Debian it's necessary only on Wheezy and in Ubuntu on Precise. Newer distributions usually have cgroups memory enabled by default.

**Comment by buschco** [comment]
I think it is jessie (in wok it says 8.5 OS Version).
But anyway that worked for me. 
Just had to add the line and restart the server.
Thank you I am very happy to be able to use the tool.

**Comment by pvital** [comment]
Glad that worked!

**Comment by mwacgi** [comment]
debian 8.7 x86_64 can't start vm:
KCHVM0019E: Unable to start virtual machine test. Details: unsupported configuration: Memory cgroup is not available on this host
edit /etc/default/grub can't work.
