### ISSUE TITLE
Troubles compiling (sass issues)

### ISSUE THREAD

**Issue by cjsoftuk** [kimchi-project/kimchi#995]
The latest version of sassc (from https://github.com/sass/sassc) no longer uses -s to select the output style.  Instead it uses -t. As a result, if you have the latest build of sassc installed from there, Ginger/Ginger Base/Kimchi fails to compile with an error compiling the sass to css ("Too Many Arguments.").

Having solved that by replacing -s with -t (the new option name), I hit a new error:
`
make[3]: Entering directory '/opt/kimchi/src/wok/plugins/gingerbase/ui/css'
echo "Compiling .scss file src/gingerbase.scss"
Compiling .scss file src/gingerbase.scss
sassc -t expanded src/gingerbase.scss gingerbase.css
Error: "#host-info-container .basic-information-list" failed to @extend ".row".
       The selector ".row" was not found.
       Use "@extend .row !optional" if the extend should be able to fail.
        on line 188 of src/modules/_host.scss
>>         @extend .row; // Extending bootstrap .row clearfix util
   --------^
`

This appears to be down to the fact that the bootstrap library isn't included into GingerBase's sass source, so it doesn't know about the .row class......

I am not familiar with sass etc, so I'm not sure how best to proceed.

**Comment by alinefm** [comment]
It is a Ginger Base issue. 
Kimchi already includes the compiled CSS into source code so you only need to rebuild it if you do changes on scss for new UI development.

I have mirrored this issue to Ginger Base.
