### ISSUE TITLE
Every time VMs are listed and if any VMs was not created via kimchi then it logs error in wok-error.log WOKOBJST0001E:

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/kimchi#997]
Every time VMs are listed and if any VMs was not created via kimchi then it logs error in wok-error.log.

WOKOBJST0001E: Unable to find 6d6d8e47-dfdb-4d13-a361-abf47136b719 in datastore
WOKOBJST0001E: Unable to find 241f2323-5900-4ef7-902b-b98d30362de5 in datastore
WOKOBJST0001E: Unable to find 5aad1e0f-ed22-4dd5-a34b-68f4861f9481 in datastore
WOKOBJST0001E: Unable to find dd430d5d-6884-4480-a59e-0490055bf613 in datastore

I guess it should be just warning or info message, in case of vm not in objectsore instead of logging it as error.

**Comment by danielhb** [comment]
Fixed by https://github.com/kimchi-project/kimchi/commit/47e348147fd20a16cc778ad86acdf6d8cc1e9a8f
